// Verilated -*- SystemC -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vsig_topology_top.h for the primary calling header

#ifndef VERILATED_VSIG_TOPOLOGY_TOP_SIG_SLC_BYPASS__PI20_H_
#define VERILATED_VSIG_TOPOLOGY_TOP_SIG_SLC_BYPASS__PI20_H_  // guard

#include "systemc"
#include "verilated_sc.h"
#include "verilated.h"
class Vsig_topology_top_sig_fifo_synchclk_flop__pi36;
class Vsig_topology_top_sig_fifo_synchclk_flop__pi37;
class Vsig_topology_top_sig_ic_crdt_recv;
class Vsig_topology_top_sig_ic_crdt_update__N8;
class Vsig_topology_top_sig_ic_initcrdt_enable;


class Vsig_topology_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vsig_topology_top_sig_slc_bypass__pi20 final : public VerilatedModule {
  public:
    // CELLS
    Vsig_topology_top_sig_fifo_synchclk_flop__pi36* __PVT__reqflit_fifo_0;
    Vsig_topology_top_sig_fifo_synchclk_flop__pi37* __PVT__pcredit_fifo;
    Vsig_topology_top_sig_ic_crdt_recv* __PVT__sig_ic_crdt_recv_dat;
    Vsig_topology_top_sig_ic_crdt_recv* __PVT__sig_ic_crdt_recv_req;
    Vsig_topology_top_sig_ic_initcrdt_enable* __PVT__sig_ic_initcrdt_enable_0;
    Vsig_topology_top_sig_ic_crdt_update__N8* __PVT__sig_ic_crdt_update_dat;
    Vsig_topology_top_sig_ic_crdt_update__N8* __PVT__sig_ic_crdt_update_rsp;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(__PVT__slc_bypass_clk,0,0);
        VL_IN8(__PVT__slc_bypass_gclk,0,0);
        VL_IN8(__PVT__rstb_slc_bypass_clk,0,0);
        VL_IN8(__PVT__cc_reqflit_valid,0,0);
        VL_IN8(__PVT__cc_reqflit_metadata,2,0);
        VL_OUT8(__PVT__slc_reqflit_fifo_full,0,0);
        VL_IN8(__PVT__slc_wrdata_valid,0,0);
        VL_IN8(__PVT__slc_drop_wrdata,0,0);
        VL_OUT8(__PVT__slc_wrdatabuf_hasroom,0,0);
        VL_OUT8(__PVT__slc_rspvalid,0,0);
        VL_OUT8(__PVT__compdata_valid,0,0);
        VL_OUT8(__PVT__compresperr_tocc,1,0);
        VL_OUT8(__PVT__ic_TX_REQFLITPEND,0,0);
        VL_OUT8(__PVT__ic_TX_REQFLITV,0,0);
        VL_OUT8(__PVT__ic_TX_REQFLIT_snp_or_req_bit,0,0);
        VL_IN8(__PVT__ic_TX_REQLCRDV,0,0);
        VL_IN8(__PVT__ic_RX_DATFLITPEND,0,0);
        VL_IN8(__PVT__ic_RX_DATFLITV,0,0);
        VL_OUT8(__PVT__ic_RX_DATLCRDV,0,0);
        VL_IN8(__PVT__ic_RX_RSPFLITPEND,0,0);
        VL_IN8(__PVT__ic_RX_RSPFLITV,0,0);
        VL_OUT8(__PVT__ic_RX_RSPLCRDV,0,0);
        VL_OUT8(__PVT__ic_TX_DATFLITPEND,0,0);
        VL_OUT8(__PVT__ic_TX_DATFLITV,0,0);
        VL_IN8(__PVT__ic_TX_DATLCRDV,0,0);
        VL_IN8(__PVT__mycluster_id,7,0);
        CData/*0:0*/ __PVT__wren_reqflit_fifo;
        CData/*0:0*/ __PVT__rden_reqflit_fifo;
        CData/*0:0*/ __PVT__empty_reqflit_fifo;
        CData/*1:0*/ __PVT__cmdproc_st;
        CData/*1:0*/ __PVT__cmdproc_st_nxt;
        CData/*0:0*/ __PVT__rd_txnid_buff_full;
        CData/*0:0*/ __PVT__allocate_rd_txnid_buff;
        CData/*3:0*/ __PVT__rd_txnid_buffer_selected;
        CData/*3:0*/ __PVT__rd_txnid_buffer_selected_nxt;
        CData/*3:0*/ __PVT__index_rd_txnid_buff_rx_datf;
        CData/*0:0*/ __PVT__rst_rd_txnid_buff;
        CData/*0:0*/ __PVT__latch_txnid;
        CData/*0:0*/ __PVT__wr_addr_buff_full;
        CData/*0:0*/ __PVT__allocate_wr_addr_buff;
        CData/*3:0*/ __PVT__wr_addr_buffer_selected;
        CData/*3:0*/ __PVT__wr_addr_buffer_selected_nxt;
        CData/*0:0*/ __PVT__allocate_wr_zero_buff;
        CData/*0:0*/ __PVT__is_wr_zero_req;
        CData/*0:0*/ __PVT__is_wr_zero_dat;
        CData/*0:0*/ __PVT__rst_wr_addr_buff;
        CData/*3:0*/ __PVT__index_wr_addr_buff_wr_rspf;
        CData/*0:0*/ __PVT__allocate_wr_comp_buff;
        CData/*0:0*/ __PVT__allocate_rd_txnid_buff_outstanding_reqf;
        CData/*0:0*/ __PVT__outstanding_wr_addr_matched;
        CData/*0:0*/ __PVT__allocate_rd_reqf_buff;
        CData/*0:0*/ __PVT__allocate_select_rd_reqf_pointer;
        CData/*3:0*/ __PVT__rd_reqf_matched_wr_index;
        CData/*0:0*/ __PVT__rd_reqf_buff_full;
        CData/*3:0*/ __PVT__store_outstanding_rd_reqf_buffer_pointer;
        CData/*3:0*/ __PVT__store_outstanding_rd_reqf_buffer_pointer_nxt;
        CData/*3:0*/ __PVT__select_outstanding_rd_reqf_buffer_pointer;
        CData/*3:0*/ __PVT__select_outstanding_rd_reqf_buffer_pointer_nxt;
        CData/*0:0*/ __PVT__outstanding_rd_reqf_ready;
        CData/*0:0*/ __PVT__outstanding_rd_reqf_bit;
        CData/*0:0*/ __PVT__flit_dmt_en;
        CData/*0:0*/ __PVT__assert_memwr_req;
        CData/*0:0*/ __PVT__assert_memrd_req;
        CData/*0:0*/ __PVT__allocate_wr_data_buff;
    };
    struct {
        CData/*0:0*/ __PVT__drop_wr_addr;
        CData/*3:0*/ __PVT__store_wr_data_index_buffer_pointer;
        CData/*3:0*/ __PVT__store_wr_data_index_buffer_pointer_nxt;
        CData/*3:0*/ __PVT__select_wr_data_index_buffer_pointer;
        CData/*3:0*/ __PVT__select_wr_data_index_buffer_pointer_nxt;
        CData/*0:0*/ __PVT__rst_wr_data_index_buffer;
        CData/*3:0*/ __PVT__wr_data_buffer_index;
        CData/*3:0*/ __PVT__wr_mem_qos;
        CData/*0:0*/ __PVT__wr_mem_ns;
        CData/*3:0*/ __PVT__wr_mem_memattr;
        CData/*0:0*/ __PVT__allocate_wr_dbid_buff;
        CData/*3:0*/ __PVT__wr_dbid_buffer_index_from_slavemem;
        CData/*3:0*/ __PVT__wr_buffer_index;
        CData/*3:0*/ __PVT__wr_qos_tx_datf;
        CData/*0:0*/ __PVT__rst_wr_buff;
        CData/*0:0*/ __PVT__send_write_data;
        CData/*0:0*/ __PVT__cm_addr_match_pm;
        CData/*0:0*/ __PVT__cm_activated_pm;
        CData/*0:0*/ __PVT__consumed_xmt_dat_crdt;
        CData/*0:0*/ __PVT__port_has_xmt_dat_crdt;
        CData/*3:0*/ __PVT__xmt_dat_crdt_available;
        CData/*0:0*/ __PVT__consumed_xmt_req_crdt;
        CData/*0:0*/ __PVT__port_has_xmt_req_crdt;
        CData/*3:0*/ __PVT__xmt_req_crdt_available;
        CData/*0:0*/ __PVT__enable_init_update;
        CData/*0:0*/ __PVT__update_dat_crdt;
        CData/*0:0*/ __PVT__drive_xLCRDV_dat;
        CData/*0:0*/ __PVT__update_rsp_crdt;
        CData/*0:0*/ __PVT__drive_xLCRDV_rsp;
        CData/*0:0*/ __PVT__rdretrytxn_avail;
        CData/*0:0*/ __PVT__rdretrybuf_full;
        CData/*0:0*/ __PVT__wrretrytxn_avail;
        CData/*0:0*/ __PVT__wrretrybuf_full;
        CData/*0:0*/ __PVT__got_dbidresp;
        CData/*0:0*/ __PVT__got_retryackresp;
        CData/*3:0*/ __PVT__retryack_bufv_index;
        CData/*0:0*/ __PVT__wren_pcredit_fifo;
        CData/*0:0*/ __PVT__rden_pcredit_fifo;
        CData/*0:0*/ __PVT__full_pcredit_fifo;
        CData/*0:0*/ __PVT__empty_pcredit_fifo;
        CData/*0:0*/ __PVT__req_cmo;
        CData/*0:0*/ __PVT__outstand_req_cmo;
        CData/*0:0*/ __PVT__send_outstand_req_cmo;
        CData/*0:0*/ __PVT__assert_slc_rspvalid;
        CData/*0:0*/ __PVT__send_dbidresp;
        CData/*0:0*/ __PVT__send_compdbidresp;
        CData/*0:0*/ __PVT__send_late_comp_resp;
        CData/*0:0*/ __PVT__matched_inpending_wr;
        CData/*0:0*/ __PVT__retryack_buf_wrrd;
        CData/*3:0*/ __Vfunc_clog2_txnid__0__Vfuncout;
        CData/*3:0*/ __Vfunc_clog2_addr__1__Vfuncout;
        CData/*3:0*/ __Vfunc_clog2_addr__2__Vfuncout;
        CData/*3:0*/ __Vfunc_clog2_addr__3__Vfuncout;
        CData/*3:0*/ __Vfunc_clog2_addr__4__Vfuncout;
        CData/*3:0*/ __Vfunc_clog2_txnid__5__Vfuncout;
        CData/*1:0*/ __Vdly__cmdproc_st;
        CData/*3:0*/ __Vdly__rd_txnid_buffer_selected;
        CData/*3:0*/ __Vdly__wr_addr_buffer_selected;
        CData/*3:0*/ __Vdly__store_outstanding_rd_reqf_buffer_pointer;
        CData/*3:0*/ __Vdly__select_outstanding_rd_reqf_buffer_pointer;
        CData/*3:0*/ __Vdly__store_wr_data_index_buffer_pointer;
        CData/*3:0*/ __Vdly__select_wr_data_index_buffer_pointer;
        CData/*0:0*/ __Vdly__ic_RX_RSPLCRDV;
        CData/*0:0*/ __Vdly__ic_RX_DATLCRDV;
    };
    struct {
        CData/*0:0*/ __VdlySet__rd_txnid_buffer__v0;
        CData/*0:0*/ __VdlySet__rd_txnid_buffer__v16;
        CData/*0:0*/ __VdlySet__rd_txnid_buffer__v17;
        CData/*0:0*/ __VdlySet__rd_txnid_buffer__v18;
        CData/*0:0*/ __VdlySet__rd_txnid_buffer__v19;
        CData/*0:0*/ __VdlySet__rd_txnid_buffer__v20;
        CData/*0:0*/ __VdlySet__rd_txnid_buffer__v21;
        CData/*0:0*/ __VdlySet__rd_txnid_buffer__v22;
        CData/*0:0*/ __VdlySet__rd_txnid_buffer__v23;
        CData/*0:0*/ __VdlySet__rd_txnid_buffer__v24;
        CData/*0:0*/ __VdlySet__rd_txnid_buffer__v25;
        CData/*0:0*/ __VdlySet__rd_txnid_buffer__v26;
        CData/*0:0*/ __VdlySet__rd_txnid_buffer__v27;
        CData/*0:0*/ __VdlySet__rd_txnid_buffer__v28;
        CData/*0:0*/ __VdlySet__rd_txnid_buffer__v29;
        CData/*0:0*/ __VdlySet__rd_txnid_buffer__v30;
        CData/*0:0*/ __VdlySet__rd_txnid_buffer__v31;
        CData/*0:0*/ __VdlySet__wr_addr_buffer__v0;
        CData/*3:0*/ __VdlyVal__wr_qos_buffer__v0;
        CData/*3:0*/ __VdlyVal__wr_qos_buffer__v1;
        CData/*3:0*/ __VdlyVal__wr_qos_buffer__v2;
        CData/*3:0*/ __VdlyVal__wr_qos_buffer__v3;
        CData/*3:0*/ __VdlyVal__wr_qos_buffer__v4;
        CData/*3:0*/ __VdlyVal__wr_qos_buffer__v5;
        CData/*3:0*/ __VdlyVal__wr_qos_buffer__v6;
        CData/*3:0*/ __VdlyVal__wr_qos_buffer__v7;
        CData/*3:0*/ __VdlyVal__wr_qos_buffer__v8;
        CData/*3:0*/ __VdlyVal__wr_qos_buffer__v9;
        CData/*3:0*/ __VdlyVal__wr_qos_buffer__v10;
        CData/*3:0*/ __VdlyVal__wr_qos_buffer__v11;
        CData/*3:0*/ __VdlyVal__wr_qos_buffer__v12;
        CData/*3:0*/ __VdlyVal__wr_qos_buffer__v13;
        CData/*3:0*/ __VdlyVal__wr_qos_buffer__v14;
        CData/*3:0*/ __VdlyVal__wr_qos_buffer__v15;
        CData/*0:0*/ __VdlyVal__wr_ns_buffer__v0;
        CData/*0:0*/ __VdlyVal__wr_ns_buffer__v1;
        CData/*0:0*/ __VdlyVal__wr_ns_buffer__v2;
        CData/*0:0*/ __VdlyVal__wr_ns_buffer__v3;
        CData/*0:0*/ __VdlyVal__wr_ns_buffer__v4;
        CData/*0:0*/ __VdlyVal__wr_ns_buffer__v5;
        CData/*0:0*/ __VdlyVal__wr_ns_buffer__v6;
        CData/*0:0*/ __VdlyVal__wr_ns_buffer__v7;
        CData/*0:0*/ __VdlyVal__wr_ns_buffer__v8;
        CData/*0:0*/ __VdlyVal__wr_ns_buffer__v9;
        CData/*0:0*/ __VdlyVal__wr_ns_buffer__v10;
        CData/*0:0*/ __VdlyVal__wr_ns_buffer__v11;
        CData/*0:0*/ __VdlyVal__wr_ns_buffer__v12;
        CData/*0:0*/ __VdlyVal__wr_ns_buffer__v13;
        CData/*0:0*/ __VdlyVal__wr_ns_buffer__v14;
        CData/*0:0*/ __VdlyVal__wr_ns_buffer__v15;
        CData/*3:0*/ __VdlyVal__wr_memattr_buffer__v0;
        CData/*3:0*/ __VdlyVal__wr_memattr_buffer__v1;
        CData/*3:0*/ __VdlyVal__wr_memattr_buffer__v2;
        CData/*3:0*/ __VdlyVal__wr_memattr_buffer__v3;
        CData/*3:0*/ __VdlyVal__wr_memattr_buffer__v4;
        CData/*3:0*/ __VdlyVal__wr_memattr_buffer__v5;
        CData/*3:0*/ __VdlyVal__wr_memattr_buffer__v6;
        CData/*3:0*/ __VdlyVal__wr_memattr_buffer__v7;
        CData/*3:0*/ __VdlyVal__wr_memattr_buffer__v8;
        CData/*3:0*/ __VdlyVal__wr_memattr_buffer__v9;
        CData/*3:0*/ __VdlyVal__wr_memattr_buffer__v10;
        CData/*3:0*/ __VdlyVal__wr_memattr_buffer__v11;
        CData/*3:0*/ __VdlyVal__wr_memattr_buffer__v12;
        CData/*3:0*/ __VdlyVal__wr_memattr_buffer__v13;
    };
    struct {
        CData/*3:0*/ __VdlyVal__wr_memattr_buffer__v14;
        CData/*3:0*/ __VdlyVal__wr_memattr_buffer__v15;
        CData/*0:0*/ __VdlySet__wr_addr_buffer__v16;
        CData/*0:0*/ __VdlySet__wr_addr_buffer__v17;
        CData/*0:0*/ __VdlySet__wr_addr_buffer__v18;
        CData/*0:0*/ __VdlySet__wr_addr_buffer__v19;
        CData/*0:0*/ __VdlySet__wr_addr_buffer__v20;
        CData/*0:0*/ __VdlySet__wr_addr_buffer__v21;
        CData/*0:0*/ __VdlySet__wr_addr_buffer__v22;
        CData/*0:0*/ __VdlySet__wr_addr_buffer__v23;
        CData/*0:0*/ __VdlySet__wr_addr_buffer__v24;
        CData/*0:0*/ __VdlySet__wr_addr_buffer__v25;
        CData/*0:0*/ __VdlySet__wr_addr_buffer__v26;
        CData/*0:0*/ __VdlySet__wr_addr_buffer__v27;
        CData/*0:0*/ __VdlySet__wr_addr_buffer__v28;
        CData/*0:0*/ __VdlySet__wr_addr_buffer__v29;
        CData/*0:0*/ __VdlySet__wr_addr_buffer__v30;
        CData/*0:0*/ __VdlySet__wr_addr_buffer__v31;
        CData/*0:0*/ __VdlySet__rd_reqf_buffer__v0;
        CData/*0:0*/ __VdlySet__rd_reqf_buffer__v16;
        CData/*0:0*/ __VdlySet__rd_reqf_buffer__v17;
        CData/*0:0*/ __VdlySet__rd_reqf_buffer__v18;
        CData/*0:0*/ __VdlySet__rd_reqf_buffer__v19;
        CData/*0:0*/ __VdlySet__rd_reqf_buffer__v20;
        CData/*0:0*/ __VdlySet__rd_reqf_buffer__v21;
        CData/*0:0*/ __VdlySet__rd_reqf_buffer__v22;
        CData/*0:0*/ __VdlySet__rd_reqf_buffer__v23;
        CData/*0:0*/ __VdlySet__rd_reqf_buffer__v24;
        CData/*0:0*/ __VdlySet__rd_reqf_buffer__v25;
        CData/*0:0*/ __VdlySet__rd_reqf_buffer__v26;
        CData/*0:0*/ __VdlySet__rd_reqf_buffer__v27;
        CData/*0:0*/ __VdlySet__rd_reqf_buffer__v28;
        CData/*0:0*/ __VdlySet__rd_reqf_buffer__v29;
        CData/*0:0*/ __VdlySet__rd_reqf_buffer__v30;
        CData/*0:0*/ __VdlySet__rd_reqf_buffer__v31;
        CData/*3:0*/ __VdlyVal__wr_data_index_buffer__v0;
        CData/*0:0*/ __VdlySet__wr_data_index_buffer__v0;
        CData/*3:0*/ __VdlyVal__wr_data_index_buffer__v1;
        CData/*3:0*/ __VdlyVal__wr_data_index_buffer__v2;
        CData/*3:0*/ __VdlyVal__wr_data_index_buffer__v3;
        CData/*3:0*/ __VdlyVal__wr_data_index_buffer__v4;
        CData/*3:0*/ __VdlyVal__wr_data_index_buffer__v5;
        CData/*3:0*/ __VdlyVal__wr_data_index_buffer__v6;
        CData/*3:0*/ __VdlyVal__wr_data_index_buffer__v7;
        CData/*3:0*/ __VdlyVal__wr_data_index_buffer__v8;
        CData/*3:0*/ __VdlyVal__wr_data_index_buffer__v9;
        CData/*3:0*/ __VdlyVal__wr_data_index_buffer__v10;
        CData/*3:0*/ __VdlyVal__wr_data_index_buffer__v11;
        CData/*3:0*/ __VdlyVal__wr_data_index_buffer__v12;
        CData/*3:0*/ __VdlyVal__wr_data_index_buffer__v13;
        CData/*3:0*/ __VdlyVal__wr_data_index_buffer__v14;
        CData/*3:0*/ __VdlyVal__wr_data_index_buffer__v15;
        CData/*0:0*/ __VdlySet__wr_data_index_buffer__v16;
        CData/*0:0*/ __VdlySet__wr_data_index_buffer__v17;
        CData/*0:0*/ __VdlySet__wr_data_index_buffer__v18;
        CData/*0:0*/ __VdlySet__wr_data_index_buffer__v19;
        CData/*0:0*/ __VdlySet__wr_data_index_buffer__v20;
        CData/*0:0*/ __VdlySet__wr_data_index_buffer__v21;
        CData/*0:0*/ __VdlySet__wr_data_index_buffer__v22;
        CData/*0:0*/ __VdlySet__wr_data_index_buffer__v23;
        CData/*0:0*/ __VdlySet__wr_data_index_buffer__v24;
        CData/*0:0*/ __VdlySet__wr_data_index_buffer__v25;
        CData/*0:0*/ __VdlySet__wr_data_index_buffer__v26;
        CData/*0:0*/ __VdlySet__wr_data_index_buffer__v27;
    };
    struct {
        CData/*0:0*/ __VdlySet__wr_data_index_buffer__v28;
        CData/*0:0*/ __VdlySet__wr_data_index_buffer__v29;
        CData/*0:0*/ __VdlySet__wr_data_index_buffer__v30;
        CData/*0:0*/ __VdlySet__wr_data_index_buffer__v31;
        CData/*3:0*/ __VdlyVal__wr_dbid_index_buffer__v0;
        CData/*0:0*/ __VdlySet__wr_dbid_index_buffer__v0;
        CData/*3:0*/ __VdlyVal__wr_dbid_index_buffer__v1;
        CData/*3:0*/ __VdlyVal__wr_dbid_index_buffer__v2;
        CData/*3:0*/ __VdlyVal__wr_dbid_index_buffer__v3;
        CData/*3:0*/ __VdlyVal__wr_dbid_index_buffer__v4;
        CData/*3:0*/ __VdlyVal__wr_dbid_index_buffer__v5;
        CData/*3:0*/ __VdlyVal__wr_dbid_index_buffer__v6;
        CData/*3:0*/ __VdlyVal__wr_dbid_index_buffer__v7;
        CData/*3:0*/ __VdlyVal__wr_dbid_index_buffer__v8;
        CData/*3:0*/ __VdlyVal__wr_dbid_index_buffer__v9;
        CData/*3:0*/ __VdlyVal__wr_dbid_index_buffer__v10;
        CData/*3:0*/ __VdlyVal__wr_dbid_index_buffer__v11;
        CData/*3:0*/ __VdlyVal__wr_dbid_index_buffer__v12;
        CData/*3:0*/ __VdlyVal__wr_dbid_index_buffer__v13;
        CData/*3:0*/ __VdlyVal__wr_dbid_index_buffer__v14;
        CData/*3:0*/ __VdlyVal__wr_dbid_index_buffer__v15;
        CData/*0:0*/ __VdlySet__wr_dbid_index_buffer__v16;
        CData/*0:0*/ __VdlySet__wr_dbid_index_buffer__v17;
        CData/*0:0*/ __VdlySet__wr_dbid_index_buffer__v18;
        CData/*0:0*/ __VdlySet__wr_dbid_index_buffer__v19;
        CData/*0:0*/ __VdlySet__wr_dbid_index_buffer__v20;
        CData/*0:0*/ __VdlySet__wr_dbid_index_buffer__v21;
        CData/*0:0*/ __VdlySet__wr_dbid_index_buffer__v22;
        CData/*0:0*/ __VdlySet__wr_dbid_index_buffer__v23;
        CData/*0:0*/ __VdlySet__wr_dbid_index_buffer__v24;
        CData/*0:0*/ __VdlySet__wr_dbid_index_buffer__v25;
        CData/*0:0*/ __VdlySet__wr_dbid_index_buffer__v26;
        CData/*0:0*/ __VdlySet__wr_dbid_index_buffer__v27;
        CData/*0:0*/ __VdlySet__wr_dbid_index_buffer__v28;
        CData/*0:0*/ __VdlySet__wr_dbid_index_buffer__v29;
        CData/*0:0*/ __VdlySet__wr_dbid_index_buffer__v30;
        CData/*0:0*/ __VdlySet__wr_dbid_index_buffer__v31;
        CData/*0:0*/ __VdlySet__rdretryack_buf__v0;
        CData/*0:0*/ __VdlySet__wrretryack_buf__v0;
        CData/*0:0*/ __VdlySet__memrdretry_buf__v0;
        CData/*0:0*/ __VdlySet__rdretryack_buf__v16;
        CData/*0:0*/ __VdlySet__rdretryack_buf__v17;
        CData/*0:0*/ __VdlySet__rdretryack_buf__v18;
        CData/*0:0*/ __VdlySet__rdretryack_buf__v19;
        CData/*0:0*/ __VdlySet__rdretryack_buf__v20;
        CData/*0:0*/ __VdlySet__rdretryack_buf__v21;
        CData/*0:0*/ __VdlySet__rdretryack_buf__v22;
        CData/*0:0*/ __VdlySet__rdretryack_buf__v23;
        CData/*0:0*/ __VdlySet__rdretryack_buf__v24;
        CData/*0:0*/ __VdlySet__rdretryack_buf__v25;
        CData/*0:0*/ __VdlySet__rdretryack_buf__v26;
        CData/*0:0*/ __VdlySet__rdretryack_buf__v27;
        CData/*0:0*/ __VdlySet__rdretryack_buf__v28;
        CData/*0:0*/ __VdlySet__rdretryack_buf__v29;
        CData/*0:0*/ __VdlySet__rdretryack_buf__v30;
        CData/*0:0*/ __VdlySet__rdretryack_buf__v31;
        CData/*0:0*/ __VdlySet__wrretryack_buf__v16;
        CData/*0:0*/ __VdlySet__wrretryack_buf__v17;
        CData/*0:0*/ __VdlySet__wrretryack_buf__v18;
        CData/*0:0*/ __VdlySet__wrretryack_buf__v19;
        CData/*0:0*/ __VdlySet__wrretryack_buf__v20;
        CData/*0:0*/ __VdlySet__wrretryack_buf__v21;
        CData/*0:0*/ __VdlySet__wrretryack_buf__v22;
        CData/*0:0*/ __VdlySet__wrretryack_buf__v23;
    };
    struct {
        CData/*0:0*/ __VdlySet__wrretryack_buf__v24;
        CData/*0:0*/ __VdlySet__wrretryack_buf__v25;
        CData/*0:0*/ __VdlySet__wrretryack_buf__v26;
        CData/*0:0*/ __VdlySet__wrretryack_buf__v27;
        CData/*0:0*/ __VdlySet__wrretryack_buf__v28;
        CData/*0:0*/ __VdlySet__wrretryack_buf__v29;
        CData/*0:0*/ __VdlySet__wrretryack_buf__v30;
        CData/*0:0*/ __VdlySet__wrretryack_buf__v31;
        VL_IN16(__PVT__dbid_from_slc,11,0);
        VL_OUT16(__PVT__comptxnid_tocc,12,0);
        VL_IN16(__PVT__xy_coord_all_pm,10,0);
        SData/*15:0*/ __PVT__rd_txnid_buffer_bit_available;
        SData/*15:0*/ __PVT__rd_txnid_buffer_bit_available_nxt;
        SData/*15:0*/ __PVT__wren_rd_txnid_buff;
        SData/*15:0*/ __PVT__wr_addr_buffer_bit_available;
        SData/*15:0*/ __PVT__wr_addr_buffer_bit_available_nxt;
        SData/*15:0*/ __PVT__wr_received_dbid_bit;
        SData/*15:0*/ __PVT__wr_received_dbid_bit_nxt;
        SData/*15:0*/ __PVT__wr_zero_buffer;
        SData/*15:0*/ __PVT__wr_zero_buffer_nxt;
        SData/*15:0*/ __PVT__wren_wr_addr_buff;
        SData/*15:0*/ __PVT__wr_sent_data_bit;
        SData/*15:0*/ __PVT__wr_sent_data_bit_nxt;
        SData/*15:0*/ __PVT__wr_received_sn_comp_bit;
        SData/*15:0*/ __PVT__wr_received_sn_comp_bit_nxt;
        SData/*15:0*/ __PVT__clear_wr_buffer;
        SData/*15:0*/ __PVT__outstanding_wr_addr_match;
        SData/*15:0*/ __PVT__rd_reqf_buffer_bit_available;
        SData/*15:0*/ __PVT__rd_reqf_buffer_bit_available_nxt;
        SData/*11:0*/ __PVT__txnid_from_cc;
        SData/*15:0*/ __PVT__outstanding_wr_match_outstanding_rd;
        SData/*15:0*/ __PVT__wr_data_index_buffer_bit;
        SData/*15:0*/ __PVT__wr_data_index_buffer_bit_nxt;
        SData/*11:0*/ __PVT__dbid_from_slavemem;
        SData/*15:0*/ __PVT__wr_dbid_index_buffer_bit;
        SData/*15:0*/ __PVT__wr_dbid_index_buffer_bit_nxt;
        SData/*15:0*/ __PVT__wr_dbid_index_buffer_bit_select;
        SData/*11:0*/ __PVT__wr_dbid_tx_datf;
        SData/*10:0*/ __PVT__tgt_pm_node_id;
        SData/*15:0*/ __PVT__rd_pcredithit_select;
        SData/*15:0*/ __PVT__rd_pcredithit;
        SData/*15:0*/ __PVT__wr_pcredithit_select;
        SData/*15:0*/ __PVT__wr_pcredithit;
        SData/*15:0*/ __PVT__clr_rdretryack_bufv;
        SData/*15:0*/ __PVT__clr_wrretryack_bufv;
        SData/*14:0*/ __PVT__retryack_buf_entry;
        SData/*15:0*/ __PVT__rdretryack_bufv;
        SData/*15:0*/ __PVT__rdretryack_bufv_nxt;
        SData/*15:0*/ __PVT__wrretryack_bufv;
        SData/*15:0*/ __PVT__wrretryack_bufv_nxt;
        SData/*14:0*/ __PVT__wrdata_pcredit_fifo;
        SData/*14:0*/ __PVT__rddata_pcredit_fifo;
        SData/*15:0*/ __PVT__wr_req_sent_nxt;
        SData/*15:0*/ __PVT__wr_req_sent;
        SData/*15:0*/ __PVT__match_inpending_wr;
        SData/*15:0*/ __Vfunc_clog2_txnid__0__set_bit_location;
        SData/*15:0*/ __Vfunc_clog2_addr__1__set_bit_location;
        SData/*15:0*/ __Vfunc_clog2_addr__2__set_bit_location;
        SData/*15:0*/ __Vfunc_clog2_addr__3__set_bit_location;
        SData/*15:0*/ __Vfunc_clog2_addr__4__set_bit_location;
        SData/*15:0*/ __Vfunc_clog2_txnid__5__set_bit_location;
        SData/*15:0*/ __Vdly__rd_txnid_buffer_bit_available;
        SData/*15:0*/ __Vdly__wr_sent_data_bit;
        SData/*15:0*/ __Vdly__wr_received_sn_comp_bit;
    };
    struct {
        SData/*15:0*/ __Vdly__wr_addr_buffer_bit_available;
        SData/*15:0*/ __Vdly__wr_received_dbid_bit;
        SData/*15:0*/ __Vdly__wr_zero_buffer;
        SData/*15:0*/ __Vdly__rd_reqf_buffer_bit_available;
        SData/*15:0*/ __Vdly__wr_req_sent;
        SData/*15:0*/ __Vdly__wr_data_index_buffer_bit;
        SData/*15:0*/ __Vdly__wr_dbid_index_buffer_bit;
        SData/*15:0*/ __Vdly__rdretryack_bufv;
        SData/*15:0*/ __Vdly__wrretryack_bufv;
        SData/*11:0*/ __VdlyVal__rd_txnid_buffer__v0;
        SData/*11:0*/ __VdlyVal__rd_txnid_buffer__v1;
        SData/*11:0*/ __VdlyVal__rd_txnid_buffer__v2;
        SData/*11:0*/ __VdlyVal__rd_txnid_buffer__v3;
        SData/*11:0*/ __VdlyVal__rd_txnid_buffer__v4;
        SData/*11:0*/ __VdlyVal__rd_txnid_buffer__v5;
        SData/*11:0*/ __VdlyVal__rd_txnid_buffer__v6;
        SData/*11:0*/ __VdlyVal__rd_txnid_buffer__v7;
        SData/*11:0*/ __VdlyVal__rd_txnid_buffer__v8;
        SData/*11:0*/ __VdlyVal__rd_txnid_buffer__v9;
        SData/*11:0*/ __VdlyVal__rd_txnid_buffer__v10;
        SData/*11:0*/ __VdlyVal__rd_txnid_buffer__v11;
        SData/*11:0*/ __VdlyVal__rd_txnid_buffer__v12;
        SData/*11:0*/ __VdlyVal__rd_txnid_buffer__v13;
        SData/*11:0*/ __VdlyVal__rd_txnid_buffer__v14;
        SData/*11:0*/ __VdlyVal__rd_txnid_buffer__v15;
        SData/*10:0*/ __VdlyVal__wr_tgtid_buffer__v0;
        SData/*10:0*/ __VdlyVal__wr_tgtid_buffer__v1;
        SData/*10:0*/ __VdlyVal__wr_tgtid_buffer__v2;
        SData/*10:0*/ __VdlyVal__wr_tgtid_buffer__v3;
        SData/*10:0*/ __VdlyVal__wr_tgtid_buffer__v4;
        SData/*10:0*/ __VdlyVal__wr_tgtid_buffer__v5;
        SData/*10:0*/ __VdlyVal__wr_tgtid_buffer__v6;
        SData/*10:0*/ __VdlyVal__wr_tgtid_buffer__v7;
        SData/*10:0*/ __VdlyVal__wr_tgtid_buffer__v8;
        SData/*10:0*/ __VdlyVal__wr_tgtid_buffer__v9;
        SData/*10:0*/ __VdlyVal__wr_tgtid_buffer__v10;
        SData/*10:0*/ __VdlyVal__wr_tgtid_buffer__v11;
        SData/*10:0*/ __VdlyVal__wr_tgtid_buffer__v12;
        SData/*10:0*/ __VdlyVal__wr_tgtid_buffer__v13;
        SData/*10:0*/ __VdlyVal__wr_tgtid_buffer__v14;
        SData/*10:0*/ __VdlyVal__wr_tgtid_buffer__v15;
        SData/*11:0*/ __VdlyVal__wr_txnid_buffer__v0;
        SData/*11:0*/ __VdlyVal__wr_txnid_buffer__v1;
        SData/*11:0*/ __VdlyVal__wr_txnid_buffer__v2;
        SData/*11:0*/ __VdlyVal__wr_txnid_buffer__v3;
        SData/*11:0*/ __VdlyVal__wr_txnid_buffer__v4;
        SData/*11:0*/ __VdlyVal__wr_txnid_buffer__v5;
        SData/*11:0*/ __VdlyVal__wr_txnid_buffer__v6;
        SData/*11:0*/ __VdlyVal__wr_txnid_buffer__v7;
        SData/*11:0*/ __VdlyVal__wr_txnid_buffer__v8;
        SData/*11:0*/ __VdlyVal__wr_txnid_buffer__v9;
        SData/*11:0*/ __VdlyVal__wr_txnid_buffer__v10;
        SData/*11:0*/ __VdlyVal__wr_txnid_buffer__v11;
        SData/*11:0*/ __VdlyVal__wr_txnid_buffer__v12;
        SData/*11:0*/ __VdlyVal__wr_txnid_buffer__v13;
        SData/*11:0*/ __VdlyVal__wr_txnid_buffer__v14;
        SData/*11:0*/ __VdlyVal__wr_txnid_buffer__v15;
        SData/*11:0*/ __VdlyVal__wr_dbid_buffer__v0;
        SData/*11:0*/ __VdlyVal__wr_dbid_buffer__v1;
        SData/*11:0*/ __VdlyVal__wr_dbid_buffer__v2;
        SData/*11:0*/ __VdlyVal__wr_dbid_buffer__v3;
        SData/*11:0*/ __VdlyVal__wr_dbid_buffer__v4;
        SData/*11:0*/ __VdlyVal__wr_dbid_buffer__v5;
        SData/*11:0*/ __VdlyVal__wr_dbid_buffer__v6;
    };
    struct {
        SData/*11:0*/ __VdlyVal__wr_dbid_buffer__v7;
        SData/*11:0*/ __VdlyVal__wr_dbid_buffer__v8;
        SData/*11:0*/ __VdlyVal__wr_dbid_buffer__v9;
        SData/*11:0*/ __VdlyVal__wr_dbid_buffer__v10;
        SData/*11:0*/ __VdlyVal__wr_dbid_buffer__v11;
        SData/*11:0*/ __VdlyVal__wr_dbid_buffer__v12;
        SData/*11:0*/ __VdlyVal__wr_dbid_buffer__v13;
        SData/*11:0*/ __VdlyVal__wr_dbid_buffer__v14;
        SData/*11:0*/ __VdlyVal__wr_dbid_buffer__v15;
        SData/*14:0*/ __VdlyVal__rdretryack_buf__v0;
        SData/*14:0*/ __VdlyVal__rdretryack_buf__v1;
        SData/*14:0*/ __VdlyVal__rdretryack_buf__v2;
        SData/*14:0*/ __VdlyVal__rdretryack_buf__v3;
        SData/*14:0*/ __VdlyVal__rdretryack_buf__v4;
        SData/*14:0*/ __VdlyVal__rdretryack_buf__v5;
        SData/*14:0*/ __VdlyVal__rdretryack_buf__v6;
        SData/*14:0*/ __VdlyVal__rdretryack_buf__v7;
        SData/*14:0*/ __VdlyVal__rdretryack_buf__v8;
        SData/*14:0*/ __VdlyVal__rdretryack_buf__v9;
        SData/*14:0*/ __VdlyVal__rdretryack_buf__v10;
        SData/*14:0*/ __VdlyVal__rdretryack_buf__v11;
        SData/*14:0*/ __VdlyVal__rdretryack_buf__v12;
        SData/*14:0*/ __VdlyVal__rdretryack_buf__v13;
        SData/*14:0*/ __VdlyVal__rdretryack_buf__v14;
        SData/*14:0*/ __VdlyVal__rdretryack_buf__v15;
        SData/*14:0*/ __VdlyVal__wrretryack_buf__v0;
        SData/*14:0*/ __VdlyVal__wrretryack_buf__v1;
        SData/*14:0*/ __VdlyVal__wrretryack_buf__v2;
        SData/*14:0*/ __VdlyVal__wrretryack_buf__v3;
        SData/*14:0*/ __VdlyVal__wrretryack_buf__v4;
        SData/*14:0*/ __VdlyVal__wrretryack_buf__v5;
        SData/*14:0*/ __VdlyVal__wrretryack_buf__v6;
        SData/*14:0*/ __VdlyVal__wrretryack_buf__v7;
        SData/*14:0*/ __VdlyVal__wrretryack_buf__v8;
        SData/*14:0*/ __VdlyVal__wrretryack_buf__v9;
        SData/*14:0*/ __VdlyVal__wrretryack_buf__v10;
        SData/*14:0*/ __VdlyVal__wrretryack_buf__v11;
        SData/*14:0*/ __VdlyVal__wrretryack_buf__v12;
        SData/*14:0*/ __VdlyVal__wrretryack_buf__v13;
        SData/*14:0*/ __VdlyVal__wrretryack_buf__v14;
        SData/*14:0*/ __VdlyVal__wrretryack_buf__v15;
        VL_INW(__PVT__cc_reqflit,150,0,5);
        VL_INW(__PVT__slc_wrdata,511,0,16);
        VL_OUTW(__PVT__slc_rspflit,72,0,3);
        VL_OUTW(__PVT__compdata_tocc,511,0,16);
        VL_OUTW(__PVT__ic_TX_REQFLIT,150,0,5);
        VL_INW(__PVT__ic_RX_DATFLIT,679,0,22);
        VL_INW(__PVT__ic_RX_RSPFLIT,72,0,3);
        VL_OUTW(__PVT__ic_TX_DATFLIT,679,0,22);
        VL_IN(__PVT__cm_homeaddr_base_all_pm,27,0);
        VL_IN(__PVT__cm_homeaddr_limit_all_pm,28,0);
        VlWide<5>/*153:0*/ __PVT__wrdata_reqflit_fifo;
        VlWide<5>/*153:0*/ __PVT__rddata_reqflit_fifo;
        VlWide<5>/*153:0*/ __PVT__outstanding_rd_reqf;
        VlWide<16>/*511:0*/ __PVT__wr_data_tx_datf;
        IData/*31:0*/ __PVT__rd_txnid_buffer_seq__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ __PVT__wr_addr_buffer_seq__DOT__unnamedblk4__DOT__i;
        IData/*31:0*/ __PVT__rd_reqf_buffer_seq__DOT__unnamedblk5__DOT__i;
        IData/*31:0*/ __PVT__wr_data_buffer_seq__DOT__unnamedblk6__DOT__i;
        IData/*31:0*/ __PVT__wr_dbid_buffer_seq__DOT__unnamedblk7__DOT__i;
        IData/*31:0*/ __PVT__unnamedblk8__DOT__i;
        IData/*31:0*/ __PVT__unnamedblk9__DOT__rd_i;
        IData/*31:0*/ __PVT__unnamedblk9__DOT__wr_i;
        IData/*31:0*/ __PVT__unnamedblk10__DOT__rd_i;
    };
    struct {
        IData/*31:0*/ __PVT__unnamedblk10__DOT__wr_i;
        IData/*31:0*/ __PVT__unnamedblk11__DOT__i;
        IData/*31:0*/ __PVT__unnamedblk12__DOT__i;
        IData/*31:0*/ __PVT__tgt_map_cmb__DOT__unnamedblk13__DOT__p;
        IData/*31:0*/ __Vfunc_clog2_txnid__0__unnamedblk1__DOT__i;
        IData/*31:0*/ __Vfunc_clog2_txnid__0__clog2_txnid_temp_mul;
        IData/*31:0*/ __Vfunc_clog2_addr__1__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_clog2_addr__1__clog2_addr_temp_mul;
        IData/*31:0*/ __Vfunc_clog2_addr__2__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_clog2_addr__2__clog2_addr_temp_mul;
        IData/*31:0*/ __Vfunc_clog2_addr__3__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_clog2_addr__3__clog2_addr_temp_mul;
        IData/*31:0*/ __Vfunc_clog2_addr__4__unnamedblk3__DOT__i;
        IData/*31:0*/ __Vfunc_clog2_addr__4__clog2_addr_temp_mul;
        IData/*31:0*/ __Vfunc_clog2_txnid__5__unnamedblk1__DOT__i;
        IData/*31:0*/ __Vfunc_clog2_txnid__5__clog2_txnid_temp_mul;
        VlWide<5>/*153:0*/ __VdlyVal__rd_reqf_buffer__v0;
        VlWide<5>/*153:0*/ __VdlyVal__rd_reqf_buffer__v1;
        VlWide<5>/*153:0*/ __VdlyVal__rd_reqf_buffer__v2;
        VlWide<5>/*153:0*/ __VdlyVal__rd_reqf_buffer__v3;
        VlWide<5>/*153:0*/ __VdlyVal__rd_reqf_buffer__v4;
        VlWide<5>/*153:0*/ __VdlyVal__rd_reqf_buffer__v5;
        VlWide<5>/*153:0*/ __VdlyVal__rd_reqf_buffer__v6;
        VlWide<5>/*153:0*/ __VdlyVal__rd_reqf_buffer__v7;
        VlWide<5>/*153:0*/ __VdlyVal__rd_reqf_buffer__v8;
        VlWide<5>/*153:0*/ __VdlyVal__rd_reqf_buffer__v9;
        VlWide<5>/*153:0*/ __VdlyVal__rd_reqf_buffer__v10;
        VlWide<5>/*153:0*/ __VdlyVal__rd_reqf_buffer__v11;
        VlWide<5>/*153:0*/ __VdlyVal__rd_reqf_buffer__v12;
        VlWide<5>/*153:0*/ __VdlyVal__rd_reqf_buffer__v13;
        VlWide<5>/*153:0*/ __VdlyVal__rd_reqf_buffer__v14;
        VlWide<5>/*153:0*/ __VdlyVal__rd_reqf_buffer__v15;
        VlWide<16>/*511:0*/ __VdlyVal__wr_data_buffer__v0;
        VlWide<16>/*511:0*/ __VdlyVal__wr_data_buffer__v1;
        VlWide<16>/*511:0*/ __VdlyVal__wr_data_buffer__v2;
        VlWide<16>/*511:0*/ __VdlyVal__wr_data_buffer__v3;
        VlWide<16>/*511:0*/ __VdlyVal__wr_data_buffer__v4;
        VlWide<16>/*511:0*/ __VdlyVal__wr_data_buffer__v5;
        VlWide<16>/*511:0*/ __VdlyVal__wr_data_buffer__v6;
        VlWide<16>/*511:0*/ __VdlyVal__wr_data_buffer__v7;
        VlWide<16>/*511:0*/ __VdlyVal__wr_data_buffer__v8;
        VlWide<16>/*511:0*/ __VdlyVal__wr_data_buffer__v9;
        VlWide<16>/*511:0*/ __VdlyVal__wr_data_buffer__v10;
        VlWide<16>/*511:0*/ __VdlyVal__wr_data_buffer__v11;
        VlWide<16>/*511:0*/ __VdlyVal__wr_data_buffer__v12;
        VlWide<16>/*511:0*/ __VdlyVal__wr_data_buffer__v13;
        VlWide<16>/*511:0*/ __VdlyVal__wr_data_buffer__v14;
        VlWide<16>/*511:0*/ __VdlyVal__wr_data_buffer__v15;
        VL_IN64(__PVT__slc_be,63,0);
        VlWide<5>/*150:0*/ __PVT__rddata_reqflit_fifo_s;
        VlWide<5>/*150:0*/ __PVT__outstanding_rd_reqf_s;
        VlWide<5>/*150:0*/ __PVT__rd_reqf_s;
        VlWide<5>/*150:0*/ __PVT__memrd_req_s;
        VlWide<5>/*150:0*/ __PVT__memwr_req_s;
        QData/*51:0*/ __PVT__wr_mem_addr;
        QData/*63:0*/ __PVT__wr_be_tx_datf;
        QData/*51:0*/ __PVT__wr_addr_for_tx_datf;
        QData/*51:0*/ __PVT__mem_addr_wrrd;
        VlWide<3>/*72:0*/ __PVT__slc_rspflit_s;
        VlWide<3>/*72:0*/ __PVT__ic_RX_RSPFLIT_s;
        VlWide<22>/*679:0*/ __PVT__ic_RX_DATFLIT_s;
        VlWide<22>/*679:0*/ __PVT__ic_TX_DATFLIT_s;
        VlWide<5>/*150:0*/ __PVT__memrdretry_cmd_s;
        QData/*32:0*/ __Vfunc_clog2_txnid__0__clog2_txnid_temp_add;
    };
    struct {
        QData/*32:0*/ __Vfunc_clog2_addr__1__clog2_addr_temp_add;
        QData/*32:0*/ __Vfunc_clog2_addr__2__clog2_addr_temp_add;
        QData/*32:0*/ __Vfunc_clog2_addr__3__clog2_addr_temp_add;
        QData/*32:0*/ __Vfunc_clog2_addr__4__clog2_addr_temp_add;
        QData/*32:0*/ __Vfunc_clog2_txnid__5__clog2_txnid_temp_add;
        QData/*51:0*/ __VdlyVal__wr_addr_buffer__v0;
        QData/*51:0*/ __VdlyVal__wr_addr_buffer__v1;
        QData/*51:0*/ __VdlyVal__wr_addr_buffer__v2;
        QData/*51:0*/ __VdlyVal__wr_addr_buffer__v3;
        QData/*51:0*/ __VdlyVal__wr_addr_buffer__v4;
        QData/*51:0*/ __VdlyVal__wr_addr_buffer__v5;
        QData/*51:0*/ __VdlyVal__wr_addr_buffer__v6;
        QData/*51:0*/ __VdlyVal__wr_addr_buffer__v7;
        QData/*51:0*/ __VdlyVal__wr_addr_buffer__v8;
        QData/*51:0*/ __VdlyVal__wr_addr_buffer__v9;
        QData/*51:0*/ __VdlyVal__wr_addr_buffer__v10;
        QData/*51:0*/ __VdlyVal__wr_addr_buffer__v11;
        QData/*51:0*/ __VdlyVal__wr_addr_buffer__v12;
        QData/*51:0*/ __VdlyVal__wr_addr_buffer__v13;
        QData/*51:0*/ __VdlyVal__wr_addr_buffer__v14;
        QData/*51:0*/ __VdlyVal__wr_addr_buffer__v15;
        QData/*63:0*/ __VdlyVal__wr_be_buffer__v0;
        QData/*63:0*/ __VdlyVal__wr_be_buffer__v1;
        QData/*63:0*/ __VdlyVal__wr_be_buffer__v2;
        QData/*63:0*/ __VdlyVal__wr_be_buffer__v3;
        QData/*63:0*/ __VdlyVal__wr_be_buffer__v4;
        QData/*63:0*/ __VdlyVal__wr_be_buffer__v5;
        QData/*63:0*/ __VdlyVal__wr_be_buffer__v6;
        QData/*63:0*/ __VdlyVal__wr_be_buffer__v7;
        QData/*63:0*/ __VdlyVal__wr_be_buffer__v8;
        QData/*63:0*/ __VdlyVal__wr_be_buffer__v9;
        QData/*63:0*/ __VdlyVal__wr_be_buffer__v10;
        QData/*63:0*/ __VdlyVal__wr_be_buffer__v11;
        QData/*63:0*/ __VdlyVal__wr_be_buffer__v12;
        QData/*63:0*/ __VdlyVal__wr_be_buffer__v13;
        QData/*63:0*/ __VdlyVal__wr_be_buffer__v14;
        QData/*63:0*/ __VdlyVal__wr_be_buffer__v15;
        VlWide<5>/*150:0*/ __VdlyVal__memrdretry_buf__v0;
        VlWide<5>/*150:0*/ __VdlyVal__memrdretry_buf__v1;
        VlWide<5>/*150:0*/ __VdlyVal__memrdretry_buf__v2;
        VlWide<5>/*150:0*/ __VdlyVal__memrdretry_buf__v3;
        VlWide<5>/*150:0*/ __VdlyVal__memrdretry_buf__v4;
        VlWide<5>/*150:0*/ __VdlyVal__memrdretry_buf__v5;
        VlWide<5>/*150:0*/ __VdlyVal__memrdretry_buf__v6;
        VlWide<5>/*150:0*/ __VdlyVal__memrdretry_buf__v7;
        VlWide<5>/*150:0*/ __VdlyVal__memrdretry_buf__v8;
        VlWide<5>/*150:0*/ __VdlyVal__memrdretry_buf__v9;
        VlWide<5>/*150:0*/ __VdlyVal__memrdretry_buf__v10;
        VlWide<5>/*150:0*/ __VdlyVal__memrdretry_buf__v11;
        VlWide<5>/*150:0*/ __VdlyVal__memrdretry_buf__v12;
        VlWide<5>/*150:0*/ __VdlyVal__memrdretry_buf__v13;
        VlWide<5>/*150:0*/ __VdlyVal__memrdretry_buf__v14;
        VlWide<5>/*150:0*/ __VdlyVal__memrdretry_buf__v15;
        VlUnpacked<SData/*11:0*/, 16> __PVT__rd_txnid_buffer;
        VlUnpacked<SData/*11:0*/, 16> __PVT__rd_txnid_buffer_nxt;
        VlUnpacked<QData/*51:0*/, 16> __PVT__wr_addr_buffer;
        VlUnpacked<QData/*51:0*/, 16> __PVT__wr_addr_buffer_nxt;
        VlUnpacked<CData/*3:0*/, 16> __PVT__wr_qos_buffer;
        VlUnpacked<CData/*3:0*/, 16> __PVT__wr_qos_buffer_nxt;
        VlUnpacked<SData/*11:0*/, 16> __PVT__wr_txnid_buffer;
        VlUnpacked<SData/*11:0*/, 16> __PVT__wr_txnid_buffer_nxt;
        VlUnpacked<SData/*10:0*/, 16> __PVT__wr_tgtid_buffer;
        VlUnpacked<SData/*10:0*/, 16> __PVT__wr_tgtid_buffer_nxt;
        VlUnpacked<CData/*0:0*/, 16> __PVT__wr_ns_buffer;
    };
    struct {
        VlUnpacked<CData/*0:0*/, 16> __PVT__wr_ns_buffer_nxt;
        VlUnpacked<CData/*3:0*/, 16> __PVT__wr_memattr_buffer;
        VlUnpacked<CData/*3:0*/, 16> __PVT__wr_memattr_buffer_nxt;
        VlUnpacked<VlWide<5>/*153:0*/, 16> __PVT__rd_reqf_buffer;
        VlUnpacked<VlWide<5>/*153:0*/, 16> __PVT__rd_reqf_buffer_nxt;
        VlUnpacked<CData/*3:0*/, 16> __PVT__wr_data_index_buffer;
        VlUnpacked<CData/*3:0*/, 16> __PVT__wr_data_index_buffer_nxt;
        VlUnpacked<VlWide<16>/*511:0*/, 16> __PVT__wr_data_buffer;
        VlUnpacked<VlWide<16>/*511:0*/, 16> __PVT__wr_data_buffer_nxt;
        VlUnpacked<QData/*63:0*/, 16> __PVT__wr_be_buffer;
        VlUnpacked<QData/*63:0*/, 16> __PVT__wr_be_buffer_nxt;
        VlUnpacked<CData/*3:0*/, 16> __PVT__wr_dbid_index_buffer;
        VlUnpacked<CData/*3:0*/, 16> __PVT__wr_dbid_index_buffer_nxt;
        VlUnpacked<SData/*11:0*/, 16> __PVT__wr_dbid_buffer;
        VlUnpacked<SData/*11:0*/, 16> __PVT__wr_dbid_buffer_nxt;
        VlUnpacked<SData/*10:0*/, 1> __PVT__xy_coord_pm;
        VlUnpacked<IData/*27:0*/, 1> __PVT__cm_homeaddr_base_pm;
        VlUnpacked<IData/*28:0*/, 1> __PVT__cm_homeaddr_limit_pm;
        VlUnpacked<IData/*27:0*/, 1> __PVT__cm_flit_addr_sliced_pm;
        VlUnpacked<IData/*27:0*/, 1> __PVT__cm_homeaddr_base_sliced_pm;
        VlUnpacked<IData/*28:0*/, 1> __PVT__cm_homeaddr_limit_sliced_pm;
        VlUnpacked<VlWide<5>/*150:0*/, 16> __PVT__memrdretry_buf;
        VlUnpacked<VlWide<5>/*150:0*/, 16> __PVT__memrdretry_buf_nxt;
        VlUnpacked<SData/*14:0*/, 16> __PVT__rdretryack_buf_nxt;
        VlUnpacked<SData/*14:0*/, 16> __PVT__rdretryack_buf;
        VlUnpacked<SData/*14:0*/, 16> __PVT__wrretryack_buf_nxt;
        VlUnpacked<SData/*14:0*/, 16> __PVT__wrretryack_buf;
    };

    // INTERNAL VARIABLES
    Vsig_topology_top__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vsig_topology_top_sig_slc_bypass__pi20(Vsig_topology_top__Syms* symsp, const char* v__name);
    ~Vsig_topology_top_sig_slc_bypass__pi20();
    VL_UNCOPYABLE(Vsig_topology_top_sig_slc_bypass__pi20);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
