// Verilated -*- SystemC -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vsig_topology_top.h for the primary calling header

#include "Vsig_topology_top__pch.h"
#include "Vsig_topology_top__Syms.h"
#include "Vsig_topology_top___024root.h"

void Vsig_topology_top___024root___ctor_var_reset(Vsig_topology_top___024root* vlSelf);

Vsig_topology_top___024root::Vsig_topology_top___024root(Vsig_topology_top__Syms* symsp, const char* v__name)
    : VerilatedModule{v__name}
    , cl0_ic_clk("cl0_ic_clk")
    , cl0_rstb_ic_clk("cl0_rstb_ic_clk")
    , cl0_cc_intfrx_clk("cl0_cc_intfrx_clk")
    , cl0_cc_rstb_intfrx_clk("cl0_cc_rstb_intfrx_clk")
    , cl0_p1_intfrx_clk("cl0_p1_intfrx_clk")
    , cl0_p1_rstb_intfrx_clk("cl0_p1_rstb_intfrx_clk")
    , cl0_p1_TX_LINKACTIVEREQ("cl0_p1_TX_LINKACTIVEREQ")
    , cl0_p1_TX_LINKACTIVEACK("cl0_p1_TX_LINKACTIVEACK")
    , cl0_p1_RX_REQFLITPEND("cl0_p1_RX_REQFLITPEND")
    , cl0_p1_RX_REQFLITV("cl0_p1_RX_REQFLITV")
    , cl0_p1_RX_REQLCRDV("cl0_p1_RX_REQLCRDV")
    , cl0_p1_RX_RSPFLITPEND("cl0_p1_RX_RSPFLITPEND")
    , cl0_p1_RX_RSPFLITV("cl0_p1_RX_RSPFLITV")
    , cl0_p1_RX_RSPLCRDV("cl0_p1_RX_RSPLCRDV")
    , cl0_p1_RX_DATFLITPEND("cl0_p1_RX_DATFLITPEND")
    , cl0_p1_RX_DATFLITV("cl0_p1_RX_DATFLITV")
    , cl0_p1_RX_DATLCRDV("cl0_p1_RX_DATLCRDV")
    , cl0_p1_RX_LINKACTIVEREQ("cl0_p1_RX_LINKACTIVEREQ")
    , cl0_p1_RX_LINKACTIVEACK("cl0_p1_RX_LINKACTIVEACK")
    , cl0_p1_TX_SNPFLITPEND("cl0_p1_TX_SNPFLITPEND")
    , cl0_p1_TX_SNPFLITV("cl0_p1_TX_SNPFLITV")
    , cl0_p1_TX_SNPLCRDV("cl0_p1_TX_SNPLCRDV")
    , cl0_p1_TX_RSPFLITPEND("cl0_p1_TX_RSPFLITPEND")
    , cl0_p1_TX_RSPFLITV("cl0_p1_TX_RSPFLITV")
    , cl0_p1_TX_RSPLCRDV("cl0_p1_TX_RSPLCRDV")
    , cl0_p1_TX_DATFLITPEND("cl0_p1_TX_DATFLITPEND")
    , cl0_p1_TX_DATFLITV("cl0_p1_TX_DATFLITV")
    , cl0_p1_TX_DATLCRDV("cl0_p1_TX_DATLCRDV")
    , cl0_p1_TXSACTIVE("cl0_p1_TXSACTIVE")
    , cl0_p1_RXSACTIVE("cl0_p1_RXSACTIVE")
    , cl0_p1_SYSCOREQ("cl0_p1_SYSCOREQ")
    , cl0_p1_SYSCOACK("cl0_p1_SYSCOACK")
    , cl0_p0_intfrx_clk("cl0_p0_intfrx_clk")
    , cl0_p0_rstb_intfrx_clk("cl0_p0_rstb_intfrx_clk")
    , cl0_p0_TX_LINKACTIVEREQ("cl0_p0_TX_LINKACTIVEREQ")
    , cl0_p0_TX_LINKACTIVEACK("cl0_p0_TX_LINKACTIVEACK")
    , cl0_p0_RX_REQFLITPEND("cl0_p0_RX_REQFLITPEND")
    , cl0_p0_RX_REQFLITV("cl0_p0_RX_REQFLITV")
    , cl0_p0_RX_REQLCRDV("cl0_p0_RX_REQLCRDV")
    , cl0_p0_RX_RSPFLITPEND("cl0_p0_RX_RSPFLITPEND")
    , cl0_p0_RX_RSPFLITV("cl0_p0_RX_RSPFLITV")
    , cl0_p0_RX_RSPLCRDV("cl0_p0_RX_RSPLCRDV")
    , cl0_p0_RX_DATFLITPEND("cl0_p0_RX_DATFLITPEND")
    , cl0_p0_RX_DATFLITV("cl0_p0_RX_DATFLITV")
    , cl0_p0_RX_DATLCRDV("cl0_p0_RX_DATLCRDV")
    , cl0_p0_RX_LINKACTIVEREQ("cl0_p0_RX_LINKACTIVEREQ")
    , cl0_p0_RX_LINKACTIVEACK("cl0_p0_RX_LINKACTIVEACK")
    , cl0_p0_TX_SNPFLITPEND("cl0_p0_TX_SNPFLITPEND")
    , cl0_p0_TX_SNPFLITV("cl0_p0_TX_SNPFLITV")
    , cl0_p0_TX_SNPLCRDV("cl0_p0_TX_SNPLCRDV")
    , cl0_p0_TX_RSPFLITPEND("cl0_p0_TX_RSPFLITPEND")
    , cl0_p0_TX_RSPFLITV("cl0_p0_TX_RSPFLITV")
    , cl0_p0_TX_RSPLCRDV("cl0_p0_TX_RSPLCRDV")
    , cl0_p0_TX_DATFLITPEND("cl0_p0_TX_DATFLITPEND")
    , cl0_p0_TX_DATFLITV("cl0_p0_TX_DATFLITV")
    , cl0_p0_TX_DATLCRDV("cl0_p0_TX_DATLCRDV")
    , cl0_p0_TXSACTIVE("cl0_p0_TXSACTIVE")
    , cl0_p0_RXSACTIVE("cl0_p0_RXSACTIVE")
    , cl0_p0_SYSCOREQ("cl0_p0_SYSCOREQ")
    , cl0_p0_SYSCOACK("cl0_p0_SYSCOACK")
    , cl0_p3_intfrx_clk("cl0_p3_intfrx_clk")
    , cl0_p3_rstb_intfrx_clk("cl0_p3_rstb_intfrx_clk")
    , cl0_p3_RX_LINKACTIVEREQ("cl0_p3_RX_LINKACTIVEREQ")
    , cl0_p3_RX_LINKACTIVEACK("cl0_p3_RX_LINKACTIVEACK")
    , cl0_p3_RX_RSPFLITPEND("cl0_p3_RX_RSPFLITPEND")
    , cl0_p3_RX_RSPFLITV("cl0_p3_RX_RSPFLITV")
    , cl0_p3_RX_RSPLCRDV("cl0_p3_RX_RSPLCRDV")
    , cl0_p3_RX_DATFLITPEND("cl0_p3_RX_DATFLITPEND")
    , cl0_p3_RX_DATFLITV("cl0_p3_RX_DATFLITV")
    , cl0_p3_RX_DATLCRDV("cl0_p3_RX_DATLCRDV")
    , cl0_p3_TX_LINKACTIVEREQ("cl0_p3_TX_LINKACTIVEREQ")
    , cl0_p3_TX_LINKACTIVEACK("cl0_p3_TX_LINKACTIVEACK")
    , cl0_p3_TX_REQFLITPEND("cl0_p3_TX_REQFLITPEND")
    , cl0_p3_TX_REQFLITV("cl0_p3_TX_REQFLITV")
    , cl0_p3_TX_REQLCRDV("cl0_p3_TX_REQLCRDV")
    , cl0_p3_TX_DATFLITPEND("cl0_p3_TX_DATFLITPEND")
    , cl0_p3_TX_DATFLITV("cl0_p3_TX_DATFLITV")
    , cl0_p3_TX_DATLCRDV("cl0_p3_TX_DATLCRDV")
    , cl0_p3_TXSACTIVE("cl0_p3_TXSACTIVE")
    , cl0_p3_RXSACTIVE("cl0_p3_RXSACTIVE")
    , PCLK_prog("PCLK_prog")
    , PRESETn_prog("PRESETn_prog")
    , PSEL_prog("PSEL_prog")
    , PENABLE_prog("PENABLE_prog")
    , PWRITE_prog("PWRITE_prog")
    , PSTRB_prog("PSTRB_prog")
    , PREADY_prog("PREADY_prog")
    , PSLVERR_prog("PSLVERR_prog")
    , qp_clk("qp_clk")
    , qp_rstb("qp_rstb")
    , qreqn("qreqn")
    , qacceptn("qacceptn")
    , qdeny("qdeny")
    , qactive("qactive")
    , qin_quiescence("qin_quiescence")
    , pstate("pstate")
    , preq("preq")
    , paccept("paccept")
    , pdeny("pdeny")
    , pactive("pactive")
    , PADDR_prog("PADDR_prog")
    , PWDATA_prog("PWDATA_prog")
    , PRDATA_prog("PRDATA_prog")
    , cl0_p1_RX_REQFLIT("cl0_p1_RX_REQFLIT")
    , cl0_p1_RX_RSPFLIT("cl0_p1_RX_RSPFLIT")
    , cl0_p1_RX_DATFLIT("cl0_p1_RX_DATFLIT")
    , cl0_p1_TX_SNPFLIT("cl0_p1_TX_SNPFLIT")
    , cl0_p1_TX_RSPFLIT("cl0_p1_TX_RSPFLIT")
    , cl0_p1_TX_DATFLIT("cl0_p1_TX_DATFLIT")
    , cl0_p0_RX_REQFLIT("cl0_p0_RX_REQFLIT")
    , cl0_p0_RX_RSPFLIT("cl0_p0_RX_RSPFLIT")
    , cl0_p0_RX_DATFLIT("cl0_p0_RX_DATFLIT")
    , cl0_p0_TX_SNPFLIT("cl0_p0_TX_SNPFLIT")
    , cl0_p0_TX_RSPFLIT("cl0_p0_TX_RSPFLIT")
    , cl0_p0_TX_DATFLIT("cl0_p0_TX_DATFLIT")
    , cl0_p3_RX_RSPFLIT("cl0_p3_RX_RSPFLIT")
    , cl0_p3_RX_DATFLIT("cl0_p3_RX_DATFLIT")
    , cl0_p3_TX_REQFLIT("cl0_p3_TX_REQFLIT")
    , cl0_p3_TX_DATFLIT("cl0_p3_TX_DATFLIT")
    , vlSymsp{symsp}
 {
    // Reset structure values
    Vsig_topology_top___024root___ctor_var_reset(this);
}

void Vsig_topology_top___024root::__Vconfigure(bool first) {
    (void)first;  // Prevent unused variable warning
}

Vsig_topology_top___024root::~Vsig_topology_top___024root() {
}
