// Verilated -*- SystemC -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vsig_topology_top.h for the primary calling header

#ifndef VERILATED_VSIG_TOPOLOGY_TOP_SIG_COHERENCY_TOP__PI5_H_
#define VERILATED_VSIG_TOPOLOGY_TOP_SIG_COHERENCY_TOP__PI5_H_  // guard

#include "systemc"
#include "verilated_sc.h"
#include "verilated.h"
class Vsig_topology_top_sig_cachedir_ctrlr__pi15;
class Vsig_topology_top_sig_chi_initcrdt_enable;
class Vsig_topology_top_sig_chi_proc_atomic_top;
class Vsig_topology_top_sig_chi_rcv_datproc__pi13;
class Vsig_topology_top_sig_chi_rcv_reqproc__pi12;
class Vsig_topology_top_sig_chi_rcv_respproc;
class Vsig_topology_top_sig_chi_xmt_compdata__pi19;
class Vsig_topology_top_sig_chi_xmt_data_flit__C2a8;
class Vsig_topology_top_sig_chi_xmt_resp;
class Vsig_topology_top_sig_chi_xmt_snpreq__pi17;
class Vsig_topology_top_sig_chi_xmt_snpreq_flit__C98;
class Vsig_topology_top_sig_cnoc_atomic_processor_data_in_interface;
class Vsig_topology_top_sig_cnoc_atomic_processor_data_out_interface;
class Vsig_topology_top_sig_cnoc_atomic_processor_meta_in_interface;
class Vsig_topology_top_sig_coherency_ctrlr__pi14;
class Vsig_topology_top_sig_compbuff_top__D0;
class Vsig_topology_top_sig_fifo_synchclk_flop__pi16;
class Vsig_topology_top_sig_fifo_synchclk_flop__pi18;
class Vsig_topology_top_sig_linearize_nodeid;
class Vsig_topology_top_sig_nway_cache__Ca_CB24;
class Vsig_topology_top_sig_system_monitor__A2e;


class Vsig_topology_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vsig_topology_top_sig_coherency_top__pi5 final : public VerilatedModule {
  public:
    // CELLS
    Vsig_topology_top_sig_cnoc_atomic_processor_meta_in_interface* __PVT__meta_to_ap;
    Vsig_topology_top_sig_cnoc_atomic_processor_data_in_interface* __PVT__data_to_ap;
    Vsig_topology_top_sig_cnoc_atomic_processor_data_out_interface* __PVT__data_from_ap;
    Vsig_topology_top_sig_linearize_nodeid* __PVT__u_linearize_nodeid;
    Vsig_topology_top_sig_chi_rcv_reqproc__pi12* __PVT__sig_chi_rcv_reqproc_0;
    Vsig_topology_top_sig_chi_rcv_datproc__pi13* __PVT__sig_chi_rcv_datproc_0;
    Vsig_topology_top_sig_chi_rcv_respproc* __PVT__sig_chi_rcv_respproc_0;
    Vsig_topology_top_sig_compbuff_top__D0* __PVT__sig_compbuff_top_0;
    Vsig_topology_top_sig_coherency_ctrlr__pi14* __PVT__sig_coherency_ctrlr_0;
    Vsig_topology_top_sig_system_monitor__A2e* __PVT__sig_system_monitor_0;
    Vsig_topology_top_sig_nway_cache__Ca_CB24* __PVT__dir_nway_cache;
    Vsig_topology_top_sig_cachedir_ctrlr__pi15* __PVT__sig_cachedir_ctrlr_0;
    Vsig_topology_top_sig_fifo_synchclk_flop__pi16* __PVT__snpreq_fifo_0;
    Vsig_topology_top_sig_chi_xmt_snpreq__pi17* __PVT__sig_chi_xmt_snpreq_0;
    Vsig_topology_top_sig_chi_xmt_snpreq_flit__C98* __PVT__sig_chi_xmt_snpreq_flit_0;
    Vsig_topology_top_sig_fifo_synchclk_flop__pi18* __PVT__outcomp_fifo_0;
    Vsig_topology_top_sig_chi_xmt_compdata__pi19* __PVT__sig_chi_xmt_compdata_0;
    Vsig_topology_top_sig_chi_xmt_data_flit__C2a8* __PVT__sig_chi_xmt_data_flit_0;
    Vsig_topology_top_sig_chi_xmt_resp* __PVT__sig_chi_xmt_resp_0;
    Vsig_topology_top_sig_chi_proc_atomic_top* __PVT__sig_chi_proc_atomic_0;
    Vsig_topology_top_sig_chi_initcrdt_enable* __PVT__sig_chi_initcrdt_enable_0;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(__PVT__cc_clk,0,0);
        VL_IN8(__PVT__cc_gclk,0,0);
        VL_IN8(__PVT__rstb_cc_clk,0,0);
        VL_OUT8(__PVT__cc_is_inactive,0,0);
        VL_IN8(__PVT__ic_RX_REQFLITPEND,0,0);
        VL_IN8(__PVT__ic_RX_REQFLITV,0,0);
        VL_OUT8(__PVT__ic_RX_REQLCRDV,0,0);
        VL_OUT8(__PVT__ic_TX_RSPFLITPEND,0,0);
        VL_OUT8(__PVT__ic_TX_RSPFLITV,0,0);
        VL_IN8(__PVT__ic_TX_RSPLCRDV,0,0);
        VL_IN8(__PVT__ic_RX_RSPFLITPEND,0,0);
        VL_IN8(__PVT__ic_RX_RSPFLITV,0,0);
        VL_OUT8(__PVT__ic_RX_RSPLCRDV,0,0);
        VL_OUT8(__PVT__ic_TX_SNPFLITPEND,0,0);
        VL_OUT8(__PVT__ic_TX_SNPFLITV,0,0);
        VL_IN8(__PVT__ic_TX_SNPLCRDV,0,0);
        VL_IN8(__PVT__ic_RX_DATFLITPEND,0,0);
        VL_IN8(__PVT__ic_RX_DATFLITV,0,0);
        VL_OUT8(__PVT__ic_RX_DATLCRDV,0,0);
        VL_IN8(__PVT__l3_datvalid,0,0);
        VL_IN8(__PVT__l3_rddata_resperr,1,0);
        VL_OUT8(__PVT__porthas_datgnt_fromcc,0,0);
        VL_OUT8(__PVT__ic_TX_DATFLITPEND,0,0);
        VL_OUT8(__PVT__ic_TX_DATFLITV,0,0);
        VL_IN8(__PVT__ic_TX_DATLCRDV,0,0);
        VL_IN8(__PVT__mycluster_id,7,0);
        VL_IN8(__PVT__dmt_enable_all_pm_vec,0,0);
        VL_OUT8(__PVT__cc_reqflit_valid,0,0);
        VL_IN8(__PVT__l3reqflit_fifo_full,0,0);
        VL_IN8(__PVT__l3_rspvalid,0,0);
        VL_OUT8(__PVT__porthas_rspgnt_fromcc,0,0);
        VL_OUT8(__PVT__l3_wrdata_valid,0,0);
        VL_OUT8(__PVT__l3_drop_wrdata,0,0);
        VL_IN8(__PVT__l3_wrdatabuf_hasroom,0,0);
        VL_OUT8(__PVT__dirc_init_complete,0,0);
        VL_IN8(__PVT__use_early_write_response,0,0);
        CData/*0:0*/ __PVT__cmd_addr_ph3_has_matchingentry_incmq;
        CData/*0:0*/ __PVT__wren_cmq_ph4;
        CData/*0:0*/ __PVT__block_fetch_cohc;
        CData/*0:0*/ __PVT__cm_cmdvalid;
        CData/*0:0*/ __PVT__clr_cm_cmdvalid;
        CData/*0:0*/ __PVT__cm_cmdvalid_evict;
        CData/*0:0*/ __PVT__clr_cm_cmdvalid_evict;
        CData/*0:0*/ __PVT__cachehit;
        CData/*0:0*/ __PVT__rden_dircache_cohc;
        CData/*0:0*/ __PVT__rden_dircache_cohc_pre;
        CData/*0:0*/ __PVT__rden_dircache_dirc;
        CData/*0:0*/ __PVT__rden_dircache_dirc_pre;
        CData/*0:0*/ __PVT__evict_this_cycle;
        CData/*0:0*/ __PVT__wrvalid_dirc;
        CData/*0:0*/ __PVT__wren_cache_cohc_or_dirc;
        CData/*0:0*/ __PVT__excl_load_reqv;
        CData/*4:0*/ __PVT__excl_load_lpid;
        CData/*2:0*/ __PVT__excl_load_size;
        CData/*0:0*/ __PVT__buffer_full;
        CData/*1:0*/ __PVT__excl_store_reqv;
        CData/*4:0*/ __PVT__excl_store_lpid;
        CData/*2:0*/ __PVT__excl_store_size;
        CData/*0:0*/ __PVT__excl_store_pass;
        CData/*0:0*/ __PVT__atom_req_update;
        CData/*0:0*/ __PVT__inpendingq_matches_collnq_cohc;
        CData/*3:0*/ __PVT__rden_which16bytes_1st;
        CData/*3:0*/ __PVT__rden_which16bytes_2nd;
        CData/*0:0*/ __PVT__compbuf_available_compbuftop;
    };
    struct {
        CData/*4:0*/ __PVT__buffernum_available;
        CData/*0:0*/ __PVT__allocate_compbuf_snpreq;
        CData/*1:0*/ __PVT__rresp_compbuf;
        CData/*0:0*/ __PVT__wren_reqcmdq;
        CData/*0:0*/ __PVT__send_reqcrdt_update;
        CData/*0:0*/ __PVT__rcv_datproc_wr_to_compbuff;
        CData/*3:0*/ __PVT__wren_which128_compbuff_rcv_dat;
        CData/*3:0*/ __PVT__wren_which128_compbuff_xmt_dat;
        CData/*3:0*/ __PVT__wren_which128_compbuff;
        CData/*0:0*/ __PVT__enable_init_update;
        CData/*0:0*/ __PVT__send_respcrdt_update_cohc;
        CData/*0:0*/ __PVT__wren_respcmdq;
        CData/*0:0*/ __PVT__wren_drespcmdq;
        CData/*0:0*/ __PVT__wren_memrespcmdq;
        CData/*0:0*/ __PVT__wren_snpreqfifo;
        CData/*0:0*/ __PVT__empty_snpreqfifo;
        CData/*0:0*/ __PVT__room_atlst3_snpreqfifo;
        CData/*0:0*/ __PVT__rden_snpreqfifo;
        CData/*0:0*/ __PVT__full_snpreqfifo;
        CData/*0:0*/ __PVT__wren_outcompfifo;
        CData/*0:0*/ __PVT__empty_outcompfifo;
        CData/*0:0*/ __PVT__rden_outcompfifo;
        CData/*0:0*/ __PVT__full_outcompfifo;
        CData/*0:0*/ __PVT__room_atlst3_outcompfifo;
        CData/*0:0*/ __PVT__dirc_canwrite_tocache;
        CData/*0:0*/ __PVT__req_resp_snpreq;
        CData/*0:0*/ __PVT__req_resp_compdata;
        CData/*0:0*/ __PVT__req_retry_ack;
        CData/*0:0*/ __PVT__req_pcrd_grant;
        CData/*0:0*/ __PVT__req_readreceipt;
        CData/*0:0*/ __PVT__clr_2nd_buffer;
        CData/*4:0*/ __PVT__grant_resp;
        CData/*0:0*/ __PVT__allocate_respbuf_snpreq;
        CData/*0:0*/ __PVT__allocate_respbuf_compdata;
        CData/*5:0*/ __PVT__respbuff_avail;
        CData/*0:0*/ __PVT__clr_collnreg_sending_ini_compdata;
        CData/*5:0*/ __PVT__index_pendingq_clr_outstand_cmd_compdata;
        CData/*5:0*/ __PVT__index_pendingq_clr_outstand_cmd_snpreq;
        CData/*0:0*/ __PVT__avoid_clr_colln_snpreq;
        CData/*0:0*/ __PVT__fiforoom_atlst4_cmq;
        CData/*0:0*/ __PVT__full_cmqfifo;
        CData/*0:0*/ __PVT__cmqhas_1room;
        CData/*0:0*/ __PVT__cmqhas_2room;
        CData/*0:0*/ __PVT__cmqhas_3room;
        CData/*0:0*/ __PVT__en_blocking_reqcmdq;
        CData/*0:0*/ __PVT__snp_tx_snpflitv;
        CData/*0:0*/ __PVT__ic_tx_snpreqflitv;
        CData/*0:0*/ __PVT__compdata_tx_reqflitv;
        CData/*0:0*/ __PVT__dirc_flittype_rdnosnp;
        CData/*0:0*/ __PVT__dirc_flittype_wrnosnp;
        CData/*0:0*/ __PVT__snpreq_crdt_avail;
        CData/*0:0*/ __PVT__dat_link_crdt_atleast_2;
        CData/*0:0*/ __PVT__compdata_tx_datflitv;
        CData/*0:0*/ __PVT__xmtdata_crdt_avail;
        CData/*0:0*/ __PVT__clr_unused_compbuff_num;
        CData/*0:0*/ __PVT__wren_compbuff_num_snpreq_1st;
        CData/*0:0*/ __PVT__wren_compbuff_num_snpreq_2nd;
        CData/*0:0*/ __PVT__wren_compbuff_num_compdata_1st;
        CData/*0:0*/ __PVT__wren_compbuff_num_compdata_2nd;
        CData/*0:0*/ __PVT__en_compbuf_2nd_for_snpdata;
        CData/*5:0*/ __PVT__outq_index;
        CData/*5:0*/ __PVT__index_outq_rcvdata;
        CData/*4:0*/ __PVT__compq_buff_to_rcvdatproc_1st;
        CData/*4:0*/ __PVT__compq_buff_to_rcvdatproc_2nd;
    };
    struct {
        CData/*0:0*/ __PVT__vld_compq_buff_to_rcvdatproc_2nd;
        CData/*0:0*/ __PVT__invalid_req_rcvdatproc;
        CData/*0:0*/ __PVT__vld_compbuf_2nd_for_snpdata;
        CData/*0:0*/ __PVT__compdata_sending_ccreq;
        CData/*0:0*/ __PVT__cc_reqflit_valid_snpreq;
        CData/*0:0*/ __PVT__cc_reqflit_valid_compdata;
        CData/*5:0*/ __PVT__index_pendingq_compdata;
        CData/*0:0*/ __PVT__block_compbuf_available;
        CData/*0:0*/ __PVT__allocate_compbuf_compdata;
        CData/*0:0*/ __PVT__compdata_clr_outstand;
        CData/*0:0*/ __PVT__ic_tx_snpreq_datflitv;
        CData/*0:0*/ __PVT__snp_tx_datflitv_resperr;
        CData/*0:0*/ __PVT__reg_dwt_en;
        CData/*0:0*/ __PVT__ignore_likyshared_writeevictorevict;
        CData/*0:0*/ __PVT__writeevict_or_evict;
        CData/*0:0*/ __PVT__slc_readnosnp_apply_dmt_snpreq;
        CData/*0:0*/ __PVT__slc_origreq_is_read_snp_snpreq;
        CData/*0:0*/ __PVT__slc_readnosnp_apply_dmt_compdata;
        CData/*0:0*/ __PVT__slc_origreq_is_read_snp_compdata;
        CData/*0:0*/ __PVT__rcv_reqproc_nodeid_valid;
        CData/*0:0*/ __PVT__xmt_compdata_nodeid_valid;
        CData/*0:0*/ __PVT__xmt_resp_nodeid_valid;
        CData/*0:0*/ __Vcellinp__sig_chi_xmt_snpreq_0__gnt_rsp_snpreq;
        CData/*0:0*/ __Vcellinp__sig_chi_xmt_compdata_0__gnt_resp_compdata;
        CData/*0:0*/ __PVT__fifofull_reqcmdq;
        CData/*0:0*/ __PVT__atom_res_update;
        VL_IN16(__PVT__l3_rddata_txnid,12,0);
        VL_IN16(__PVT__xy_coord_all_pm,10,0);
        VL_OUT16(__PVT__dbid_from_l3,11,0);
        SData/*15:0*/ __PVT__cachehit_vector;
        SData/*9:0*/ __PVT__cache_index_rd_cohc;
        SData/*9:0*/ __PVT__cache_index_rd_cohc_pre;
        SData/*9:0*/ __PVT__cache_index_rd_dirc;
        SData/*15:0*/ __PVT__evict_this_one;
        SData/*15:0*/ __PVT__validity_vector;
        SData/*15:0*/ __PVT__in_pendingq_cache_all;
        SData/*15:0*/ __PVT__wren_cache_vector_dirc;
        SData/*9:0*/ __PVT__cache_index_wr_dirc;
        SData/*9:0*/ __PVT__cache_index_wr_cohc_or_dirc;
        SData/*10:0*/ __PVT__excl_load_srcid;
        SData/*10:0*/ __PVT__excl_store_srcid;
        SData/*15:0*/ __PVT__wren_cache_vector_cohc;
        SData/*9:0*/ __PVT__cache_index_wr_cohc;
        SData/*9:0*/ __PVT__index_cache_eviction;
        SData/*10:0*/ __PVT__rcv_reqproc_full_node_id;
        SData/*10:0*/ __PVT__rcv_reqproc_linear_nodeid;
        SData/*10:0*/ __PVT__rcv_rsp_dat_srcid;
        SData/*10:0*/ __PVT__rcv_rsp_dat_linear_srcid;
        SData/*10:0*/ __PVT__xmt_snpreq_linear_tgtid;
        SData/*10:0*/ __PVT__xmt_snpreq_full_tgtid;
        SData/*10:0*/ __PVT__xmt_snpreq_linear_srcid;
        SData/*10:0*/ __PVT__xmt_snpreq_full_srcid;
        SData/*10:0*/ __PVT__xmt_compdata_linear_nodeid;
        SData/*10:0*/ __PVT__xmt_compdata_full_node_id;
        SData/*10:0*/ __PVT__xmt_resp_linear_nodeid;
        SData/*10:0*/ __PVT__xmt_resp_full_node_id;
        VL_INW(__PVT__ic_RX_REQFLIT,150,0,5);
        VL_OUTW(__PVT__ic_TX_RSPFLIT,72,0,3);
        VL_INW(__PVT__ic_RX_RSPFLIT,72,0,3);
        VL_OUTW(__PVT__ic_TX_SNPFLIT,151,0,5);
        VL_INW(__PVT__ic_RX_DATFLIT,679,0,22);
        VL_INW(__PVT__l3_datflit,511,0,16);
        VL_OUTW(__PVT__ic_TX_DATFLIT,679,0,22);
        VL_IN(__PVT__COH_RNF_Exist,21,0);
    };
    struct {
        VL_IN(__PVT__reg_cc_ctrl1,31,0);
        VL_INW(__PVT__COH_nodeid_all_rn,241,0,8);
        VL_IN(__PVT__cm_homeaddr_base_all_pm,27,0);
        VL_IN(__PVT__cm_homeaddr_limit_all_pm,28,0);
        VL_IN(__PVT__noncm_homeaddr_base_all_pm,27,0);
        VL_IN(__PVT__noncm_homeaddr_limit_all_pm,28,0);
        VL_IN(__PVT__dct_enable_all_rn_vec,21,0);
        VL_OUTW(__PVT__cc_reqflit,153,0,5);
        VL_INW(__PVT__l3_rspflit,72,0,3);
        VL_OUTW(__PVT__l3_wrdata,511,0,16);
        VlWide<5>/*154:0*/ __PVT__cmd_ph4;
        VlWide<5>/*154:0*/ __PVT__cm_cmd;
        VlWide<3>/*83:0*/ __PVT__evict_details;
        IData/*31:0*/ __PVT__rddata_cache;
        IData/*31:0*/ __PVT__wrdata_cache_dirc;
        IData/*31:0*/ __PVT__wrdata_cache_cohc;
        IData/*31:0*/ __PVT__read_datareuse_compdata_1st;
        IData/*31:0*/ __PVT__dealloc_compfifo_vector_compdata;
        IData/*31:0*/ __PVT__rden_whichcompfifo_1st;
        VlWide<16>/*511:0*/ __PVT__rddata_to_compdata_1st;
        IData/*31:0*/ __PVT__read_datareuse_compdata_2nd;
        IData/*31:0*/ __PVT__rden_whichcompfifo_2nd;
        VlWide<16>/*511:0*/ __PVT__rddata_to_compdata_2nd;
        VlWide<4>/*127:0*/ __PVT__valid_location_all;
        VlWide<5>/*155:0*/ __PVT__wrdata_reqcmdq;
        IData/*31:0*/ __PVT__wren_compbuff_rcv_dat;
        VlWide<16>/*511:0*/ __PVT__wrdata_compbuff_rcv_dat;
        IData/*31:0*/ __PVT__wren_compbuff_xmt_dat;
        VlWide<16>/*511:0*/ __PVT__wrdata_compbuff_xmt_dat;
        IData/*31:0*/ __PVT__wren_compbuff;
        VlWide<16>/*511:0*/ __PVT__wrdata_compbuff;
        VlWide<3>/*73:0*/ __PVT__wrdata_respcmdq;
        VlWide<4>/*108:0*/ __PVT__wrdata_drespcmdq;
        VlWide<4>/*108:0*/ __PVT__wrdata_memrespcmdq;
        VlWide<6>/*180:0*/ __PVT__wrdata_outcompfifo;
        VlWide<6>/*180:0*/ __PVT__rddata_outcompfifo;
        VlWide<3>/*73:0*/ __PVT__respbody_snpreq;
        VlWide<3>/*73:0*/ __PVT__respbody_compdata;
        VlWide<3>/*73:0*/ __PVT__respbody_rdrcpt;
        VlWide<3>/*73:0*/ __PVT__respbody_retryack;
        VlWide<3>/*73:0*/ __PVT__respbody_pcrdgnt;
        IData/*31:0*/ __PVT__clr_outstand_cmd_compdata;
        IData/*31:0*/ __PVT__clr_outstand_cmd_snpreq;
        VlWide<5>/*151:0*/ __PVT__txflit_snpreq_memreq;
        VlWide<5>/*151:0*/ __PVT__snp_tx_snpflit_compdata;
        VlWide<5>/*151:0*/ __PVT__ic_tx_snpreqflit;
        VlWide<22>/*679:0*/ __PVT__compdata_tx_datflit;
        IData/*31:0*/ __PVT__clr_outstand_prep;
        IData/*31:0*/ __PVT__dealloc_compfifo_vector_ccn;
        VlWide<22>/*679:0*/ __PVT__ic_tx_snpreq_datflit;
        VlWide<22>/*679:0*/ __PVT__snp_tx_datflit_resperr;
        VlWide<6>/*190:0*/ __Vcellout__snpreq_fifo_0__fifo_rddata;
        VlWide<6>/*190:0*/ __Vcellinp__snpreq_fifo_0__fifo_wrdata;
        VL_OUT64(__PVT__l3_wrbe,63,0);
        QData/*51:0*/ __PVT__cmd_addr_ph3;
        QData/*35:0*/ __PVT__cache_tag_rd_cohc;
        QData/*35:0*/ __PVT__cache_tag_rd_dirc;
        QData/*35:0*/ __PVT__rdout_tag_value;
        QData/*35:0*/ __PVT__cache_tag_wr_dirc;
        QData/*45:0*/ __PVT__excl_load_addr;
        QData/*45:0*/ __PVT__excl_store_addr;
        QData/*45:0*/ __PVT__atom_addr;
        QData/*35:0*/ __PVT__cache_tag_wr_cohc;
        QData/*63:0*/ __PVT__rdbe_to_compdata_1st;
    };
    struct {
        QData/*63:0*/ __PVT__rdbe_to_compdata_2nd;
        QData/*63:0*/ __PVT__wrbe_compbuff_rcv_dat;
        QData/*63:0*/ __PVT__wrbe_compbuff_xmt_dat;
        QData/*63:0*/ __PVT__wrbe_compbuff;
        VlWide<6>/*190:0*/ __PVT__wrdata_snpreqfifo;
        VlWide<6>/*190:0*/ __PVT__rddata_snpreqfifo;
        VlWide<6>/*180:0*/ __PVT__data_outcompfifo;
        QData/*51:0*/ __PVT__addr_outstandq_to_compdata;
        VlWide<6>/*180:0*/ __Vcellout__sig_coherency_ctrlr_0__wrdata_outcompfifo;
        VL_IN(__PVT__i_ucie_base_addresses[16],27,0);
        VL_IN(__PVT__i_ucie_limit_addresses[16],28,0);
    };

    // INTERNAL VARIABLES
    Vsig_topology_top__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vsig_topology_top_sig_coherency_top__pi5(Vsig_topology_top__Syms* symsp, const char* v__name);
    ~Vsig_topology_top_sig_coherency_top__pi5();
    VL_UNCOPYABLE(Vsig_topology_top_sig_coherency_top__pi5);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
