// Verilated -*- SystemC -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vsig_topology_top.h for the primary calling header

#ifndef VERILATED_VSIG_TOPOLOGY_TOP_SIG_CLUST_CG_TOP_H_
#define VERILATED_VSIG_TOPOLOGY_TOP_SIG_CLUST_CG_TOP_H_  // guard

#include "systemc"
#include "verilated_sc.h"
#include "verilated.h"
class Vsig_topology_top_sig_cg_cell;
class Vsig_topology_top_sig_clust_cg_ctrl__Cz5;


class Vsig_topology_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vsig_topology_top_sig_clust_cg_top final : public VerilatedModule {
  public:
    // CELLS
    Vsig_topology_top_sig_clust_cg_ctrl__Cz5* __PVT__inst_cc_cg_ctrl;
    Vsig_topology_top_sig_cg_cell* __PVT__inst_cg_cc_ic_clk;
    Vsig_topology_top_sig_clust_cg_ctrl__Cz5* __PVT__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_ppx_rx_cg_ctrl;
    Vsig_topology_top_sig_cg_cell* __PVT__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_cg_ppx_rx_intfc_clk;
    Vsig_topology_top_sig_cg_cell* __PVT__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_cg_ppx_rx_ic_clk;
    Vsig_topology_top_sig_clust_cg_ctrl__Cz5* __PVT__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_ppx_tx_cg_ctrl;
    Vsig_topology_top_sig_cg_cell* __PVT__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_cg_ppx_tx_intfc_clk;
    Vsig_topology_top_sig_cg_cell* __PVT__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_cg_ppx_tx_ic_clk;
    Vsig_topology_top_sig_clust_cg_ctrl__Cz5* __PVT__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_icx_rx_cg_ctrl;
    Vsig_topology_top_sig_cg_cell* __PVT__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_cg_icx_rx_intfc_clk;
    Vsig_topology_top_sig_cg_cell* __PVT__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_cg_icx_rx_ic_clk;
    Vsig_topology_top_sig_clust_cg_ctrl__Cz5* __PVT__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_icx_tx_cg_ctrl;
    Vsig_topology_top_sig_cg_cell* __PVT__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_cg_icx_tx_intfc_clk;
    Vsig_topology_top_sig_cg_cell* __PVT__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_cg_icx_tx_ic_clk;
    Vsig_topology_top_sig_clust_cg_ctrl__Cz5* __PVT__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_ppx_rx_cg_ctrl;
    Vsig_topology_top_sig_cg_cell* __PVT__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_cg_ppx_rx_intfc_clk;
    Vsig_topology_top_sig_cg_cell* __PVT__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_cg_ppx_rx_ic_clk;
    Vsig_topology_top_sig_clust_cg_ctrl__Cz5* __PVT__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_ppx_tx_cg_ctrl;
    Vsig_topology_top_sig_cg_cell* __PVT__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_cg_ppx_tx_intfc_clk;
    Vsig_topology_top_sig_cg_cell* __PVT__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_cg_ppx_tx_ic_clk;
    Vsig_topology_top_sig_clust_cg_ctrl__Cz5* __PVT__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_icx_rx_cg_ctrl;
    Vsig_topology_top_sig_cg_cell* __PVT__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_cg_icx_rx_intfc_clk;
    Vsig_topology_top_sig_cg_cell* __PVT__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_cg_icx_rx_ic_clk;
    Vsig_topology_top_sig_clust_cg_ctrl__Cz5* __PVT__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_icx_tx_cg_ctrl;
    Vsig_topology_top_sig_cg_cell* __PVT__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_cg_icx_tx_intfc_clk;
    Vsig_topology_top_sig_cg_cell* __PVT__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_cg_icx_tx_ic_clk;
    Vsig_topology_top_sig_clust_cg_ctrl__Cz5* __PVT__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_ppx_rx_cg_ctrl;
    Vsig_topology_top_sig_cg_cell* __PVT__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_cg_ppx_rx_intfc_clk;
    Vsig_topology_top_sig_cg_cell* __PVT__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_cg_ppx_rx_ic_clk;
    Vsig_topology_top_sig_clust_cg_ctrl__Cz5* __PVT__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_ppx_tx_cg_ctrl;
    Vsig_topology_top_sig_cg_cell* __PVT__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_cg_ppx_tx_intfc_clk;
    Vsig_topology_top_sig_cg_cell* __PVT__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_cg_ppx_tx_ic_clk;
    Vsig_topology_top_sig_clust_cg_ctrl__Cz5* __PVT__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_icx_rx_cg_ctrl;
    Vsig_topology_top_sig_cg_cell* __PVT__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_cg_icx_rx_intfc_clk;
    Vsig_topology_top_sig_cg_cell* __PVT__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_cg_icx_rx_ic_clk;
    Vsig_topology_top_sig_clust_cg_ctrl__Cz5* __PVT__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_icx_tx_cg_ctrl;
    Vsig_topology_top_sig_cg_cell* __PVT__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_cg_icx_tx_intfc_clk;
    Vsig_topology_top_sig_cg_cell* __PVT__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_cg_icx_tx_ic_clk;
    Vsig_topology_top_sig_clust_cg_ctrl__Cz5* __PVT__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_ppx_rx_cg_ctrl;
    Vsig_topology_top_sig_cg_cell* __PVT__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_cg_ppx_rx_intfc_clk;
    Vsig_topology_top_sig_cg_cell* __PVT__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_cg_ppx_rx_ic_clk;
    Vsig_topology_top_sig_clust_cg_ctrl__Cz5* __PVT__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_ppx_tx_cg_ctrl;
    Vsig_topology_top_sig_cg_cell* __PVT__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_cg_ppx_tx_intfc_clk;
    Vsig_topology_top_sig_cg_cell* __PVT__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_cg_ppx_tx_ic_clk;
    Vsig_topology_top_sig_clust_cg_ctrl__Cz5* __PVT__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_icx_rx_cg_ctrl;
    Vsig_topology_top_sig_cg_cell* __PVT__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_cg_icx_rx_intfc_clk;
    Vsig_topology_top_sig_cg_cell* __PVT__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_cg_icx_rx_ic_clk;
    Vsig_topology_top_sig_clust_cg_ctrl__Cz5* __PVT__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_icx_tx_cg_ctrl;
    Vsig_topology_top_sig_cg_cell* __PVT__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_cg_icx_tx_intfc_clk;
    Vsig_topology_top_sig_cg_cell* __PVT__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_cg_icx_tx_ic_clk;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(__PVT__i_pp_intfc_clk,3,0);
        VL_IN8(__PVT__i_rst_n_pp_intfc_clk,3,0);
        VL_IN8(__PVT__i_pp_rx_is_inactive,3,0);
        VL_IN8(__PVT__i_pp_tx_is_inactive,3,0);
        VL_IN8(__PVT__i_activate_pp_rx,3,0);
        VL_IN8(__PVT__i_activate_pp_tx,3,0);
        VL_IN8(__PVT__i_pp_exists,3,0);
        VL_OUT8(__PVT__o_pp_rx_intfc_gclk,3,0);
        VL_OUT8(__PVT__o_pp_rx_ic_gclk,3,0);
        VL_OUT8(__PVT__o_pp_tx_intfc_gclk,3,0);
        VL_OUT8(__PVT__o_pp_tx_ic_gclk,3,0);
        VL_IN8(__PVT__i_ic_intfc_clk,3,0);
        VL_IN8(__PVT__i_rst_n_ic_intfc_clk,3,0);
        VL_IN8(__PVT__i_ic_rx_is_inactive,3,0);
        VL_IN8(__PVT__i_ic_tx_is_inactive,3,0);
        VL_IN8(__PVT__i_activate_ic_rx,3,0);
        VL_IN8(__PVT__i_activate_ic_tx,3,0);
        VL_IN8(__PVT__i_ic_exists,3,0);
        VL_OUT8(__PVT__o_ic_rx_intfc_gclk,3,0);
        VL_OUT8(__PVT__o_ic_rx_ic_gclk,3,0);
        VL_OUT8(__PVT__o_ic_tx_intfc_gclk,3,0);
        VL_OUT8(__PVT__o_ic_tx_ic_gclk,3,0);
        VL_IN8(__PVT__i_cc_intfc_clk,0,0);
        VL_IN8(__PVT__i_rst_n_cc_intfc_clk,0,0);
        VL_IN8(__PVT__i_ic_clk,0,0);
        VL_IN8(__PVT__i_rst_n_ic_clk,0,0);
        VL_IN8(__PVT__i_cc_is_inactive,0,0);
        VL_IN8(__PVT__i_activate_cc,0,0);
        VL_IN8(__PVT__i_cc_exists,0,0);
        VL_OUT8(__PVT__o_cc_ic_gclk,0,0);
        VL_OUT8(__PVT__o_cc_intfc_gclk,0,0);
        VL_IN8(__PVT__i_cg_reg_ctrl_2,1,0);
        CData/*0:0*/ __PVT__all_are_inactive;
        CData/*7:0*/ __PVT__cc_inactivity_cntr;
        CData/*7:0*/ __PVT__ic_inactivity_cntr;
        CData/*7:0*/ __PVT__pp_inactivity_cntr;
        CData/*7:0*/ __PVT__cluster_inactivity_counter;
        CData/*0:0*/ __PVT__clock_gating_mode;
        CData/*0:0*/ __PVT__clock_gating_enable;
        CData/*7:0*/ __PVT__pp_inactivity_cntr_mux;
        CData/*7:0*/ __PVT__ic_inactivity_cntr_mux;
        CData/*7:0*/ __PVT__cc_inactivity_cntr_mux;
        CData/*3:0*/ __PVT__ppx_rx_is_inactive_mux;
        CData/*3:0*/ __PVT__icx_rx_is_inactive_mux;
        CData/*3:0*/ __PVT__ppx_tx_is_inactive_mux;
        CData/*3:0*/ __PVT__icx_tx_is_inactive_mux;
        CData/*0:0*/ __PVT__cc_is_inactive_mux;
        CData/*3:0*/ __PVT__ppx_rx_intfc_cg_en_n;
        CData/*3:0*/ __PVT__ppx_rx_ic_cg_en_n;
        CData/*3:0*/ __PVT__icx_rx_intfc_cg_en_n;
        CData/*3:0*/ __PVT__icx_rx_ic_cg_en_n;
        CData/*3:0*/ __PVT__ppx_tx_intfc_cg_en_n;
        CData/*3:0*/ __PVT__ppx_tx_ic_cg_en_n;
        CData/*3:0*/ __PVT__icx_tx_intfc_cg_en_n;
        CData/*3:0*/ __PVT__icx_tx_ic_cg_en_n;
        CData/*0:0*/ __PVT__cc_ic_cg_en_n;
        CData/*0:0*/ __PVT__cc_intfc_cg_en_n;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_ppx_rx_cg_ctrl__o_tx_cg_en_n;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_ppx_rx_cg_ctrl__o_rx_cg_en_n;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_ppx_rx_cg_ctrl__i_activate_block;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_ppx_rx_cg_ctrl__i_block_is_inactive;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_ppx_rx_cg_ctrl__i_block_exists;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_ppx_rx_cg_ctrl__i_rst_n_rx_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_ppx_rx_cg_ctrl__i_rx_clk;
    };
    struct {
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_cg_ppx_rx_intfc_clk__o_gated_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_cg_ppx_rx_intfc_clk__i_cg_enable_n;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_cg_ppx_rx_intfc_clk__i_clk;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_cg_ppx_rx_ic_clk__o_gated_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_cg_ppx_rx_ic_clk__i_cg_enable_n;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_ppx_tx_cg_ctrl__o_tx_cg_en_n;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_ppx_tx_cg_ctrl__o_rx_cg_en_n;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_ppx_tx_cg_ctrl__i_activate_block;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_ppx_tx_cg_ctrl__i_block_is_inactive;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_ppx_tx_cg_ctrl__i_block_exists;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_ppx_tx_cg_ctrl__i_rst_n_tx_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_ppx_tx_cg_ctrl__i_tx_clk;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_cg_ppx_tx_intfc_clk__o_gated_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_cg_ppx_tx_intfc_clk__i_cg_enable_n;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_cg_ppx_tx_intfc_clk__i_clk;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_cg_ppx_tx_ic_clk__o_gated_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_cg_ppx_tx_ic_clk__i_cg_enable_n;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_icx_rx_cg_ctrl__o_tx_cg_en_n;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_icx_rx_cg_ctrl__o_rx_cg_en_n;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_icx_rx_cg_ctrl__i_activate_block;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_icx_rx_cg_ctrl__i_block_is_inactive;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_icx_rx_cg_ctrl__i_block_exists;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_icx_rx_cg_ctrl__i_rst_n_rx_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_icx_rx_cg_ctrl__i_rx_clk;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_cg_icx_rx_intfc_clk__o_gated_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_cg_icx_rx_intfc_clk__i_cg_enable_n;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_cg_icx_rx_intfc_clk__i_clk;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_cg_icx_rx_ic_clk__o_gated_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_cg_icx_rx_ic_clk__i_cg_enable_n;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_icx_tx_cg_ctrl__o_tx_cg_en_n;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_icx_tx_cg_ctrl__o_rx_cg_en_n;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_icx_tx_cg_ctrl__i_activate_block;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_icx_tx_cg_ctrl__i_block_is_inactive;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_icx_tx_cg_ctrl__i_block_exists;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_icx_tx_cg_ctrl__i_rst_n_tx_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_icx_tx_cg_ctrl__i_tx_clk;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_cg_icx_tx_intfc_clk__o_gated_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_cg_icx_tx_intfc_clk__i_cg_enable_n;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_cg_icx_tx_intfc_clk__i_clk;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_cg_icx_tx_ic_clk__o_gated_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__0__KET____DOT__inst_cg_icx_tx_ic_clk__i_cg_enable_n;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_ppx_rx_cg_ctrl__o_tx_cg_en_n;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_ppx_rx_cg_ctrl__o_rx_cg_en_n;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_ppx_rx_cg_ctrl__i_activate_block;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_ppx_rx_cg_ctrl__i_block_is_inactive;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_ppx_rx_cg_ctrl__i_block_exists;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_ppx_rx_cg_ctrl__i_rst_n_rx_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_ppx_rx_cg_ctrl__i_rx_clk;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_cg_ppx_rx_intfc_clk__o_gated_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_cg_ppx_rx_intfc_clk__i_cg_enable_n;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_cg_ppx_rx_intfc_clk__i_clk;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_cg_ppx_rx_ic_clk__o_gated_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_cg_ppx_rx_ic_clk__i_cg_enable_n;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_ppx_tx_cg_ctrl__o_tx_cg_en_n;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_ppx_tx_cg_ctrl__o_rx_cg_en_n;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_ppx_tx_cg_ctrl__i_activate_block;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_ppx_tx_cg_ctrl__i_block_is_inactive;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_ppx_tx_cg_ctrl__i_block_exists;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_ppx_tx_cg_ctrl__i_rst_n_tx_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_ppx_tx_cg_ctrl__i_tx_clk;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_cg_ppx_tx_intfc_clk__o_gated_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_cg_ppx_tx_intfc_clk__i_cg_enable_n;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_cg_ppx_tx_intfc_clk__i_clk;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_cg_ppx_tx_ic_clk__o_gated_clk;
    };
    struct {
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_cg_ppx_tx_ic_clk__i_cg_enable_n;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_icx_rx_cg_ctrl__o_tx_cg_en_n;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_icx_rx_cg_ctrl__o_rx_cg_en_n;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_icx_rx_cg_ctrl__i_activate_block;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_icx_rx_cg_ctrl__i_block_is_inactive;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_icx_rx_cg_ctrl__i_block_exists;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_icx_rx_cg_ctrl__i_rst_n_rx_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_icx_rx_cg_ctrl__i_rx_clk;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_cg_icx_rx_intfc_clk__o_gated_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_cg_icx_rx_intfc_clk__i_cg_enable_n;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_cg_icx_rx_intfc_clk__i_clk;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_cg_icx_rx_ic_clk__o_gated_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_cg_icx_rx_ic_clk__i_cg_enable_n;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_icx_tx_cg_ctrl__o_tx_cg_en_n;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_icx_tx_cg_ctrl__o_rx_cg_en_n;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_icx_tx_cg_ctrl__i_activate_block;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_icx_tx_cg_ctrl__i_block_is_inactive;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_icx_tx_cg_ctrl__i_block_exists;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_icx_tx_cg_ctrl__i_rst_n_tx_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_icx_tx_cg_ctrl__i_tx_clk;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_cg_icx_tx_intfc_clk__o_gated_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_cg_icx_tx_intfc_clk__i_cg_enable_n;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_cg_icx_tx_intfc_clk__i_clk;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_cg_icx_tx_ic_clk__o_gated_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__1__KET____DOT__inst_cg_icx_tx_ic_clk__i_cg_enable_n;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_ppx_rx_cg_ctrl__o_tx_cg_en_n;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_ppx_rx_cg_ctrl__o_rx_cg_en_n;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_ppx_rx_cg_ctrl__i_activate_block;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_ppx_rx_cg_ctrl__i_block_is_inactive;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_ppx_rx_cg_ctrl__i_block_exists;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_ppx_rx_cg_ctrl__i_rst_n_rx_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_ppx_rx_cg_ctrl__i_rx_clk;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_cg_ppx_rx_intfc_clk__o_gated_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_cg_ppx_rx_intfc_clk__i_cg_enable_n;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_cg_ppx_rx_intfc_clk__i_clk;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_cg_ppx_rx_ic_clk__o_gated_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_cg_ppx_rx_ic_clk__i_cg_enable_n;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_ppx_tx_cg_ctrl__o_tx_cg_en_n;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_ppx_tx_cg_ctrl__o_rx_cg_en_n;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_ppx_tx_cg_ctrl__i_activate_block;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_ppx_tx_cg_ctrl__i_block_is_inactive;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_ppx_tx_cg_ctrl__i_block_exists;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_ppx_tx_cg_ctrl__i_rst_n_tx_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_ppx_tx_cg_ctrl__i_tx_clk;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_cg_ppx_tx_intfc_clk__o_gated_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_cg_ppx_tx_intfc_clk__i_cg_enable_n;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_cg_ppx_tx_intfc_clk__i_clk;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_cg_ppx_tx_ic_clk__o_gated_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_cg_ppx_tx_ic_clk__i_cg_enable_n;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_icx_rx_cg_ctrl__o_tx_cg_en_n;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_icx_rx_cg_ctrl__o_rx_cg_en_n;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_icx_rx_cg_ctrl__i_activate_block;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_icx_rx_cg_ctrl__i_block_is_inactive;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_icx_rx_cg_ctrl__i_block_exists;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_icx_rx_cg_ctrl__i_rst_n_rx_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_icx_rx_cg_ctrl__i_rx_clk;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_cg_icx_rx_intfc_clk__o_gated_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_cg_icx_rx_intfc_clk__i_cg_enable_n;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_cg_icx_rx_intfc_clk__i_clk;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_cg_icx_rx_ic_clk__o_gated_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_cg_icx_rx_ic_clk__i_cg_enable_n;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_icx_tx_cg_ctrl__o_tx_cg_en_n;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_icx_tx_cg_ctrl__o_rx_cg_en_n;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_icx_tx_cg_ctrl__i_activate_block;
    };
    struct {
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_icx_tx_cg_ctrl__i_block_is_inactive;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_icx_tx_cg_ctrl__i_block_exists;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_icx_tx_cg_ctrl__i_rst_n_tx_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_icx_tx_cg_ctrl__i_tx_clk;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_cg_icx_tx_intfc_clk__o_gated_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_cg_icx_tx_intfc_clk__i_cg_enable_n;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_cg_icx_tx_intfc_clk__i_clk;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_cg_icx_tx_ic_clk__o_gated_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__2__KET____DOT__inst_cg_icx_tx_ic_clk__i_cg_enable_n;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_ppx_rx_cg_ctrl__o_tx_cg_en_n;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_ppx_rx_cg_ctrl__o_rx_cg_en_n;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_ppx_rx_cg_ctrl__i_activate_block;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_ppx_rx_cg_ctrl__i_block_is_inactive;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_ppx_rx_cg_ctrl__i_block_exists;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_ppx_rx_cg_ctrl__i_rst_n_rx_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_ppx_rx_cg_ctrl__i_rx_clk;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_cg_ppx_rx_intfc_clk__o_gated_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_cg_ppx_rx_intfc_clk__i_cg_enable_n;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_cg_ppx_rx_intfc_clk__i_clk;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_cg_ppx_rx_ic_clk__o_gated_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_cg_ppx_rx_ic_clk__i_cg_enable_n;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_ppx_tx_cg_ctrl__o_tx_cg_en_n;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_ppx_tx_cg_ctrl__o_rx_cg_en_n;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_ppx_tx_cg_ctrl__i_activate_block;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_ppx_tx_cg_ctrl__i_block_is_inactive;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_ppx_tx_cg_ctrl__i_block_exists;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_ppx_tx_cg_ctrl__i_rst_n_tx_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_ppx_tx_cg_ctrl__i_tx_clk;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_cg_ppx_tx_intfc_clk__o_gated_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_cg_ppx_tx_intfc_clk__i_cg_enable_n;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_cg_ppx_tx_intfc_clk__i_clk;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_cg_ppx_tx_ic_clk__o_gated_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_cg_ppx_tx_ic_clk__i_cg_enable_n;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_icx_rx_cg_ctrl__o_tx_cg_en_n;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_icx_rx_cg_ctrl__o_rx_cg_en_n;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_icx_rx_cg_ctrl__i_activate_block;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_icx_rx_cg_ctrl__i_block_is_inactive;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_icx_rx_cg_ctrl__i_block_exists;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_icx_rx_cg_ctrl__i_rst_n_rx_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_icx_rx_cg_ctrl__i_rx_clk;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_cg_icx_rx_intfc_clk__o_gated_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_cg_icx_rx_intfc_clk__i_cg_enable_n;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_cg_icx_rx_intfc_clk__i_clk;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_cg_icx_rx_ic_clk__o_gated_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_cg_icx_rx_ic_clk__i_cg_enable_n;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_icx_tx_cg_ctrl__o_tx_cg_en_n;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_icx_tx_cg_ctrl__o_rx_cg_en_n;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_icx_tx_cg_ctrl__i_activate_block;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_icx_tx_cg_ctrl__i_block_is_inactive;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_icx_tx_cg_ctrl__i_block_exists;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_icx_tx_cg_ctrl__i_rst_n_tx_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_icx_tx_cg_ctrl__i_tx_clk;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_cg_icx_tx_intfc_clk__o_gated_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_cg_icx_tx_intfc_clk__i_cg_enable_n;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_cg_icx_tx_intfc_clk__i_clk;
        CData/*0:0*/ __Vcellout__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_cg_icx_tx_ic_clk__o_gated_clk;
        CData/*0:0*/ __Vcellinp__gen_inst_cg_ctlr__BRA__3__KET____DOT__inst_cg_icx_tx_ic_clk__i_cg_enable_n;
        VL_IN(__PVT__i_cg_reg_ctrl_1,31,0);
    };

    // INTERNAL VARIABLES
    Vsig_topology_top__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vsig_topology_top_sig_clust_cg_top(Vsig_topology_top__Syms* symsp, const char* v__name);
    ~Vsig_topology_top_sig_clust_cg_top();
    VL_UNCOPYABLE(Vsig_topology_top_sig_clust_cg_top);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
