// Verilated -*- SystemC -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vsig_topology_top.h for the primary calling header

#ifndef VERILATED_VSIG_TOPOLOGY_TOP_SIG_CL0_CLUSTERCORE__PI4_H_
#define VERILATED_VSIG_TOPOLOGY_TOP_SIG_CL0_CLUSTERCORE__PI4_H_  // guard

#include "systemc"
#include "verilated_sc.h"
#include "verilated.h"
class Vsig_topology_top_sig_L3top__pi7;
class Vsig_topology_top_sig_clust_cg_top;
class Vsig_topology_top_sig_cluster_csr;
class Vsig_topology_top_sig_cnoc_port_rx_handshake;
class Vsig_topology_top_sig_cnoc_port_tx_handshake;
class Vsig_topology_top_sig_coherency_top__pi6;
class Vsig_topology_top_sig_common_porttop__pi5;
class Vsig_topology_top_sig_common_porttop__pi8;
class Vsig_topology_top_sig_node_porttop_wrapper__pi10;
class Vsig_topology_top_sig_node_porttop_wrapper__pi9;


class Vsig_topology_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vsig_topology_top_sig_cl0_clustercore__pi4 final : public VerilatedModule {
  public:
    // CELLS
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__cc_port_req_vc0_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__cc_port_rsp_vc0_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__cc_port_dat_vc0_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__cc_port_req_vc1_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__cc_port_rsp_vc1_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__cc_port_dat_vc1_rx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__cc_port_req_vc0_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__cc_port_rsp_vc0_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__cc_port_dat_vc0_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__cc_port_req_vc1_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__cc_port_rsp_vc1_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__cc_port_dat_vc1_tx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__l3_port_req_vc0_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__l3_port_rsp_vc0_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__l3_port_dat_vc0_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__l3_port_req_vc1_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__l3_port_rsp_vc1_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__l3_port_dat_vc1_rx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__l3_port_req_vc0_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__l3_port_rsp_vc0_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__l3_port_dat_vc0_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__l3_port_req_vc1_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__l3_port_rsp_vc1_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__l3_port_dat_vc1_tx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__n2_port_req_vc0_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__n2_port_rsp_vc0_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__n2_port_dat_vc0_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__n2_port_req_vc1_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__n2_port_rsp_vc1_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__n2_port_dat_vc1_rx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__n2_port_req_vc0_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__n2_port_rsp_vc0_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__n2_port_dat_vc0_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__n2_port_req_vc1_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__n2_port_rsp_vc1_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__n2_port_dat_vc1_tx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__n3_port_req_vc0_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__n3_port_rsp_vc0_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__n3_port_dat_vc0_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__n3_port_req_vc1_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__n3_port_rsp_vc1_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__n3_port_dat_vc1_rx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__n3_port_req_vc0_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__n3_port_rsp_vc0_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__n3_port_dat_vc0_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__n3_port_req_vc1_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__n3_port_rsp_vc1_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__n3_port_dat_vc1_tx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__n1_port_req_vc0_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__n1_port_rsp_vc0_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__n1_port_dat_vc0_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__n1_port_req_vc1_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__n1_port_rsp_vc1_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__n1_port_dat_vc1_rx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__n1_port_req_vc0_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__n1_port_rsp_vc0_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__n1_port_dat_vc0_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__n1_port_req_vc1_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__n1_port_rsp_vc1_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__n1_port_dat_vc1_tx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__n0_port_req_vc0_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__n0_port_rsp_vc0_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__n0_port_dat_vc0_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__n0_port_req_vc1_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__n0_port_rsp_vc1_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__n0_port_dat_vc1_rx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__n0_port_req_vc0_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__n0_port_rsp_vc0_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__n0_port_dat_vc0_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__n0_port_req_vc1_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__n0_port_rsp_vc1_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__n0_port_dat_vc1_tx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__icn_port_req_vc0_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__icn_port_rsp_vc0_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__icn_port_dat_vc0_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__icn_port_req_vc1_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__icn_port_rsp_vc1_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__icn_port_dat_vc1_rx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__icn_port_req_vc0_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__icn_port_rsp_vc0_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__icn_port_dat_vc0_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__icn_port_req_vc1_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__icn_port_rsp_vc1_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__icn_port_dat_vc1_tx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__ics_port_req_vc0_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__ics_port_rsp_vc0_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__ics_port_dat_vc0_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__ics_port_req_vc1_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__ics_port_rsp_vc1_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__ics_port_dat_vc1_rx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__ics_port_req_vc0_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__ics_port_rsp_vc0_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__ics_port_dat_vc0_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__ics_port_req_vc1_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__ics_port_rsp_vc1_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__ics_port_dat_vc1_tx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__icw_port_req_vc0_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__icw_port_rsp_vc0_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__icw_port_dat_vc0_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__icw_port_req_vc1_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__icw_port_rsp_vc1_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__icw_port_dat_vc1_rx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__icw_port_req_vc0_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__icw_port_rsp_vc0_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__icw_port_dat_vc0_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__icw_port_req_vc1_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__icw_port_rsp_vc1_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__icw_port_dat_vc1_tx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__ice_port_req_vc0_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__ice_port_rsp_vc0_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__ice_port_dat_vc0_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__ice_port_req_vc1_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__ice_port_rsp_vc1_rx_hs;
    Vsig_topology_top_sig_cnoc_port_rx_handshake* __PVT__ice_port_dat_vc1_rx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__ice_port_req_vc0_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__ice_port_rsp_vc0_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__ice_port_dat_vc0_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__ice_port_req_vc1_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__ice_port_rsp_vc1_tx_hs;
    Vsig_topology_top_sig_cnoc_port_tx_handshake* __PVT__ice_port_dat_vc1_tx_hs;
    Vsig_topology_top_sig_common_porttop__pi5* __PVT__sig_cc_porttop_0;
    Vsig_topology_top_sig_coherency_top__pi6* __PVT__sig_chi_cc_top_0;
    Vsig_topology_top_sig_L3top__pi7* __PVT__sig_L3top_bypass_0;
    Vsig_topology_top_sig_common_porttop__pi8* __PVT__sig_l3_porttop_0;
    Vsig_topology_top_sig_node_porttop_wrapper__pi9* __PVT__sig_node_porttop_rn_p2;
    Vsig_topology_top_sig_node_porttop_wrapper__pi9* __PVT__sig_node_porttop_rn_p3;
    Vsig_topology_top_sig_node_porttop_wrapper__pi10* __PVT__sig_node_porttop_sn_p1;
    Vsig_topology_top_sig_node_porttop_wrapper__pi10* __PVT__sig_node_porttop_sn_p0;
    Vsig_topology_top_sig_cluster_csr* __PVT__inst_sig_cluster_csr;
    Vsig_topology_top_sig_clust_cg_top* __PVT__sig_clust_cg_top_0;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(__PVT__ic_clk,0,0);
        VL_IN8(__PVT__rstb_ic_clk,0,0);
        VL_OUT8(__PVT__cc_is_inactive,0,0);
        VL_IN8(__PVT__noc_is_inactive,0,0);
        VL_OUT8(__PVT__cache_init_complete,0,0);
        VL_IN8(__PVT__all_cache_init_complete,0,0);
        VL_IN8(__PVT__cc_intfrx_clk,0,0);
        VL_IN8(__PVT__cc_rstb_intfrx_clk,0,0);
        VL_IN8(__PVT__p2_intfrx_clk,0,0);
        VL_IN8(__PVT__p2_rstb_intfrx_clk,0,0);
        VL_IN8(__PVT__p2_RX_LINKACTIVEREQ,0,0);
        VL_OUT8(__PVT__p2_RX_LINKACTIVEACK,0,0);
        VL_IN8(__PVT__p2_RX_REQFLITPEND,0,0);
        VL_IN8(__PVT__p2_RX_REQFLITV,0,0);
        VL_OUT8(__PVT__p2_RX_REQLCRDV,0,0);
        VL_IN8(__PVT__p2_RX_RSPFLITPEND,0,0);
        VL_IN8(__PVT__p2_RX_RSPFLITV,0,0);
        VL_OUT8(__PVT__p2_RX_RSPLCRDV,0,0);
        VL_IN8(__PVT__p2_RX_DATFLITPEND,0,0);
        VL_IN8(__PVT__p2_RX_DATFLITV,0,0);
        VL_OUT8(__PVT__p2_RX_DATLCRDV,0,0);
        VL_OUT8(__PVT__p2_TX_LINKACTIVEREQ,0,0);
        VL_IN8(__PVT__p2_TX_LINKACTIVEACK,0,0);
        VL_OUT8(__PVT__p2_TX_SNPFLITPEND,0,0);
        VL_OUT8(__PVT__p2_TX_SNPFLITV,0,0);
        VL_IN8(__PVT__p2_TX_SNPLCRDV,0,0);
        VL_OUT8(__PVT__p2_TX_RSPFLITPEND,0,0);
        VL_OUT8(__PVT__p2_TX_RSPFLITV,0,0);
        VL_IN8(__PVT__p2_TX_RSPLCRDV,0,0);
        VL_OUT8(__PVT__p2_TX_DATFLITPEND,0,0);
        VL_OUT8(__PVT__p2_TX_DATFLITV,0,0);
        VL_IN8(__PVT__p2_TX_DATLCRDV,0,0);
        VL_OUT8(__PVT__p2_ic_TXSACTIVE,0,0);
        VL_IN8(__PVT__p2_ic_RXSACTIVE,0,0);
        VL_IN8(__PVT__p2_syscoreq,0,0);
        VL_OUT8(__PVT__p2_syscoack,0,0);
        VL_IN8(__PVT__p2_reg_syscoh,1,0);
        VL_IN8(__PVT__p3_intfrx_clk,0,0);
        VL_IN8(__PVT__p3_rstb_intfrx_clk,0,0);
        VL_IN8(__PVT__p3_RX_LINKACTIVEREQ,0,0);
        VL_OUT8(__PVT__p3_RX_LINKACTIVEACK,0,0);
        VL_IN8(__PVT__p3_RX_REQFLITPEND,0,0);
        VL_IN8(__PVT__p3_RX_REQFLITV,0,0);
        VL_OUT8(__PVT__p3_RX_REQLCRDV,0,0);
        VL_IN8(__PVT__p3_RX_RSPFLITPEND,0,0);
        VL_IN8(__PVT__p3_RX_RSPFLITV,0,0);
        VL_OUT8(__PVT__p3_RX_RSPLCRDV,0,0);
        VL_IN8(__PVT__p3_RX_DATFLITPEND,0,0);
        VL_IN8(__PVT__p3_RX_DATFLITV,0,0);
        VL_OUT8(__PVT__p3_RX_DATLCRDV,0,0);
        VL_OUT8(__PVT__p3_TX_LINKACTIVEREQ,0,0);
        VL_IN8(__PVT__p3_TX_LINKACTIVEACK,0,0);
        VL_OUT8(__PVT__p3_TX_SNPFLITPEND,0,0);
        VL_OUT8(__PVT__p3_TX_SNPFLITV,0,0);
        VL_IN8(__PVT__p3_TX_SNPLCRDV,0,0);
        VL_OUT8(__PVT__p3_TX_RSPFLITPEND,0,0);
        VL_OUT8(__PVT__p3_TX_RSPFLITV,0,0);
        VL_IN8(__PVT__p3_TX_RSPLCRDV,0,0);
        VL_OUT8(__PVT__p3_TX_DATFLITPEND,0,0);
        VL_OUT8(__PVT__p3_TX_DATFLITV,0,0);
        VL_IN8(__PVT__p3_TX_DATLCRDV,0,0);
        VL_OUT8(__PVT__p3_ic_TXSACTIVE,0,0);
        VL_IN8(__PVT__p3_ic_RXSACTIVE,0,0);
        VL_IN8(__PVT__p3_syscoreq,0,0);
    };
    struct {
        VL_OUT8(__PVT__p3_syscoack,0,0);
        VL_IN8(__PVT__p3_reg_syscoh,1,0);
        VL_IN8(__PVT__p1_intfrx_clk,0,0);
        VL_IN8(__PVT__p1_rstb_intfrx_clk,0,0);
        VL_IN8(__PVT__p1_RX_LINKACTIVEREQ,0,0);
        VL_OUT8(__PVT__p1_RX_LINKACTIVEACK,0,0);
        VL_IN8(__PVT__p1_RX_RSPFLITPEND,0,0);
        VL_IN8(__PVT__p1_RX_RSPFLITV,0,0);
        VL_OUT8(__PVT__p1_RX_RSPLCRDV,0,0);
        VL_IN8(__PVT__p1_RX_DATFLITPEND,0,0);
        VL_IN8(__PVT__p1_RX_DATFLITV,0,0);
        VL_OUT8(__PVT__p1_RX_DATLCRDV,0,0);
        VL_OUT8(__PVT__p1_TX_LINKACTIVEREQ,0,0);
        VL_IN8(__PVT__p1_TX_LINKACTIVEACK,0,0);
        VL_OUT8(__PVT__p1_TX_REQFLITPEND,0,0);
        VL_OUT8(__PVT__p1_TX_REQFLITV,0,0);
        VL_IN8(__PVT__p1_TX_REQLCRDV,0,0);
        VL_OUT8(__PVT__p1_TX_DATFLITPEND,0,0);
        VL_OUT8(__PVT__p1_TX_DATFLITV,0,0);
        VL_IN8(__PVT__p1_TX_DATLCRDV,0,0);
        VL_OUT8(__PVT__p1_ic_TXSACTIVE,0,0);
        VL_IN8(__PVT__p1_ic_RXSACTIVE,0,0);
        VL_IN8(__PVT__p0_intfrx_clk,0,0);
        VL_IN8(__PVT__p0_rstb_intfrx_clk,0,0);
        VL_IN8(__PVT__p0_RX_LINKACTIVEREQ,0,0);
        VL_OUT8(__PVT__p0_RX_LINKACTIVEACK,0,0);
        VL_IN8(__PVT__p0_RX_RSPFLITPEND,0,0);
        VL_IN8(__PVT__p0_RX_RSPFLITV,0,0);
        VL_OUT8(__PVT__p0_RX_RSPLCRDV,0,0);
        VL_IN8(__PVT__p0_RX_DATFLITPEND,0,0);
        VL_IN8(__PVT__p0_RX_DATFLITV,0,0);
        VL_OUT8(__PVT__p0_RX_DATLCRDV,0,0);
        VL_OUT8(__PVT__p0_TX_LINKACTIVEREQ,0,0);
        VL_IN8(__PVT__p0_TX_LINKACTIVEACK,0,0);
        VL_OUT8(__PVT__p0_TX_REQFLITPEND,0,0);
        VL_OUT8(__PVT__p0_TX_REQFLITV,0,0);
        VL_IN8(__PVT__p0_TX_REQLCRDV,0,0);
        VL_OUT8(__PVT__p0_TX_DATFLITPEND,0,0);
        VL_OUT8(__PVT__p0_TX_DATFLITV,0,0);
        VL_IN8(__PVT__p0_TX_DATLCRDV,0,0);
        VL_OUT8(__PVT__p0_ic_TXSACTIVE,0,0);
        VL_IN8(__PVT__p0_ic_RXSACTIVE,0,0);
        VL_IN8(__PVT__mycluster_id,7,0);
        VL_IN8(__PVT__xy_coord_all_hn_f,7,0);
        VL_IN8(__PVT__icx_txport_cfg,3,0);
        VL_IN8(__PVT__i_rden_csr_top_or_clus,0,0);
        VL_IN8(__PVT__i_wren_csr_top_or_clus,0,0);
        VL_IN8(__PVT__i_clus_csr_wstrb,3,0);
        VL_IN8(__PVT__i_csr_clk,0,0);
        VL_IN8(__PVT__i_csr_reset_n,0,0);
        CData/*0:0*/ __PVT__p2_rx_is_inactive;
        CData/*0:0*/ __PVT__p2_rx_activate_clk;
        CData/*0:0*/ __PVT__p2_tx_is_inactive;
        CData/*0:0*/ __PVT__p2_tx_activate_clk;
        CData/*0:0*/ __PVT__p3_rx_is_inactive;
        CData/*0:0*/ __PVT__p3_rx_activate_clk;
        CData/*0:0*/ __PVT__p3_tx_is_inactive;
        CData/*0:0*/ __PVT__p3_tx_activate_clk;
        CData/*0:0*/ __PVT__p1_rx_is_inactive;
        CData/*0:0*/ __PVT__p1_rx_activate_clk;
        CData/*0:0*/ __PVT__p1_tx_is_inactive;
        CData/*0:0*/ __PVT__p1_tx_activate_clk;
        CData/*0:0*/ __PVT__p0_rx_is_inactive;
        CData/*0:0*/ __PVT__p0_rx_activate_clk;
    };
    struct {
        CData/*0:0*/ __PVT__p0_tx_is_inactive;
        CData/*0:0*/ __PVT__p0_tx_activate_clk;
        CData/*0:0*/ __PVT__icn_rx_is_inactive;
        CData/*0:0*/ __PVT__icn_rx_activate_clk;
        CData/*0:0*/ __PVT__icn_tx_is_inactive;
        CData/*0:0*/ __PVT__icn_tx_activate_clk;
        CData/*0:0*/ __PVT__ics_rx_is_inactive;
        CData/*0:0*/ __PVT__ics_rx_activate_clk;
        CData/*0:0*/ __PVT__ics_tx_is_inactive;
        CData/*0:0*/ __PVT__ics_tx_activate_clk;
        CData/*0:0*/ __PVT__icw_rx_is_inactive;
        CData/*0:0*/ __PVT__icw_rx_activate_clk;
        CData/*0:0*/ __PVT__icw_tx_is_inactive;
        CData/*0:0*/ __PVT__icw_tx_activate_clk;
        CData/*0:0*/ __PVT__ice_rx_is_inactive;
        CData/*0:0*/ __PVT__ice_rx_activate_clk;
        CData/*0:0*/ __PVT__ice_tx_is_inactive;
        CData/*0:0*/ __PVT__ice_tx_activate_clk;
        CData/*0:0*/ __PVT__proc_port_reg_1_rx_is_inactive;
        CData/*0:0*/ __PVT__proc_port_reg_1_tx_is_inactive;
        CData/*3:0*/ __PVT__node_port_timeout_interrupt_vec;
        CData/*3:0*/ __PVT__node_port_timeout_recovery_successful_vec;
        CData/*3:0*/ __PVT__node_port_timeout_clear_timeout_interrupt_vec;
        CData/*3:0*/ __PVT__node_port_timeout_clear_recovery_interrupt_vec;
        CData/*3:0*/ __PVT__pp_intfc_clk;
        CData/*3:0*/ __PVT__rst_n_pp_intfc_clk;
        CData/*3:0*/ __PVT__pp_rx_is_inactive;
        CData/*3:0*/ __PVT__pp_tx_is_inactive;
        CData/*3:0*/ __PVT__activate_pp_rx;
        CData/*3:0*/ __PVT__activate_pp_tx;
        CData/*3:0*/ __PVT__pp_exists;
        CData/*3:0*/ __PVT__pp_rx_intfc_gclk;
        CData/*3:0*/ __PVT__pp_rx_ic_gclk;
        CData/*3:0*/ __PVT__pp_tx_intfc_gclk;
        CData/*3:0*/ __PVT__pp_tx_ic_gclk;
        CData/*3:0*/ __PVT__ic_intfc_clk;
        CData/*3:0*/ __PVT__rst_n_ic_intfc_clk;
        CData/*3:0*/ __PVT__ic_rx_is_inactive;
        CData/*3:0*/ __PVT__ic_tx_is_inactive;
        CData/*3:0*/ __PVT__activate_ic_rx;
        CData/*3:0*/ __PVT__activate_ic_tx;
        CData/*3:0*/ __PVT__ic_exists;
        CData/*3:0*/ __PVT__ic_rx_intfc_gclk;
        CData/*3:0*/ __PVT__ic_rx_ic_gclk;
        CData/*3:0*/ __PVT__ic_tx_intfc_gclk;
        CData/*3:0*/ __PVT__ic_tx_ic_gclk;
        CData/*0:0*/ __PVT__cc_intfc_gclk;
        CData/*0:0*/ __PVT__cc_exists;
        CData/*0:0*/ __PVT__cc_ic_gclk;
        CData/*0:0*/ __PVT__activate_cc_l3_or_mn;
        CData/*0:0*/ __PVT__cc_final_gclk;
        CData/*1:0*/ __PVT__cg_reg_ctrl_2;
        CData/*0:0*/ __PVT__activate_cc;
        CData/*0:0*/ __PVT__activate_l3;
        CData/*0:0*/ __PVT__cg_cc_intfrx_clk;
        CData/*0:0*/ __PVT__cg_cc_rstb_intfrx_clk;
        CData/*0:0*/ __PVT__cc_is_inactive_cg;
        CData/*0:0*/ __PVT__l3_port_is_inactive;
        CData/*0:0*/ __PVT__cc_clk;
        CData/*0:0*/ __PVT__rstb_cc_clk;
        CData/*0:0*/ __PVT__cc_RX_SNPFLITPEND;
        CData/*0:0*/ __PVT__cc_RX_SNPFLITV;
        CData/*0:0*/ __PVT__cc_RX_SNPFLIT_snp_or_req_bit;
        CData/*0:0*/ __PVT__cc_RX_SNPLCRDV;
    };
    struct {
        CData/*0:0*/ __PVT__cc_RX_RSPFLITPEND;
        CData/*0:0*/ __PVT__cc_RX_RSPFLITV;
        CData/*0:0*/ __PVT__cc_RX_RSPLCRDV;
        CData/*0:0*/ __PVT__cc_RX_DATFLITPEND;
        CData/*0:0*/ __PVT__cc_RX_DATFLITV;
        CData/*0:0*/ __PVT__cc_RX_DATLCRDV;
        CData/*0:0*/ __PVT__cc_TX_REQFLITPEND;
        CData/*0:0*/ __PVT__cc_TX_REQFLITV;
        CData/*0:0*/ __PVT__cc_TX_REQLCRDV;
        CData/*0:0*/ __PVT__cc_TX_RSPFLITPEND;
        CData/*0:0*/ __PVT__cc_TX_RSPFLITV;
        CData/*0:0*/ __PVT__cc_TX_RSPLCRDV;
        CData/*0:0*/ __PVT__cc_TX_DATFLITPEND;
        CData/*0:0*/ __PVT__cc_TX_DATFLITV;
        CData/*0:0*/ __PVT__cc_TX_DATLCRDV;
        CData/*0:0*/ __PVT__cc_reqflit_valid;
        CData/*0:0*/ __PVT__l3reqflit_fifo_full;
        CData/*0:0*/ __PVT__l3_wrdata_valid;
        CData/*0:0*/ __PVT__l3_drop_wrdata;
        CData/*0:0*/ __PVT__l3_wrdatabuf_hasroom;
        CData/*0:0*/ __PVT__L3_TX_REQFLITPEND;
        CData/*0:0*/ __PVT__L3_TX_REQFLITV;
        CData/*0:0*/ __PVT__L3_TX_REQFLIT_snp_or_req_bit;
        CData/*0:0*/ __PVT__L3_TX_REQLCRDV;
        CData/*0:0*/ __PVT__L3_RX_DATFLITPEND;
        CData/*0:0*/ __PVT__L3_RX_DATFLITV;
        CData/*0:0*/ __PVT__L3_RX_DATLCRDV;
        CData/*0:0*/ __PVT__L3_RX_RSPFLITPEND;
        CData/*0:0*/ __PVT__L3_RX_RSPFLITV;
        CData/*0:0*/ __PVT__L3_RX_RSPLCRDV;
        CData/*0:0*/ __PVT__L3_TX_DATFLITPEND;
        CData/*0:0*/ __PVT__L3_TX_DATFLITV;
        CData/*0:0*/ __PVT__L3_TX_DATLCRDV;
        CData/*0:0*/ __PVT__l3_rspvalid;
        CData/*0:0*/ __PVT__porthas_rspgnt_fromcc;
        CData/*0:0*/ __PVT__l3_datvalid;
        CData/*1:0*/ __PVT__l3_rddata_resperr;
        CData/*0:0*/ __PVT__porthas_datgnt_fromcc;
        CData/*0:0*/ __PVT__dirc_init_complete;
        CData/*0:0*/ __PVT__slc_init_complete;
        CData/*0:0*/ __Vcellinp__sig_node_porttop_rn_p2__i_clear_recovery_interrupt;
        CData/*0:0*/ __Vcellout__sig_node_porttop_rn_p2__o_timeout_recovery_successful;
        CData/*0:0*/ __Vcellout__sig_node_porttop_rn_p2__o_timeout_interrupt;
        CData/*0:0*/ __Vcellinp__sig_node_porttop_rn_p2__i_clear_timeout_interrupt;
        CData/*0:0*/ __Vcellinp__sig_node_porttop_rn_p2__tx_intfrx_gclk;
        CData/*0:0*/ __Vcellinp__sig_node_porttop_rn_p2__rx_intfrx_gclk;
        CData/*0:0*/ __Vcellinp__sig_node_porttop_rn_p2__tx_ic_gclk;
        CData/*0:0*/ __Vcellinp__sig_node_porttop_rn_p2__rx_ic_gclk;
        CData/*0:0*/ __Vcellinp__sig_node_porttop_rn_p3__i_clear_recovery_interrupt;
        CData/*0:0*/ __Vcellout__sig_node_porttop_rn_p3__o_timeout_recovery_successful;
        CData/*0:0*/ __Vcellout__sig_node_porttop_rn_p3__o_timeout_interrupt;
        CData/*0:0*/ __Vcellinp__sig_node_porttop_rn_p3__i_clear_timeout_interrupt;
        CData/*0:0*/ __Vcellinp__sig_node_porttop_rn_p3__tx_intfrx_gclk;
        CData/*0:0*/ __Vcellinp__sig_node_porttop_rn_p3__rx_intfrx_gclk;
        CData/*0:0*/ __Vcellinp__sig_node_porttop_rn_p3__tx_ic_gclk;
        CData/*0:0*/ __Vcellinp__sig_node_porttop_rn_p3__rx_ic_gclk;
        CData/*0:0*/ __Vcellinp__sig_node_porttop_sn_p1__i_clear_recovery_interrupt;
        CData/*0:0*/ __Vcellout__sig_node_porttop_sn_p1__o_timeout_recovery_successful;
        CData/*0:0*/ __Vcellout__sig_node_porttop_sn_p1__o_timeout_interrupt;
        CData/*0:0*/ __Vcellinp__sig_node_porttop_sn_p1__i_clear_timeout_interrupt;
        CData/*0:0*/ __Vcellinp__sig_node_porttop_sn_p1__tx_intfrx_gclk;
        CData/*0:0*/ __Vcellinp__sig_node_porttop_sn_p1__rx_intfrx_gclk;
        CData/*0:0*/ __Vcellinp__sig_node_porttop_sn_p1__tx_ic_gclk;
        CData/*0:0*/ __Vcellinp__sig_node_porttop_sn_p1__rx_ic_gclk;
    };
    struct {
        CData/*0:0*/ __Vcellinp__sig_node_porttop_sn_p0__i_clear_recovery_interrupt;
        CData/*0:0*/ __Vcellout__sig_node_porttop_sn_p0__o_timeout_recovery_successful;
        CData/*0:0*/ __Vcellout__sig_node_porttop_sn_p0__o_timeout_interrupt;
        CData/*0:0*/ __Vcellinp__sig_node_porttop_sn_p0__i_clear_timeout_interrupt;
        CData/*0:0*/ __Vcellinp__sig_node_porttop_sn_p0__tx_intfrx_gclk;
        CData/*0:0*/ __Vcellinp__sig_node_porttop_sn_p0__rx_intfrx_gclk;
        CData/*0:0*/ __Vcellinp__sig_node_porttop_sn_p0__tx_ic_gclk;
        CData/*0:0*/ __Vcellinp__sig_node_porttop_sn_p0__rx_ic_gclk;
        CData/*0:0*/ __PVT__cc_port_is_inactive;
        VL_IN16(__PVT__mn_node_id,10,0);
        SData/*9:0*/ __PVT__out_end_flit_reqf_vc0;
        SData/*9:0*/ __PVT__out_end_flit_rspf_vc0;
        SData/*9:0*/ __PVT__out_end_flit_datf_vc0;
        SData/*9:0*/ __PVT__out_valid_flit_datf_vc0;
        SData/*9:0*/ __PVT__out_valid_flit_reqf_vc0;
        SData/*9:0*/ __PVT__out_valid_flit_rspf_vc0;
        SData/*9:0*/ __PVT__out_end_flit_reqf_vc1;
        SData/*9:0*/ __PVT__out_end_flit_rspf_vc1;
        SData/*9:0*/ __PVT__out_end_flit_datf_vc1;
        SData/*9:0*/ __PVT__out_valid_flit_datf_vc1;
        SData/*9:0*/ __PVT__out_valid_flit_reqf_vc1;
        SData/*9:0*/ __PVT__out_valid_flit_rspf_vc1;
        SData/*11:0*/ __PVT__dbid_from_l3;
        SData/*12:0*/ __PVT__l3_rddata_txnid;
        VL_INW(__PVT__p2_RX_REQFLIT,150,0,5);
        VL_INW(__PVT__p2_RX_RSPFLIT,72,0,3);
        VL_INW(__PVT__p2_RX_DATFLIT,679,0,22);
        VL_OUTW(__PVT__p2_TX_SNPFLIT,107,0,4);
        VL_OUTW(__PVT__p2_TX_RSPFLIT,72,0,3);
        VL_OUTW(__PVT__p2_TX_DATFLIT,679,0,22);
        VL_INW(__PVT__p3_RX_REQFLIT,150,0,5);
        VL_INW(__PVT__p3_RX_RSPFLIT,72,0,3);
        VL_INW(__PVT__p3_RX_DATFLIT,679,0,22);
        VL_OUTW(__PVT__p3_TX_SNPFLIT,107,0,4);
        VL_OUTW(__PVT__p3_TX_RSPFLIT,72,0,3);
        VL_OUTW(__PVT__p3_TX_DATFLIT,679,0,22);
        VL_INW(__PVT__p1_RX_RSPFLIT,72,0,3);
        VL_INW(__PVT__p1_RX_DATFLIT,679,0,22);
        VL_OUTW(__PVT__p1_TX_REQFLIT,150,0,5);
        VL_OUTW(__PVT__p1_TX_DATFLIT,679,0,22);
        VL_INW(__PVT__p0_RX_RSPFLIT,72,0,3);
        VL_INW(__PVT__p0_RX_DATFLIT,679,0,22);
        VL_OUTW(__PVT__p0_TX_REQFLIT,150,0,5);
        VL_OUTW(__PVT__p0_TX_DATFLIT,679,0,22);
        VL_IN(__PVT__COH_RNF_Exist,21,0);
        VL_IN(__PVT__reg_cc_ctrl1,31,0);
        VL_INW(__PVT__COH_nodeid_all_rn,241,0,8);
        VL_IN(__PVT__xy_coord_all_pm,21,0);
        VL_IN(__PVT__cm_homeaddr_base_all_hn_f,27,0);
        VL_IN(__PVT__cm_homeaddr_limit_all_hn_f,28,0);
        VL_IN(__PVT__noncm_homeaddr_base_all_hn_f,27,0);
        VL_IN(__PVT__noncm_homeaddr_limit_all_hn_f,28,0);
        VL_OUT(__PVT__o_rd_csr_clus,31,0);
        VL_IN(__PVT__i_clus_csr_address,31,0);
        VL_IN(__PVT__i_clus_csr_wdata,31,0);
        VlWide<6>/*160:0*/ __PVT__cc_out_flit_reqf_vc0;
        VlWide<3>/*78:0*/ __PVT__cc_out_flit_rspf_vc0;
        VlWide<22>/*685:0*/ __PVT__cc_out_flit_datf_vc0;
        VlWide<6>/*160:0*/ __PVT__cc_out_flit_reqf_vc1;
        VlWide<3>/*78:0*/ __PVT__cc_out_flit_rspf_vc1;
        VlWide<22>/*685:0*/ __PVT__cc_out_flit_datf_vc1;
        VlWide<51>/*1609:0*/ __PVT__cc_in_flit_all_req_vc0;
        VlWide<51>/*1609:0*/ __PVT__cc_in_flit_all_req_vc1;
        VlWide<25>/*789:0*/ __PVT__cc_in_flit_all_rsp_vc0;
    };
    struct {
        VlWide<25>/*789:0*/ __PVT__cc_in_flit_all_rsp_vc1;
        VlWide<215>/*6859:0*/ __PVT__cc_in_flit_all_dat_vc0;
        VlWide<215>/*6859:0*/ __PVT__cc_in_flit_all_dat_vc1;
        VlWide<6>/*160:0*/ __PVT__l3_out_flit_reqf_vc0;
        VlWide<3>/*78:0*/ __PVT__l3_out_flit_rspf_vc0;
        VlWide<22>/*685:0*/ __PVT__l3_out_flit_datf_vc0;
        VlWide<6>/*160:0*/ __PVT__l3_out_flit_reqf_vc1;
        VlWide<3>/*78:0*/ __PVT__l3_out_flit_rspf_vc1;
        VlWide<22>/*685:0*/ __PVT__l3_out_flit_datf_vc1;
        VlWide<51>/*1609:0*/ __PVT__l3_in_flit_all_req_vc0;
        VlWide<51>/*1609:0*/ __PVT__l3_in_flit_all_req_vc1;
        VlWide<25>/*789:0*/ __PVT__l3_in_flit_all_rsp_vc0;
        VlWide<25>/*789:0*/ __PVT__l3_in_flit_all_rsp_vc1;
        VlWide<215>/*6859:0*/ __PVT__l3_in_flit_all_dat_vc0;
        VlWide<215>/*6859:0*/ __PVT__l3_in_flit_all_dat_vc1;
        VlWide<6>/*160:0*/ __PVT__p2_out_flit_reqf_vc0;
        VlWide<3>/*78:0*/ __PVT__p2_out_flit_rspf_vc0;
        VlWide<22>/*685:0*/ __PVT__p2_out_flit_datf_vc0;
        VlWide<6>/*160:0*/ __PVT__p2_out_flit_reqf_vc1;
        VlWide<3>/*78:0*/ __PVT__p2_out_flit_rspf_vc1;
        VlWide<22>/*685:0*/ __PVT__p2_out_flit_datf_vc1;
        VlWide<51>/*1609:0*/ __PVT__p2_in_flit_all_req_vc0;
        VlWide<51>/*1609:0*/ __PVT__p2_in_flit_all_req_vc1;
        VlWide<25>/*789:0*/ __PVT__p2_in_flit_all_rsp_vc0;
        VlWide<25>/*789:0*/ __PVT__p2_in_flit_all_rsp_vc1;
        VlWide<215>/*6859:0*/ __PVT__p2_in_flit_all_dat_vc0;
        VlWide<215>/*6859:0*/ __PVT__p2_in_flit_all_dat_vc1;
        VlWide<6>/*160:0*/ __PVT__p3_out_flit_reqf_vc0;
        VlWide<3>/*78:0*/ __PVT__p3_out_flit_rspf_vc0;
        VlWide<22>/*685:0*/ __PVT__p3_out_flit_datf_vc0;
        VlWide<6>/*160:0*/ __PVT__p3_out_flit_reqf_vc1;
        VlWide<3>/*78:0*/ __PVT__p3_out_flit_rspf_vc1;
        VlWide<22>/*685:0*/ __PVT__p3_out_flit_datf_vc1;
        VlWide<51>/*1609:0*/ __PVT__p3_in_flit_all_req_vc0;
        VlWide<51>/*1609:0*/ __PVT__p3_in_flit_all_req_vc1;
        VlWide<25>/*789:0*/ __PVT__p3_in_flit_all_rsp_vc0;
        VlWide<25>/*789:0*/ __PVT__p3_in_flit_all_rsp_vc1;
        VlWide<215>/*6859:0*/ __PVT__p3_in_flit_all_dat_vc0;
        VlWide<215>/*6859:0*/ __PVT__p3_in_flit_all_dat_vc1;
        VlWide<6>/*160:0*/ __PVT__p1_out_flit_reqf_vc0;
        VlWide<3>/*78:0*/ __PVT__p1_out_flit_rspf_vc0;
        VlWide<22>/*685:0*/ __PVT__p1_out_flit_datf_vc0;
        VlWide<6>/*160:0*/ __PVT__p1_out_flit_reqf_vc1;
        VlWide<3>/*78:0*/ __PVT__p1_out_flit_rspf_vc1;
        VlWide<22>/*685:0*/ __PVT__p1_out_flit_datf_vc1;
        VlWide<51>/*1609:0*/ __PVT__p1_in_flit_all_req_vc0;
        VlWide<51>/*1609:0*/ __PVT__p1_in_flit_all_req_vc1;
        VlWide<25>/*789:0*/ __PVT__p1_in_flit_all_rsp_vc0;
        VlWide<25>/*789:0*/ __PVT__p1_in_flit_all_rsp_vc1;
        VlWide<215>/*6859:0*/ __PVT__p1_in_flit_all_dat_vc0;
        VlWide<215>/*6859:0*/ __PVT__p1_in_flit_all_dat_vc1;
        VlWide<6>/*160:0*/ __PVT__p0_out_flit_reqf_vc0;
        VlWide<3>/*78:0*/ __PVT__p0_out_flit_rspf_vc0;
        VlWide<22>/*685:0*/ __PVT__p0_out_flit_datf_vc0;
        VlWide<6>/*160:0*/ __PVT__p0_out_flit_reqf_vc1;
        VlWide<3>/*78:0*/ __PVT__p0_out_flit_rspf_vc1;
        VlWide<22>/*685:0*/ __PVT__p0_out_flit_datf_vc1;
        VlWide<51>/*1609:0*/ __PVT__p0_in_flit_all_req_vc0;
        VlWide<51>/*1609:0*/ __PVT__p0_in_flit_all_req_vc1;
        VlWide<25>/*789:0*/ __PVT__p0_in_flit_all_rsp_vc0;
        VlWide<25>/*789:0*/ __PVT__p0_in_flit_all_rsp_vc1;
        VlWide<215>/*6859:0*/ __PVT__p0_in_flit_all_dat_vc0;
        VlWide<215>/*6859:0*/ __PVT__p0_in_flit_all_dat_vc1;
        VlWide<6>/*160:0*/ __PVT__icn_out_flit_reqf_vc0;
    };
    struct {
        VlWide<3>/*78:0*/ __PVT__icn_out_flit_rspf_vc0;
        VlWide<22>/*685:0*/ __PVT__icn_out_flit_datf_vc0;
        VlWide<6>/*160:0*/ __PVT__icn_out_flit_reqf_vc1;
        VlWide<3>/*78:0*/ __PVT__icn_out_flit_rspf_vc1;
        VlWide<22>/*685:0*/ __PVT__icn_out_flit_datf_vc1;
        VlWide<51>/*1609:0*/ __PVT__icn_in_flit_all_req_vc0;
        VlWide<51>/*1609:0*/ __PVT__icn_in_flit_all_req_vc1;
        VlWide<25>/*789:0*/ __PVT__icn_in_flit_all_rsp_vc0;
        VlWide<25>/*789:0*/ __PVT__icn_in_flit_all_rsp_vc1;
        VlWide<215>/*6859:0*/ __PVT__icn_in_flit_all_dat_vc0;
        VlWide<215>/*6859:0*/ __PVT__icn_in_flit_all_dat_vc1;
        VlWide<6>/*160:0*/ __PVT__ics_out_flit_reqf_vc0;
        VlWide<3>/*78:0*/ __PVT__ics_out_flit_rspf_vc0;
        VlWide<22>/*685:0*/ __PVT__ics_out_flit_datf_vc0;
        VlWide<6>/*160:0*/ __PVT__ics_out_flit_reqf_vc1;
        VlWide<3>/*78:0*/ __PVT__ics_out_flit_rspf_vc1;
        VlWide<22>/*685:0*/ __PVT__ics_out_flit_datf_vc1;
        VlWide<51>/*1609:0*/ __PVT__ics_in_flit_all_req_vc0;
        VlWide<51>/*1609:0*/ __PVT__ics_in_flit_all_req_vc1;
        VlWide<25>/*789:0*/ __PVT__ics_in_flit_all_rsp_vc0;
        VlWide<25>/*789:0*/ __PVT__ics_in_flit_all_rsp_vc1;
        VlWide<215>/*6859:0*/ __PVT__ics_in_flit_all_dat_vc0;
        VlWide<215>/*6859:0*/ __PVT__ics_in_flit_all_dat_vc1;
        VlWide<6>/*160:0*/ __PVT__icw_out_flit_reqf_vc0;
        VlWide<3>/*78:0*/ __PVT__icw_out_flit_rspf_vc0;
        VlWide<22>/*685:0*/ __PVT__icw_out_flit_datf_vc0;
        VlWide<6>/*160:0*/ __PVT__icw_out_flit_reqf_vc1;
        VlWide<3>/*78:0*/ __PVT__icw_out_flit_rspf_vc1;
        VlWide<22>/*685:0*/ __PVT__icw_out_flit_datf_vc1;
        VlWide<51>/*1609:0*/ __PVT__icw_in_flit_all_req_vc0;
        VlWide<51>/*1609:0*/ __PVT__icw_in_flit_all_req_vc1;
        VlWide<25>/*789:0*/ __PVT__icw_in_flit_all_rsp_vc0;
        VlWide<25>/*789:0*/ __PVT__icw_in_flit_all_rsp_vc1;
        VlWide<215>/*6859:0*/ __PVT__icw_in_flit_all_dat_vc0;
        VlWide<215>/*6859:0*/ __PVT__icw_in_flit_all_dat_vc1;
        VlWide<6>/*160:0*/ __PVT__ice_out_flit_reqf_vc0;
        VlWide<3>/*78:0*/ __PVT__ice_out_flit_rspf_vc0;
        VlWide<22>/*685:0*/ __PVT__ice_out_flit_datf_vc0;
        VlWide<6>/*160:0*/ __PVT__ice_out_flit_reqf_vc1;
        VlWide<3>/*78:0*/ __PVT__ice_out_flit_rspf_vc1;
        VlWide<22>/*685:0*/ __PVT__ice_out_flit_datf_vc1;
        VlWide<51>/*1609:0*/ __PVT__ice_in_flit_all_req_vc0;
        VlWide<51>/*1609:0*/ __PVT__ice_in_flit_all_req_vc1;
        VlWide<25>/*789:0*/ __PVT__ice_in_flit_all_rsp_vc0;
        VlWide<25>/*789:0*/ __PVT__ice_in_flit_all_rsp_vc1;
        VlWide<215>/*6859:0*/ __PVT__ice_in_flit_all_dat_vc0;
        VlWide<215>/*6859:0*/ __PVT__ice_in_flit_all_dat_vc1;
        IData/*27:0*/ __PVT__cm_homeaddr_base_all_hn_f_final;
        IData/*28:0*/ __PVT__cm_homeaddr_limit_all_hn_f_final;
        IData/*27:0*/ __PVT__noncm_homeaddr_base_all_hn_f_final;
        IData/*28:0*/ __PVT__noncm_homeaddr_limit_all_hn_f_final;
        IData/*31:0*/ __PVT__proc_port_reg_0_max_credits;
        IData/*31:0*/ __PVT__coherency_ctlr_reg_0_inactive_threshold;
        IData/*31:0*/ __PVT__coherency_ctlr_reg_1_b2b_resp_wait;
        IData/*31:0*/ __PVT__cg_reg_ctrl_1;
        VlWide<5>/*150:0*/ __PVT__cc_RX_SNPFLIT;
        VlWide<3>/*72:0*/ __PVT__cc_RX_RSPFLIT;
        VlWide<22>/*679:0*/ __PVT__cc_RX_DATFLIT;
        VlWide<5>/*150:0*/ __PVT__cc_TX_REQFLIT;
        VlWide<3>/*72:0*/ __PVT__cc_TX_RSPFLIT;
        VlWide<22>/*679:0*/ __PVT__cc_TX_DATFLIT;
        VlWide<5>/*153:0*/ __PVT__cc_reqflit;
        VlWide<16>/*511:0*/ __PVT__l3_wrdata;
        VlWide<5>/*150:0*/ __PVT__L3_TX_REQFLIT;
    };
    struct {
        VlWide<22>/*679:0*/ __PVT__L3_RX_DATFLIT;
        VlWide<3>/*72:0*/ __PVT__L3_RX_RSPFLIT;
        VlWide<22>/*679:0*/ __PVT__L3_TX_DATFLIT;
        VlWide<3>/*72:0*/ __PVT__l3_rspflit;
        VlWide<16>/*511:0*/ __PVT__l3_datflit;
        VlWide<5>/*151:0*/ __Vcellout__sig_chi_cc_top_0__ic_TX_SNPFLIT;
        VlWide<5>/*151:0*/ __Vcellout__sig_L3top_bypass_0__L3_TX_REQFLIT;
        VL_IN64(__PVT__cm_homeaddr_base_all_pm,55,0);
        VL_IN64(__PVT__cm_homeaddr_limit_all_pm,57,0);
        VL_IN64(__PVT__noncm_homeaddr_base_all_pm,55,0);
        VL_IN64(__PVT__noncm_homeaddr_limit_all_pm,57,0);
        QData/*55:0*/ __PVT__cm_homeaddr_base_all_pm_final;
        QData/*57:0*/ __PVT__cm_homeaddr_limit_all_pm_final;
        QData/*55:0*/ __PVT__noncm_homeaddr_base_all_pm_final;
        QData/*57:0*/ __PVT__noncm_homeaddr_limit_all_pm_final;
        QData/*63:0*/ __PVT__l3_wrbe;
        VlUnpacked<SData/*9:0*/, 10> __PVT__out_gnt_vec_req_vc0;
        VlUnpacked<SData/*9:0*/, 10> __PVT__out_gnt_vec_rsp_vc0;
        VlUnpacked<SData/*9:0*/, 10> __PVT__out_gnt_vec_dat_vc0;
        VlUnpacked<SData/*9:0*/, 10> __PVT__out_req_reqf_vc0;
        VlUnpacked<SData/*9:0*/, 10> __PVT__out_req_rspf_vc0;
        VlUnpacked<SData/*9:0*/, 10> __PVT__out_req_datf_vc0;
        VlUnpacked<SData/*9:0*/, 10> __PVT__out_gnt_vec_req_vc1;
        VlUnpacked<SData/*9:0*/, 10> __PVT__out_gnt_vec_rsp_vc1;
        VlUnpacked<SData/*9:0*/, 10> __PVT__out_gnt_vec_dat_vc1;
        VlUnpacked<SData/*9:0*/, 10> __PVT__out_req_reqf_vc1;
        VlUnpacked<SData/*9:0*/, 10> __PVT__out_req_rspf_vc1;
        VlUnpacked<SData/*9:0*/, 10> __PVT__out_req_datf_vc1;
    };

    // INTERNAL VARIABLES
    Vsig_topology_top__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vsig_topology_top_sig_cl0_clustercore__pi4(Vsig_topology_top__Syms* symsp, const char* v__name);
    ~Vsig_topology_top_sig_cl0_clustercore__pi4();
    VL_UNCOPYABLE(Vsig_topology_top_sig_cl0_clustercore__pi4);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
