// Verilated -*- SystemC -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vsig_topology_top.h for the primary calling header

#ifndef VERILATED_VSIG_TOPOLOGY_TOP_SIG_COHERENCY_CTRLR__PI14_H_
#define VERILATED_VSIG_TOPOLOGY_TOP_SIG_COHERENCY_CTRLR__PI14_H_  // guard

#include "systemc"
#include "verilated_sc.h"
#include "verilated.h"
class Vsig_topology_top_sig_countones;
class Vsig_topology_top_sig_fifo_synchclk_flop__FB6d;
class Vsig_topology_top_sig_fifo_synchclk_flop__FB9c;
class Vsig_topology_top_sig_fifo_synchclk_flop__pi33;
class Vsig_topology_top_sig_fifo_synchclk_flop__pi34;


class Vsig_topology_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vsig_topology_top_sig_coherency_ctrlr__pi14 final : public VerilatedModule {
  public:
    // CELLS
    Vsig_topology_top_sig_fifo_synchclk_flop__FB9c* __PVT__reqcmd_fifo_0;
    Vsig_topology_top_sig_fifo_synchclk_flop__pi33* __PVT__respcmd_fifo_0;
    Vsig_topology_top_sig_fifo_synchclk_flop__pi34* __PVT__drespcmd_fifo_0;
    Vsig_topology_top_sig_fifo_synchclk_flop__FB6d* __PVT__memrespcmd_fifo_0;
    Vsig_topology_top_sig_countones* __PVT__sig_countones_0;
    Vsig_topology_top_sig_countones* __PVT__sig_countones_post_rsp;
    Vsig_topology_top_sig_countones* __PVT__sig_countones_post_req;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(__PVT__cc_clk,0,0);
        VL_IN8(__PVT__cc_gclk,0,0);
        VL_IN8(__PVT__rstb_cc_clk,0,0);
        VL_IN8(__PVT__mycluster_id,7,0);
        VL_IN8(__PVT__reg_dwt_en,0,0);
        VL_IN8(__PVT__wren_reqcmdq,0,0);
        VL_OUT8(__PVT__fifofull_reqcmdq,0,0);
        VL_OUT8(__PVT__send_reqcrdt_update,0,0);
        VL_IN8(__PVT__wren_respcmdq,0,0);
        VL_OUT8(__PVT__send_respcrdt_update,0,0);
        VL_IN8(__PVT__wren_drespcmdq,0,0);
        VL_IN8(__PVT__wren_memrespcmdq,0,0);
        VL_OUT8(__PVT__wren_cmq_ph4,0,0);
        VL_IN8(__PVT__cmd_addr_ph3_has_matchingentry_incmq,0,0);
        VL_IN8(__PVT__block_fetch_cohc,0,0);
        VL_IN8(__PVT__cm_cmdvalid,0,0);
        VL_OUT8(__PVT__clr_cm_cmdvalid,0,0);
        VL_IN8(__PVT__cm_cmdvalid_evict,0,0);
        VL_OUT8(__PVT__clr_cm_cmdvalid_evict,0,0);
        VL_IN8(__PVT__en_blocking_reqcmdq,0,0);
        VL_OUT8(__PVT__rden_dircache_ph2,0,0);
        VL_IN8(__PVT__cachehit_ph3,0,0);
        VL_IN8(__PVT__fiforoom_atlst4_cmq,0,0);
        VL_IN8(__PVT__full_cmqfifo,0,0);
        VL_IN8(__PVT__cmqhas_1room,0,0);
        VL_IN8(__PVT__cmqhas_2room,0,0);
        VL_IN8(__PVT__cmqhas_3room,0,0);
        VL_OUT8(__PVT__rden_dircache_pre,0,0);
        VL_OUT8(__PVT__inpendingq_matches_collnq,0,0);
        VL_IN8(__PVT__wren_cache_cohc_or_dirc,0,0);
        VL_OUT8(__PVT__excl_load_reqv,0,0);
        VL_OUT8(__PVT__excl_load_lpid,4,0);
        VL_OUT8(__PVT__excl_load_size,2,0);
        VL_IN8(__PVT__buffer_full,0,0);
        VL_OUT8(__PVT__excl_store_reqv,1,0);
        VL_OUT8(__PVT__excl_store_lpid,4,0);
        VL_OUT8(__PVT__excl_store_size,2,0);
        VL_IN8(__PVT__excl_store_pass,0,0);
        VL_OUT8(__PVT__atom_res_update,0,0);
        VL_OUT8(__PVT__wren_snpreqfifo,0,0);
        VL_IN8(__PVT__full_snpreqfifo,0,0);
        VL_IN8(__PVT__room_atlst3_snpreqfifo,0,0);
        VL_OUT8(__PVT__wren_outcompfifo,0,0);
        VL_IN8(__PVT__full_outcompfifo,0,0);
        VL_IN8(__PVT__room_atlst3_outcompfifo,0,0);
        VL_OUT8(__PVT__respbuff_avail,5,0);
        VL_IN8(__PVT__allocate_respbuf_snpreq,0,0);
        VL_IN8(__PVT__allocate_respbuf_compdata,0,0);
        VL_IN8(__PVT__clr_collnreg_sending_ini_compdata,0,0);
        VL_IN8(__PVT__index_pendingq_clr_outstand_cmd_compdata,5,0);
        VL_IN8(__PVT__index_pendingq_clr_outstand_cmd_snpreq,5,0);
        VL_IN8(__PVT__avoid_clr_colln_snpreq,0,0);
        VL_IN8(__PVT__dmt_enable_all_pm_vec,0,0);
        VL_IN8(__PVT__wren_compbuff_num_snpreq_1st,0,0);
        VL_IN8(__PVT__wren_compbuff_num_snpreq_2nd,0,0);
        VL_IN8(__PVT__wren_compbuff_num_compdata_1st,0,0);
        VL_IN8(__PVT__wren_compbuff_num_compdata_2nd,0,0);
        VL_IN8(__PVT__en_compbuf_2nd_for_snpdata,0,0);
        VL_IN8(__PVT__outq_index,5,0);
        VL_IN8(__PVT__buffernum_available,4,0);
        VL_IN8(__PVT__index_outq_rcvdata,5,0);
        VL_OUT8(__PVT__compq_buff_to_rcvdatproc_1st,4,0);
        VL_OUT8(__PVT__compq_buff_to_rcvdatproc_2nd,4,0);
        VL_OUT8(__PVT__vld_compq_buff_to_rcvdatproc_2nd,0,0);
    };
    struct {
        VL_OUT8(__PVT__invalid_req_rcvdatproc,0,0);
        VL_OUT8(__PVT__vld_compbuf_2nd_for_snpdata,0,0);
        VL_IN8(__PVT__index_pendingq_compdata,5,0);
        VL_IN8(__PVT__clr_2nd_buffer,0,0);
        VL_IN8(__PVT__use_early_write_response,0,0);
        VL_OUT8(__PVT__cc_is_inactive,0,0);
        CData/*0:0*/ __PVT__full_reqcmdq;
        CData/*0:0*/ __PVT__empty_reqcmdq;
        CData/*0:0*/ __PVT__rddata_reqcmdq_addr_invalid;
        CData/*0:0*/ __PVT__gnt_reqcmdq;
        CData/*0:0*/ __PVT__gnt_collnq;
        CData/*0:0*/ __PVT__gnt_cmq;
        CData/*0:0*/ __PVT__cmdvalid_ph2_req;
        CData/*0:0*/ __PVT__cmdvalid_ph2_req_nxt;
        CData/*1:0*/ __PVT__cmdq_src_ph2_req;
        CData/*1:0*/ __PVT__cmdq_src_ph3_req;
        CData/*1:0*/ __PVT__cmdq_src_ph2_req_nxt;
        CData/*0:0*/ __PVT__cmdvalid_ph3_rsp;
        CData/*0:0*/ __PVT__cmdvalid_ph3_rsp_nxt;
        CData/*1:0*/ __PVT__cmdq_src_ph3_rsp;
        CData/*1:0*/ __PVT__cmdq_src_ph3_rsp_nxt;
        CData/*0:0*/ __PVT__cmdis_req_ph2;
        CData/*0:0*/ __PVT__cmdis_isatmo_ph2;
        CData/*0:0*/ __PVT__cmdis_req_ph2_nxt;
        CData/*0:0*/ __PVT__cmdis_resp_ph3_nxt;
        CData/*0:0*/ __PVT__cmdis_invalidate_ph2;
        CData/*0:0*/ __PVT__cmdis_invalidate_ph2_nxt;
        CData/*0:0*/ __PVT__cmdis_invalidate_ph3;
        CData/*0:0*/ __PVT__cmdis_invalidate_ph4;
        CData/*0:0*/ __PVT__cmdvalid_ph3_req_outstd;
        CData/*4:0*/ __PVT__outstand_req_atmo_rd_idx;
        CData/*0:0*/ __PVT__outstand_atmo_wr;
        CData/*0:0*/ __PVT__outstand_atmo_rd;
        CData/*0:0*/ __PVT__outstand_atmo;
        CData/*0:0*/ __PVT__outstand_atmo_rd_alloc_then_wr_clr;
        CData/*0:0*/ __PVT__outstand_atmo_rd_alloc_then_wr_clr_nxt;
        CData/*0:0*/ __PVT__cmd_isatmo_ph2;
        CData/*0:0*/ __PVT__cmd_isatmo_ph3;
        CData/*0:0*/ __PVT__cmd_isatmo_rd_ph2;
        CData/*0:0*/ __PVT__cmd_isatmo_rd_ph3;
        CData/*0:0*/ __PVT__cmd_isatmo_wr_ph2;
        CData/*0:0*/ __PVT__cmd_isatmo_wr_ph3;
        VlWide<5>/*159:0*/ __PVT__outstand_cmd_buffnum_1st;
        VlWide<5>/*159:0*/ __PVT__outstand_cmd_buffnum_1st_nxt;
        VlWide<5>/*159:0*/ __PVT__outstand_cmd_buffnum_2nd;
        VlWide<5>/*159:0*/ __PVT__outstand_cmd_buffnum_2nd_nxt;
        CData/*0:0*/ __PVT__outstand_cmdq_full;
        CData/*0:0*/ __PVT__excl_pass_ph4;
        CData/*0:0*/ __PVT__excl_pass_ph3;
        CData/*0:0*/ __PVT__req_is_excl_ld_ph3;
        CData/*0:0*/ __PVT__req_is_excl_str_nsnp_ph3;
        CData/*0:0*/ __PVT__req_is_excl_str_snp_ph3;
        CData/*0:0*/ __PVT__gnt_respcmdq;
        CData/*0:0*/ __PVT__full_respcmdq;
        CData/*0:0*/ __PVT__empty_respcmdq;
        CData/*0:0*/ __PVT__gnt_drespcmdq;
        CData/*0:0*/ __PVT__full_drespcmdq;
        CData/*0:0*/ __PVT__empty_drespcmdq;
        CData/*0:0*/ __PVT__gnt_memrespcmdq;
        CData/*0:0*/ __PVT__full_memrespcmdq;
        CData/*0:0*/ __PVT__empty_memrespcmdq;
        CData/*0:0*/ __PVT__req_cmq;
        CData/*0:0*/ __PVT__req_respcmdq;
        CData/*0:0*/ __PVT__req_drespcmdq;
    };
    struct {
        CData/*0:0*/ __PVT__req_reqcmdq;
        CData/*0:0*/ __PVT__req_memrespcmdq;
        CData/*0:0*/ __PVT__req_cmq_gated;
        CData/*0:0*/ __PVT__req_respcmdq_gated;
        CData/*0:0*/ __PVT__req_collnq_gated;
        CData/*0:0*/ __PVT__req_drespcmdq_gated;
        CData/*0:0*/ __PVT__req_reqcmdq_gated;
        CData/*0:0*/ __PVT__req_memrespcmdq_gated;
        CData/*4:0*/ __PVT__pshare_ph4;
        CData/*4:0*/ __PVT__pshare_forsnp_ph4;
        CData/*5:0*/ __PVT__respbuff_avail_nxt;
        CData/*0:0*/ __PVT__deallocate_respbuf_ph3_1st;
        CData/*0:0*/ __PVT__deallocate_respbuf_ph3_2nd;
        CData/*0:0*/ __PVT__wren_outcompfifo_resp;
        CData/*0:0*/ __PVT__wren_outcompfifo_prelastresp;
        CData/*0:0*/ __PVT__wren_outcompfifo_retry;
        CData/*0:0*/ __PVT__wren_outcompfifo_atom;
        CData/*0:0*/ __PVT__wren_outcompfifo_compack;
        CData/*0:0*/ __PVT__wren_outcompfifo_wr_all;
        CData/*0:0*/ __PVT__orig_wr_evict_full_ph3;
        CData/*0:0*/ __PVT__cmdvalid_ph3_req;
        CData/*0:0*/ __PVT__cmdvalid_ph3_req_nxt;
        CData/*5:0*/ __PVT__index_statusreg_ph3_nxt;
        CData/*5:0*/ __PVT__index_statusreg_ph3;
        CData/*5:0*/ __PVT__index_statusreg_ph4;
        CData/*0:0*/ __PVT__cmdis_req_ph3;
        CData/*0:0*/ __PVT__cmdis_resp_ph3;
        CData/*5:0*/ __PVT__wrindex_req_ph3;
        CData/*0:0*/ __PVT__cmdq_src0_CompDBIDResp_ph3;
        CData/*0:0*/ __PVT__cmdq_src0_DBIDResp_ph3;
        CData/*0:0*/ __PVT__cmdq_src0_CompAckResp_ph3;
        CData/*0:0*/ __PVT__cmdq_src0_Comp_ph3;
        CData/*0:0*/ __PVT__cmdq_src0_RetryAck_ph3;
        CData/*0:0*/ __PVT__cmdq_src0_PCrdGrant_ph3;
        CData/*0:0*/ __PVT__cmdq_src0_CompCMO_ph3;
        CData/*0:0*/ __PVT__cmdvalid_ph4_req;
        CData/*0:0*/ __PVT__cmdvalid_ph4_rsp;
        CData/*0:0*/ __PVT__cmdis_req_ph4;
        CData/*0:0*/ __PVT__cmdis_resp_ph4;
        CData/*5:0*/ __PVT__wrindex_req_ph4;
        CData/*4:0*/ __PVT__orig_pshare_cnt_ph4;
        CData/*2:0*/ __PVT__req_cache_st_ph3;
        CData/*6:0*/ __PVT__ownerp_id_ph3;
        CData/*2:0*/ __PVT__req_cache_st_ph2;
        CData/*6:0*/ __PVT__ownerp_id_ph2;
        CData/*2:0*/ __PVT__req_src_pid_ph3;
        CData/*2:0*/ __PVT__resp_outcompdata_req_ph3;
        CData/*0:0*/ __PVT__reqid_matches_ownerpid_ph3;
        CData/*7:0*/ __PVT__req_src_clstid_ph3;
        CData/*5:0*/ __PVT__pendingq_index_resp_ph3;
        CData/*0:0*/ __PVT__reqid_matches_ownerpid_ph4;
        CData/*0:0*/ __PVT__req_is_anyrd_ph3;
        CData/*0:0*/ __PVT__req_is_anywr_ph3;
        CData/*0:0*/ __PVT__snpattr_req_ph3;
        CData/*2:0*/ __PVT__req_atmo_ph3;
        CData/*2:0*/ __PVT__req_atmo_ph4;
        CData/*0:0*/ __PVT__itis_stage2_atmo_ph3;
        CData/*0:0*/ __PVT__itis_stage2_atmo_read_nosnoop_ph3;
        CData/*0:0*/ __PVT__itis_stage2_atmo_read_nosnoop_req_ph3;
        CData/*0:0*/ __PVT__itis_stage2_atmo_read_nosnoop_rsp_ph3;
        CData/*0:0*/ __PVT__itis_stage2_atmo_rsp_ptl_ph3;
        CData/*0:0*/ __PVT__itis_stage2_atmo_rsp_ph3;
        CData/*0:0*/ __PVT__itis_stage2_atmo_fetch_txndata_ph3;
        CData/*0:0*/ __PVT__itis_stage2_atmo_complete_ph3;
    };
    struct {
        CData/*0:0*/ __PVT__req_is_read_ph3;
        CData/*0:0*/ __PVT__req_is_anydct_ph3;
        CData/*0:0*/ __PVT__req_is_anydwt_ph3;
        CData/*0:0*/ __PVT__dn_sm_req_ph3;
        CData/*0:0*/ __PVT__req_is_evict_ph3;
        CData/*0:0*/ __PVT__req_is_atom_ph3;
        CData/*0:0*/ __PVT__req_is_rdnosnp_ph3;
        CData/*0:0*/ __PVT__req_is_read_o_ph3;
        CData/*0:0*/ __PVT__req_is_read_c_ph3;
        CData/*0:0*/ __PVT__req_is_read_s_ph3;
        CData/*0:0*/ __PVT__req_is_read_u_ph3;
        CData/*0:0*/ __PVT__req_is_read_notsd_ph3;
        CData/*0:0*/ __PVT__req_is_makeread_u_ph3;
        CData/*0:0*/ __PVT__req_is_read_pu_ph3;
        CData/*0:0*/ __PVT__req_is_clean_u_ph3;
        CData/*0:0*/ __PVT__req_is_clean_s_ph3;
        CData/*0:0*/ __PVT__req_is_clean_i_ph3;
        CData/*0:0*/ __PVT__req_is_make_u_ph3;
        CData/*0:0*/ __PVT__req_is_make_i_ph3;
        CData/*0:0*/ __PVT__req_is_clean_si_ph3;
        CData/*0:0*/ __PVT__req_is_wrnosnpfull_ph3;
        CData/*0:0*/ __PVT__req_is_wrnosnpptl_ph3;
        CData/*0:0*/ __PVT__req_is_wrbackptl_ph3;
        CData/*0:0*/ __PVT__req_is_wruniqueptl_ph3;
        CData/*0:0*/ __PVT__req_is_wruniquefl_ph3;
        CData/*0:0*/ __PVT__req_is_wrunique_ph3;
        CData/*0:0*/ __PVT__req_is_wrnosnpzero_ph3;
        CData/*0:0*/ __PVT__req_is_wruniquezero_ph3;
        CData/*0:0*/ __PVT__dataless_xfrdata_tomem_ph3;
        CData/*0:0*/ __PVT__snoopable_cmo_sendresp_req_ph3;
        CData/*0:0*/ __PVT__req_is_wrnosnpfl_clean_i_ph3;
        CData/*0:0*/ __PVT__req_is_wrnosnpfl_clean_s_ph3;
        CData/*0:0*/ __PVT__req_is_wrnosnpptl_clean_i_ph3;
        CData/*0:0*/ __PVT__req_is_wrnosnpptl_clean_s_ph3;
        CData/*0:0*/ __PVT__req_is_wruniquefl_clean_s_ph3;
        CData/*0:0*/ __PVT__req_is_wruniqueptl_clean_s_ph3;
        CData/*0:0*/ __PVT__req_is_wrbackfl_clean_i_ph3;
        CData/*0:0*/ __PVT__req_is_wrbackfl_clean_s_ph3;
        CData/*0:0*/ __PVT__req_is_wrcleanfl_clean_s_ph3;
        CData/*0:0*/ __PVT__req_is_writecmo_ph3;
        CData/*0:0*/ __PVT__req_is_writefull_clean_i_ph3;
        CData/*0:0*/ __PVT__req_is_writefull_clean_s_ph3;
        CData/*0:0*/ __PVT__req_is_writenosnpptl_clean_si_ph3;
        CData/*0:0*/ __PVT__req_is_writenosnp_clean_si_ph3;
        CData/*0:0*/ __PVT__dataless_xfrdata_tomem_ph4;
        CData/*0:0*/ __PVT__req_read_oc_ph3;
        CData/*0:0*/ __PVT__req_read_oc_notsd_in_ucudsd_ph3;
        CData/*0:0*/ __PVT__itis_lastresp_ph3_nonwr;
        CData/*0:0*/ __PVT__itis_lastresp_atom_ph3;
        CData/*0:0*/ __PVT__itis_prelastresp_dataless_xfr_tomem_ph3;
        CData/*0:0*/ __PVT__itis_lastresp_dataless_xfr_tomem_ph3;
        CData/*0:0*/ __PVT__itis_lastresp_comp_ph3_wr_nosnp;
        CData/*0:0*/ __PVT__itis_prelastresp_comp_is_last_ph3_wr_nosnp_full;
        CData/*0:0*/ __PVT__itis_prelastresp_comp_is_last_ph3_wr_nosnp_ptl;
        CData/*0:0*/ __PVT__itis_prelastresp_comp_is_last_ph3_wr_nosnp;
        CData/*0:0*/ __PVT__itis_prelastresp_without_comp_ph3_wr_nosnp_full;
        CData/*0:0*/ __PVT__itis_prelastresp_without_comp_ph3_wr_nosnp_ptl;
        CData/*0:0*/ __PVT__itis_prelastresp_without_comp_ph3_wr_nosnp_zero;
        CData/*0:0*/ __PVT__itis_lastresp_comp_is_not_last_ph3_wr_nosnp_full;
        CData/*0:0*/ __PVT__itis_lastresp_comp_is_not_last_ph3_wr_nosnp_ptl;
        CData/*0:0*/ __PVT__itis_lastresp_comp_is_not_last_ph3_wr_nosnp_zero;
        CData/*0:0*/ __PVT__itis_lastresp_comp_is_not_last_ph3_wr_nosnp;
        CData/*0:0*/ __PVT__itis_lastresp_compdbidresp_ph3_wr_nosnp_full;
        CData/*0:0*/ __PVT__itis_lastresp_compdbidresp_ph3_wr_nosnp_ptl;
    };
    struct {
        CData/*0:0*/ __PVT__itis_lastresp_compdbidresp_ph3_wr_nosnp_zero;
        CData/*0:0*/ __PVT__itis_lastresp_compdbidresp_ph3_wr_nosnp;
        CData/*0:0*/ __PVT__itis_prelastresp_ph3_wr_nosnp;
        CData/*0:0*/ __PVT__itis_wrnosnpptl_send_wr_data_ph3;
        CData/*0:0*/ __PVT__itis_wrnosnpfull_send_wr_data_ph3;
        CData/*0:0*/ __PVT__itis_wrnosnp_send_wr_data_ph3;
        CData/*0:0*/ __PVT__pcrdgrant_match;
        CData/*0:0*/ __PVT__retryack_match;
        CData/*0:0*/ __PVT__itis_req_retry_pcrdmatch_ph3;
        CData/*4:0*/ __PVT__retry_shared_txnid;
        CData/*4:0*/ __PVT__muxed_id;
        CData/*0:0*/ __PVT__itis_lastresp_ph3_wr_cb;
        CData/*0:0*/ __PVT__itis_lastresp_ph3_wr_uniq_fl;
        CData/*0:0*/ __PVT__it_maybe_lastresp_ph3_wr_uniq_ptl;
        CData/*0:0*/ __PVT__itis_lastresp_ph3_wr_uniq_ptl;
        CData/*0:0*/ __PVT__itis_lastresp_ph3_wr_uniq_zero;
        CData/*0:0*/ __PVT__itis_lastresp_ph3_wr_all;
        CData/*0:0*/ __PVT__itis_lastresp_ph3_wr_invalid_addr;
        CData/*0:0*/ __PVT__itis_lastresp_nonsnp_excl_store_fail_ph3;
        CData/*0:0*/ __PVT__drop_write_data_to_slc;
        CData/*0:0*/ __PVT__itis_lastresp_ph3_wr_snp;
        CData/*4:0*/ __PVT__ic_resp_cnt_ph3_from_respreg;
        CData/*4:0*/ __PVT__ic_resp_cnt_ph3_from_reqreg;
        CData/*4:0*/ __PVT__ic_resp_cnt_ph3;
        CData/*0:0*/ __PVT__first_resp_ph3;
        CData/*0:0*/ __PVT__new_first_resp_ph4_nxt;
        CData/*1:0*/ __PVT__new_first_RespErr_ph4_nxt;
        CData/*1:0*/ __PVT__first_RespErr_ph3;
        CData/*1:0*/ __PVT__RespErr_ph3;
        CData/*1:0*/ __PVT__resperr_req_ph3;
        CData/*1:0*/ __PVT__cmd_ph3_dat_resperr;
        CData/*1:0*/ __PVT__final_compcmo_resperr_ph3;
        CData/*1:0*/ __PVT__compcmo_resperr_ph3;
        CData/*1:0*/ __PVT__new_compcmo_resperr_ph4_nxt;
        CData/*0:0*/ __PVT__mmem_resp_cnt_ph3;
        CData/*0:0*/ __PVT__origreq_expcompack_bit_resp_ph3;
        CData/*0:0*/ __PVT__origreq_reqid_matches_ownerpid_ph3;
        CData/*0:0*/ __PVT__origreq_reqid_matches_sharevec_ph3;
        CData/*2:0*/ __PVT__cmd_ph4_dat_resp_write_data_nxt;
        CData/*4:0*/ __PVT__new_snpresp_cnt_resp_ph4_nxt;
        CData/*0:0*/ __PVT__new_mmemresp_cnt_resp_ph4_nxt;
        CData/*1:0*/ __PVT__new_wrdata_cnt_resp_ph4_nxt;
        CData/*1:0*/ __PVT__new_compdbid_cnt_ph4_nxt;
        CData/*0:0*/ __PVT__new_dbid_cnt_ph4_nxt;
        CData/*0:0*/ __PVT__new_got_compack_ph4_nxt;
        CData/*4:0*/ __PVT__new_compfifo_index_mm_ph4_nxt;
        CData/*3:0*/ __PVT__cmd_ph4_dat_opcode_nxt;
        CData/*0:0*/ __PVT__new_last_read_snp_sent_ph4_nxt;
        CData/*4:0*/ __PVT__new_compfifo_index_ic_data_ph4_nxt;
        CData/*4:0*/ __PVT__new_compfifo_index_ic_ph4_nxt;
        CData/*2:0*/ __PVT__new_respfield_ic_src2or4_ph4_nxt;
        CData/*0:0*/ __PVT__new_gotresp_earlier_ic_ph4_nxt;
        CData/*0:0*/ __PVT__new_gotwrdata_earlier_ic_ph4_nxt;
        CData/*0:0*/ __PVT__new_got_snpdata_earlier_ic_ph4_nxt;
        CData/*0:0*/ __PVT__new_gotptldata_earlier_ic_ph4_nxt;
        CData/*3:0*/ __PVT__new_pcrdtype_from_mem_ph4_nxt;
        CData/*0:0*/ __PVT__new_pkt_already_forwarded_snp_ph4_nxt;
        CData/*0:0*/ __PVT__new_pkt_already_forwarded_mem_ph4_nxt;
        CData/*0:0*/ __PVT__new_was_prelastresp_read_snp_ph4_nxt;
        CData/*0:0*/ __PVT__new_was_prelastresp_wr_uniq_ptl_ph4_nxt;
        CData/*0:0*/ __PVT__new_was_lastresp_dataless_snpdataptl_ph4_nxt;
        CData/*0:0*/ __PVT__was_lastresp_dataless_snpdataptl_ph3;
        CData/*0:0*/ __PVT__was_prelastresp_wr_uniq_ptl_ph3;
        CData/*0:0*/ __PVT__was_prelastresp_read_snp_ph3;
    };
    struct {
        CData/*0:0*/ __PVT__itis_prelastresp_check_cacheline_ph3_cmo;
        CData/*0:0*/ __PVT__was_prelastresp_check_cacheline_ph3_cmo;
        CData/*0:0*/ __PVT__was_prelastresp_check_cacheline_ph4_cmo_nxt;
        CData/*0:0*/ __PVT__itis_prelastresp_write_compdbid_ph3_cmo;
        CData/*0:0*/ __PVT__was_prelastresp_write_compdbid_ph3_cmo;
        CData/*0:0*/ __PVT__was_prelastresp_write_compdbid_ph4_cmo_nxt;
        CData/*0:0*/ __PVT__itis_prelastresp_write_dbid_ph3_cmo;
        CData/*0:0*/ __PVT__was_prelastresp_write_dbid_ph3_cmo;
        CData/*0:0*/ __PVT__was_prelastresp_write_dbid_ph4_cmo_nxt;
        CData/*0:0*/ __PVT__itis_prelastresp_write_comp_ph3_cmo;
        CData/*0:0*/ __PVT__was_prelastresp_write_comp_ph3_cmo;
        CData/*0:0*/ __PVT__was_prelastresp_write_comp_ph4_cmo_nxt;
        CData/*0:0*/ __PVT__itis_lastresp_ph3_cmo;
        CData/*0:0*/ __PVT__itis_prelastresp_before_sending_wrreq_ph3_wrcmo;
        CData/*0:0*/ __PVT__was_prelastresp_before_sending_wrreq_ph3_wrcmo;
        CData/*0:0*/ __PVT__was_prelastresp_before_sending_wrreq_ph4_wrcmo_nxt;
        CData/*0:0*/ __PVT__itis_prelastresp_before_sending_cacheable_wrdat_ph3_wrcmo;
        CData/*0:0*/ __PVT__was_prelastresp_before_sending_cacheable_wrdat_ph3_wrcmo;
        CData/*0:0*/ __PVT__was_prelastresp_before_sending_cacheable_wrdat_ph4_wrcmo_nxt;
        CData/*0:0*/ __PVT__itis_prelastresp_before_sending_noncachealbe_wrdat_ph3_wrcmo;
        CData/*0:0*/ __PVT__was_prelastresp_before_sending_noncachealbe_wrdat_ph3_wrcmo;
        CData/*0:0*/ __PVT__was_prelastresp_before_sending_noncachealbe_wrdat_ph4_wrcmo_nxt;
        CData/*0:0*/ __PVT__itis_lastresp_ph3_wrcmo;
        CData/*0:0*/ __PVT__has_sent_comp_ph3_wrcmo;
        CData/*0:0*/ __PVT__has_sent_comp_ph4_wrcmo_nxt;
        CData/*0:0*/ __PVT__send_comp_wrcmo;
        CData/*0:0*/ __PVT__has_sent_compcmo_ph3_wrcmo;
        CData/*0:0*/ __PVT__has_sent_compcmo_ph4_wrcmo_nxt;
        CData/*0:0*/ __PVT__send_compcmo_wrcmo;
        CData/*2:0*/ __PVT__snp_resp_stored_ph3;
        CData/*2:0*/ __PVT__cmd_ph4_snp_resp_nxt;
        CData/*0:0*/ __PVT__got_mem_data_earlier_ph3;
        CData/*0:0*/ __PVT__new_got_mem_data_earlier_ph4_nxt;
        CData/*3:0*/ __PVT__dat_opcode_write_data_ph3;
        CData/*2:0*/ __PVT__dat_resp_write_data_ph3;
        CData/*4:0*/ __PVT__compfifo_index_mm_ph3;
        CData/*4:0*/ __PVT__compfifo_index_ic_data_ph3;
        CData/*4:0*/ __PVT__compfifo_index_ic_ph3;
        CData/*2:0*/ __PVT__respfield_ic_src2or4_ph3;
        CData/*0:0*/ __PVT__gotwrdata_earlier_ic_ph3;
        CData/*0:0*/ __PVT__got_snpdata_earlier_ic_ph3;
        CData/*0:0*/ __PVT__gotptldata_earlier_ic_ph3;
        CData/*0:0*/ __PVT__pkt_already_forwarded_snp_ph3;
        CData/*0:0*/ __PVT__pkt_already_forwarded_mem_ph3;
        CData/*0:0*/ __PVT__gotresp_earlier_ic_ph3;
        CData/*0:0*/ __PVT__origreq_got_mem_data;
        CData/*0:0*/ __PVT__origreq_got_snpresp_ic;
        CData/*0:0*/ __PVT__origreq_got_snpdata_ic;
        CData/*0:0*/ __PVT__origreq_got_snpptldata_ic;
        CData/*0:0*/ __PVT__origreq_got_copybackwrdata_invalid;
        CData/*1:0*/ __PVT__origreq_ccid_ph3;
        CData/*3:0*/ __PVT__origreq_qos_ph3;
        CData/*2:0*/ __PVT__origreq_size_ph3;
        CData/*0:0*/ __PVT__origreq_invalid_addr;
        CData/*0:0*/ __PVT__origreq_excl_ph3;
        CData/*0:0*/ __PVT__origreq_ns_ph3;
        CData/*3:0*/ __PVT__origreq_memattr_ph3;
        CData/*0:0*/ __PVT__origreq_excl_pass_ph3;
        CData/*4:0*/ __PVT__origreq_lpid_ph3;
        CData/*2:0*/ __PVT__resp_outcompdata_resp;
        CData/*4:0*/ __PVT__outcompfifo_index;
        CData/*4:0*/ __PVT__outcompfifo_index_2nd;
        CData/*0:0*/ __PVT__origreq_need_dataxfr_toic;
        CData/*0:0*/ __PVT__origreq_need_dataxfr_tomm;
    };
    struct {
        CData/*0:0*/ __PVT__origreq_mayneed_dataxfr_tomm;
        CData/*0:0*/ __PVT__origreq_no_dataxfr;
        CData/*0:0*/ __PVT__read_notsd_has_data_to_mem;
        CData/*0:0*/ __PVT__pd_bit_ph3;
        CData/*0:0*/ __PVT__pkt_forwarded_bit_snp_ph3;
        CData/*0:0*/ __PVT__pkt_forwarded_bit_mem_ph3;
        CData/*0:0*/ __PVT__origreq_invalidate_ph3;
        CData/*6:0*/ __PVT__origreq_opcode_ph3;
        CData/*2:0*/ __PVT__orig_cachest_ph3;
        CData/*0:0*/ __PVT__orig_cachest_dirty_ph3;
        CData/*0:0*/ __PVT__orig_cachest_inv_ph3;
        CData/*0:0*/ __PVT__orig_cachest_uc_ph3;
        CData/*0:0*/ __PVT__orig_cachest_ud_ph3;
        CData/*0:0*/ __PVT__orig_cachest_sc_ph3;
        CData/*0:0*/ __PVT__orig_cachest_sd_ph3;
        CData/*0:0*/ __PVT__opcode_any_snoop_response_ph3;
        CData/*0:0*/ __PVT__opcode_snprespdata_ph3;
        CData/*0:0*/ __PVT__cmd_ph3_pkt_forwarded_bit98;
        CData/*0:0*/ __PVT__opcode_snprespptldata_ph3;
        CData/*0:0*/ __PVT__opcode_compack_resp_ph3;
        CData/*0:0*/ __PVT__opcode_snprespdata_ptldata_ph3;
        CData/*0:0*/ __PVT__opcode_readreceipt_ph3;
        CData/*0:0*/ __PVT__opcode_snprespdatafwd_ph3;
        CData/*0:0*/ __PVT__cmdq_src0_SnpResp_ph3;
        CData/*0:0*/ __PVT__cmdq_src0_SnpRespFwd_ph3;
        CData/*0:0*/ __PVT__cmdq_src0_ph3;
        CData/*0:0*/ __PVT__cmdq_src1_ph3;
        CData/*0:0*/ __PVT__cmdq_src2_ph3;
        CData/*0:0*/ __PVT__cmdq_src0snpresp_or_src2_ph3;
        CData/*0:0*/ __PVT__orig_read_o_ph3;
        CData/*0:0*/ __PVT__orig_read_c_ph3;
        CData/*0:0*/ __PVT__orig_read_s_ph3;
        CData/*0:0*/ __PVT__orig_read_u_ph3;
        CData/*0:0*/ __PVT__orig_read_nosnp_ph3;
        CData/*0:0*/ __PVT__orig_read_notsd_ph3;
        CData/*0:0*/ __PVT__orig_makeread_u_ph3;
        CData/*0:0*/ __PVT__orig_read_pu_ph3;
        CData/*0:0*/ __PVT__orig_clean_u_ph3;
        CData/*0:0*/ __PVT__orig_clean_s_ph3;
        CData/*0:0*/ __PVT__orig_clean_i_ph3;
        CData/*0:0*/ __PVT__orig_make_u_ph3;
        CData/*0:0*/ __PVT__orig_make_i_ph3;
        CData/*0:0*/ __PVT__orig_req_cmo_ph3;
        CData/*0:0*/ __PVT__orig_req_wr_snp_ph3;
        CData/*0:0*/ __PVT__orig_req_wr_nosnp_full_ph3;
        CData/*0:0*/ __PVT__orig_req_wr_nosnp_ptl_ph3;
        CData/*0:0*/ __PVT__orig_req_wr_nosnp_zero_ph3;
        CData/*0:0*/ __PVT__orig_req_wr_nosnp_ph3;
        CData/*0:0*/ __PVT__orig_req_wr_ph3;
        CData/*0:0*/ __PVT__orig_req_wrback_wrcln_ph3;
        CData/*0:0*/ __PVT__orig_req_wruniq_full_ph3;
        CData/*0:0*/ __PVT__orig_req_wruniq_ptl_ph3;
        CData/*0:0*/ __PVT__orig_req_wruniq_zero_ph3;
        CData/*0:0*/ __PVT__orig_req_wr_cb_ph3;
        CData/*0:0*/ __PVT__orig_req_read_ocsu_notsd_pu_ph3;
        CData/*0:0*/ __PVT__orig_req_atom_ph3;
        CData/*0:0*/ __PVT__orig_req_wrnosnpfl_clean_i_ph3;
        CData/*0:0*/ __PVT__orig_req_wrnosnpfl_clean_s_ph3;
        CData/*0:0*/ __PVT__orig_req_wrnosnpptl_clean_i_ph3;
        CData/*0:0*/ __PVT__orig_req_wrnosnpptl_clean_s_ph3;
        CData/*0:0*/ __PVT__orig_req_wruniquefl_clean_s_ph3;
        CData/*0:0*/ __PVT__orig_req_wruniqueptl_clean_s_ph3;
        CData/*0:0*/ __PVT__orig_req_wrbackfl_clean_i_ph3;
        CData/*0:0*/ __PVT__orig_req_wrbackfl_clean_s_ph3;
    };
    struct {
        CData/*0:0*/ __PVT__orig_req_wrcleanfl_clean_s_ph3;
        CData/*0:0*/ __PVT__orig_req_writefull_cmo_ph3;
        CData/*0:0*/ __PVT__orig_req_writenosnp_cmo_ph3;
        CData/*0:0*/ __PVT__orig_req_writecopyback_cmo_ph3;
        CData/*0:0*/ __PVT__orig_req_write_cmo_ph3;
        CData/*5:0*/ __PVT__cmd_ph4_23_18_rsp;
        CData/*5:0*/ __PVT__cmd_ph4_23_18_rsp_nxt;
        CData/*5:0*/ __PVT__cmd_ph5_23_18_rsp;
        CData/*5:0*/ __PVT__cmd_ph4_23_18_req;
        CData/*5:0*/ __PVT__cmd_ph4_23_18_req_nxt;
        CData/*5:0*/ __PVT__cmd_ph5_23_18_req;
        CData/*5:0*/ __PVT__cmd_ph6_23_18_req;
        CData/*4:0*/ __PVT__pshare_cnt_ph5_rsp;
        CData/*4:0*/ __PVT__pshare_cnt_ph6_rsp;
        CData/*6:0*/ __PVT__ownerp_id_ph6_rsp;
        CData/*6:0*/ __PVT__ownerp_id_ph6_rsp_nxt;
        CData/*4:0*/ __PVT__pshare_cnt_ph5_req;
        CData/*4:0*/ __PVT__pshare_cnt_ph6_req;
        CData/*6:0*/ __PVT__ownerp_id_ph6_req;
        CData/*6:0*/ __PVT__ownerp_id_ph6_req_nxt;
        CData/*0:0*/ __PVT__wren_stat_req_ph4;
        CData/*0:0*/ __PVT__wren_stat_req_ph3;
        CData/*5:0*/ __PVT__wraddr_stat_req_ph4;
        CData/*5:0*/ __PVT__wraddr_stat_req_ph3;
        CData/*0:0*/ __PVT__wren_stat_rsp_ph3;
        CData/*5:0*/ __PVT__wraddr_stat_rsp_ph3;
        CData/*6:0*/ __PVT__new_ownerp_id_ph3_req;
        CData/*6:0*/ __PVT__new_ownerp_id_ph3_rsp;
        CData/*2:0*/ __PVT__new_cache_st_ph3_req;
        CData/*2:0*/ __PVT__new_cache_st_ph3_rsp;
        CData/*0:0*/ __PVT__new_cache_st_1_ph3_req;
        CData/*0:0*/ __PVT__new_cache_st_1_ph3_rsp;
        CData/*4:0*/ __PVT__new_snpresp_cnt_req_ph4;
        CData/*0:0*/ __PVT__req_st_valid_ph4;
        CData/*0:0*/ __PVT__orig_st_uniq_ph4;
        CData/*0:0*/ __PVT__new_mmemresp_cnt_req_ph3;
        CData/*0:0*/ __PVT__new_dbid_cnt_req_ph3;
        CData/*1:0*/ __PVT__new_compdbid_cnt_req_ph3;
        CData/*0:0*/ __PVT__req_st_notdirty_ph4;
        CData/*0:0*/ __PVT__req_st_dirty_ph4;
        CData/*0:0*/ __PVT__dn_sm_req_ph4;
        CData/*1:0*/ __PVT__new_wrdata_cnt_req_ph3;
        CData/*0:0*/ __PVT__new_compack_cnt_req_ph3;
        CData/*0:0*/ __PVT__new_comp_cnt_req_ph3;
        CData/*0:0*/ __PVT__new_readreceipt_cnt_req_ph3;
        CData/*0:0*/ __PVT__compack_cnt_resp_ph3;
        CData/*0:0*/ __PVT__comp_cnt_resp_ph3;
        CData/*0:0*/ __PVT__comp_slc_cnt_resp_ph3;
        CData/*0:0*/ __PVT__readreceipt_cnt_resp_ph3;
        CData/*0:0*/ __PVT__new_compack_cnt_resp_ph4_nxt;
        CData/*0:0*/ __PVT__new_comp_cnt_resp_ph4_nxt;
        CData/*0:0*/ __PVT__new_comp_slc_cnt_resp_ph4_nxt;
        CData/*0:0*/ __PVT__new_readreceipt_cnt_resp_ph4_nxt;
        CData/*1:0*/ __PVT__atmo_state_ph3;
        CData/*1:0*/ __PVT__new_atmo_state_req_ph3;
        CData/*1:0*/ __PVT__new_atmo_state_ph4_nxt;
        CData/*0:0*/ __PVT__new_compcmo_cnt_req_ph3;
        CData/*0:0*/ __PVT__new_compcmo_cnt_resp_ph4_nxt;
        CData/*0:0*/ __PVT__compcmo_cnt_resp_ph3;
        CData/*1:0*/ __PVT__cmdq_src_ph4_rsp;
        CData/*0:0*/ __PVT__cmdq_snpresp_or_dataresp_ph4;
        CData/*0:0*/ __PVT__cmdq_src0_SnpResp_ph4;
        CData/*0:0*/ __PVT__cmdq_srcdata_ph4;
        CData/*6:0*/ __PVT__origreq_opcode_ph4;
    };
    struct {
        CData/*0:0*/ __PVT__orig_st_sd_ph4;
        CData/*0:0*/ __PVT__orig_st_uc_ph4;
        CData/*0:0*/ __PVT__req_st_invalid_ph4;
        CData/*0:0*/ __PVT__orig_st_invalid_ph4;
        CData/*2:0*/ __PVT__orig_cache_st_ph4;
        CData/*0:0*/ __PVT__orig_st_dirty_ph4;
        CData/*0:0*/ __PVT__req_st_invalid_ph3;
        CData/*0:0*/ __PVT__snp_resp_state_inv_ph3;
        CData/*4:0*/ __PVT__orig_pshare_cnt_ph3;
        CData/*2:0*/ __PVT__snp_resp_ph3;
        CData/*0:0*/ __PVT__itis_finalcompack;
        CData/*0:0*/ __PVT__wren_cmq_ph4_nxt;
        CData/*2:0*/ __PVT__req_cache_st_ph4;
        CData/*0:0*/ __PVT__req_is_read_o_ph4;
        CData/*0:0*/ __PVT__req_is_read_c_ph4;
        CData/*0:0*/ __PVT__req_is_read_s_ph4;
        CData/*0:0*/ __PVT__req_is_read_u_ph4;
        CData/*0:0*/ __PVT__req_is_read_notsd_ph4;
        CData/*0:0*/ __PVT__req_is_makeread_u_ph4;
        CData/*0:0*/ __PVT__req_is_read_pu_ph4;
        CData/*0:0*/ __PVT__req_is_clean_u_ph4;
        CData/*0:0*/ __PVT__req_is_clean_i_ph4;
        CData/*0:0*/ __PVT__req_is_clean_s_ph4;
        CData/*0:0*/ __PVT__req_is_make_u_ph4;
        CData/*0:0*/ __PVT__req_is_make_i_ph4;
        CData/*0:0*/ __PVT__req_is_evict_ph4;
        CData/*0:0*/ __PVT__req_is_read_ocs_notsd_ph4;
        CData/*0:0*/ __PVT__req_is_clean_ui_ph4;
        CData/*0:0*/ __PVT__req_is_make_ui_ph4;
        CData/*0:0*/ __PVT__req_is_read_s_notsd_ph4;
        CData/*0:0*/ __PVT__req_is_dataless_ph4;
        CData/*0:0*/ __PVT__req_is_wr_uniq_ph4;
        CData/*0:0*/ __PVT__snpattr_req_ph4;
        CData/*0:0*/ __PVT__cmdq_srcis_cachemiss_ph2_pre;
        CData/*0:0*/ __PVT__cmdq_srcis_colln_ph2_pre;
        CData/*0:0*/ __PVT__cmdq_srcis_newreq_ph2_pre;
        CData/*0:0*/ __PVT__cmdis_invalidate_ph2_pre;
        CData/*0:0*/ __PVT__snpattr_req_ph2_pre;
        CData/*0:0*/ __PVT__snpattr_req_ph2;
        CData/*0:0*/ __PVT__req_is_read_ocsu_notsd_ph3;
        CData/*0:0*/ __PVT__req_is_read_ocs_ph3;
        CData/*0:0*/ __PVT__req_is_read_ocsu_notsd_pu_ph3;
        CData/*0:0*/ __PVT__req_is_read_csu_notsd_pu_ph3;
        CData/*0:0*/ __PVT__req_is_read_su_notsd_pu_ph3;
        CData/*0:0*/ __PVT__req_is_read_cs_notsd_ph3;
        CData/*0:0*/ __PVT__orig_read_o_ph4;
        CData/*0:0*/ __PVT__orig_read_c_ph4;
        CData/*0:0*/ __PVT__orig_read_s_ph4;
        CData/*0:0*/ __PVT__orig_read_u_ph4;
        CData/*0:0*/ __PVT__orig_read_nosnp_ph4;
        CData/*0:0*/ __PVT__orig_read_notsd_ph4;
        CData/*0:0*/ __PVT__orig_clean_u_ph4;
        CData/*0:0*/ __PVT__orig_clean_s_ph4;
        CData/*0:0*/ __PVT__orig_clean_i_ph4;
        CData/*0:0*/ __PVT__orig_make_u_ph4;
        CData/*0:0*/ __PVT__orig_make_i_ph4;
        CData/*0:0*/ __PVT__orig_evict_ph4;
        CData/*0:0*/ __PVT__orig_wr_cl_ph4;
        CData/*0:0*/ __PVT__orig_wr_copyback_ph4;
        CData/*0:0*/ __PVT__orig_wr_cl_ph3;
        CData/*0:0*/ __PVT__orig_read_su_pu_ph3;
        CData/*6:0*/ __PVT__moving_ownerp_id_ph3;
        CData/*6:0*/ __PVT__moving_ownerp_id_ph4;
        CData/*2:0*/ __PVT__moving_cache_st_ph3;
    };
    struct {
        CData/*2:0*/ __PVT__moving_cache_st_ph4;
        CData/*1:0*/ __PVT__wrdata_cnt_resp_ph3;
        CData/*1:0*/ __PVT__wrdata_cnt_resp_ph4;
        CData/*1:0*/ __PVT__compdbid_cnt_ph3;
        CData/*0:0*/ __PVT__dbid_cnt_ph3;
        CData/*0:0*/ __PVT__got_compack_ph3;
        CData/*0:0*/ __PVT__last_read_snp_sent_ph3;
        IData/*23:0*/ __PVT__seq_num;
        IData/*23:0*/ __PVT__seq_num_nxt;
        IData/*23:0*/ __PVT__seq_num_atom;
        IData/*23:0*/ __PVT__seq_num_atom_nxt;
        CData/*7:0*/ __PVT__wren_collnq_valid;
        CData/*2:0*/ __PVT__wren_collnq_vld_idx;
        CData/*7:0*/ __PVT__clr_collnq_valid;
        CData/*7:0*/ __PVT__colln_empty;
        CData/*7:0*/ __PVT__colln_empty_nxt;
        CData/*7:0*/ __PVT__colln_cmd_invalidate;
        CData/*7:0*/ __PVT__colln_cmd_invalidate_nxt;
        CData/*7:0*/ __PVT__highest_seq_is4;
        CData/*7:0*/ __PVT__highest_seq_is3;
        CData/*7:0*/ __PVT__highest_seq_is2;
        CData/*7:0*/ __PVT__highest_seq_is1;
        CData/*7:0*/ __PVT__highest_seq_is0;
        CData/*7:0*/ __PVT__highest_seq_is4_atom;
        CData/*7:0*/ __PVT__highest_seq_is3_atom;
        CData/*7:0*/ __PVT__highest_seq_is2_atom;
        CData/*7:0*/ __PVT__highest_seq_is1_atom;
        CData/*7:0*/ __PVT__highest_seq_is0_atom;
        CData/*0:0*/ __PVT__any_highest_seq_is4;
        CData/*0:0*/ __PVT__any_highest_seq_is3;
        CData/*0:0*/ __PVT__any_highest_seq_is2;
        CData/*0:0*/ __PVT__any_highest_seq_is1;
        CData/*0:0*/ __PVT__any_highest_seq_is0;
        CData/*0:0*/ __PVT__any_highest_seq_is4_atom;
        CData/*0:0*/ __PVT__any_highest_seq_is3_atom;
        CData/*0:0*/ __PVT__any_highest_seq_is2_atom;
        CData/*0:0*/ __PVT__any_highest_seq_is1_atom;
        CData/*0:0*/ __PVT__any_highest_seq_is0_atom;
        CData/*0:0*/ __PVT__colln_newentry_addr_clr_addr_match;
        CData/*0:0*/ __PVT__colln_newentry_atom_clr_atom;
        CData/*0:0*/ __PVT__highest_seqnum_is4;
        CData/*0:0*/ __PVT__highest_seqnum_is3;
        CData/*0:0*/ __PVT__highest_seqnum_is2;
        CData/*0:0*/ __PVT__highest_seqnum_is1;
        CData/*0:0*/ __PVT__highest_seqnum_is0;
        CData/*0:0*/ __PVT__highest_seqnum_is4_atom;
        CData/*0:0*/ __PVT__highest_seqnum_is3_atom;
        CData/*0:0*/ __PVT__highest_seqnum_is2_atom;
        CData/*0:0*/ __PVT__highest_seqnum_is1_atom;
        CData/*0:0*/ __PVT__highest_seqnum_is0_atom;
        CData/*0:0*/ __PVT__en_clr_collnreg;
        CData/*0:0*/ __PVT__en_clr_collnreg_nxt;
        CData/*0:0*/ __PVT__en_clr_atom_rd_collnreg;
        CData/*0:0*/ __PVT__en_clr_atom_rd_collnreg_nxt;
        CData/*7:0*/ __PVT__colln_clr_addr_match;
        CData/*7:0*/ __PVT__colln_clr_no_atom_outstand;
        CData/*7:0*/ __PVT__decrement_seq_num_atom;
        CData/*7:0*/ __PVT__set_colln_rdy;
        CData/*7:0*/ __PVT__clr_colln_rdy;
        CData/*7:0*/ __PVT__colln_rdy_for_proc;
        CData/*7:0*/ __PVT__colln_rdy_for_proc_nxt;
        CData/*0:0*/ __PVT__atom_block_rd;
        CData/*7:0*/ __PVT__colln_rdy_atom_block_rd;
        CData/*7:0*/ __PVT__colln_rdy_atom_block_rd_nxt;
    };
    struct {
        CData/*7:0*/ __PVT__colln_rdy_for_proc_lock;
        CData/*7:0*/ __PVT__colln_rdy_for_proc_lock_nxt;
        CData/*7:0*/ __PVT__colln_cmd_addr_invalid;
        CData/*7:0*/ __PVT__colln_cmd_addr_invalid_nxt;
        CData/*7:0*/ __PVT__colln_cmd_isatmo_wr_nxt;
        CData/*7:0*/ __PVT__colln_cmd_isatmo_wr;
        CData/*7:0*/ __PVT__colln_cmd_isatmo_rd_nxt;
        CData/*7:0*/ __PVT__colln_cmd_isatmo_rd;
        CData/*0:0*/ __PVT__collnq_full;
        CData/*7:0*/ __PVT__sel_winner_collq;
        CData/*0:0*/ __PVT__winner_colln_addr_invalid;
        CData/*0:0*/ __PVT__winner_colln_invalidate;
        CData/*0:0*/ __PVT__sel_winner_addr_invalid;
        CData/*0:0*/ __PVT__sel_winner_invalidate;
        CData/*7:0*/ __PVT__colln_detected_collnq;
        CData/*7:0*/ __PVT__colln_detected_ph2;
        CData/*7:0*/ __PVT__colln_detected_ph3;
        CData/*7:0*/ __PVT__colln_atom_detected_collnq;
        CData/*7:0*/ __PVT__colln_atom_detected_ph2;
        CData/*7:0*/ __PVT__colln_atom_detected_ph3;
        CData/*7:0*/ __PVT__colln_atom_rd_detected_atom_wr_ph3;
        CData/*2:0*/ __PVT__colln_det_collnq_idx;
        CData/*0:0*/ __PVT__colln_detected_in_outstq;
        CData/*0:0*/ __PVT__colln_detected_in_collnq;
        CData/*0:0*/ __PVT__colln_atom_detected_in_outstq;
        CData/*0:0*/ __PVT__colln_atom_detected_in_collnq;
        CData/*0:0*/ __PVT__colln_detected_outstq_or_collnq_ph3;
        CData/*4:0*/ __PVT__outstand_no_atom_cntr;
        CData/*4:0*/ __PVT__outstand_no_atom_cntr_nxt;
        CData/*0:0*/ __PVT__decrement_colln_atom_seq_num;
        CData/*0:0*/ __PVT__decrement_colln_atom_seq_num_nxt;
        CData/*7:0*/ __PVT__has_atom_rd_seq_num_0;
        CData/*0:0*/ __PVT__blockreqq_dueto_highestseqnum_incollnq;
        CData/*0:0*/ __PVT__blockcmq_dueto_highestseqnum_incollnq;
        CData/*7:0*/ __PVT__colln_detected_reqcmdq;
        CData/*7:0*/ __PVT__colln_detected_cmq;
        CData/*7:0*/ __PVT__highest_seq_reqcmdq_is3_or_more;
        CData/*7:0*/ __PVT__highest_seq_cmq_is3_or_more;
        CData/*0:0*/ __PVT__cmdq_srcis_cachemiss_ph2;
        CData/*0:0*/ __PVT__cmdq_srcis_colln_ph2;
        CData/*0:0*/ __PVT__cmdq_srcis_newreq_ph2;
        CData/*0:0*/ __PVT__cmdq_srcis_resp_ph2;
        CData/*0:0*/ __PVT__cmdq_srcis_mem_ph2;
        CData/*0:0*/ __PVT__cmdq_srcis_data_ph2;
        CData/*0:0*/ __PVT__cmdq_srcis_cachemiss_ph3;
        CData/*0:0*/ __PVT__cmdq_srcis_colln_ph3;
        CData/*0:0*/ __PVT__cmdq_srcis_newreq_ph3;
        CData/*7:0*/ __PVT__num_emptyloc_collnq;
        CData/*7:0*/ __PVT__num_emptyloc_collnq_nxt;
        CData/*0:0*/ __PVT__req_collnq;
        CData/*0:0*/ __PVT__req_collnq_nxt;
        CData/*0:0*/ __PVT__collnreq_st;
        CData/*0:0*/ __PVT__collnreq_st_nxt;
        CData/*7:0*/ __PVT__colln_match_check_for_inpendingq;
        CData/*0:0*/ __PVT__block_reqcmdq_dueto_eviction;
        CData/*0:0*/ __PVT__sel_cmq_path_ph3;
        CData/*0:0*/ __PVT__block_cmqfull;
        CData/*0:0*/ __PVT__reqid_matches_sharevec_ph3;
        CData/*0:0*/ __PVT__reqid_matches_sharevec_ph4;
        CData/*0:0*/ __PVT__block_reqcmdq_rd_cache;
        CData/*0:0*/ __PVT__block_collnq_rd_cache;
        CData/*0:0*/ __PVT__block_cmq_rd_cache;
        CData/*0:0*/ __PVT__noncm_tgt_sn_supports_dmt_ph2;
        CData/*0:0*/ __PVT__noncm_tgt_sn_supports_dmt_ph3;
    };
    struct {
        CData/*0:0*/ __PVT__cm_tgt_sn_supports_dmt_ph2;
        CData/*0:0*/ __PVT__cm_tgt_sn_supports_dmt_ph3;
        CData/*0:0*/ __PVT__cmd_ph3_apply_dmt_req;
        CData/*0:0*/ __PVT__cmd_ph4_apply_dmt_req;
        CData/*0:0*/ __PVT__cmd_ph3_apply_dmt_rsp;
        CData/*0:0*/ __PVT__origreq_apply_dmt_ph3;
        CData/*0:0*/ __PVT__cmd_ph3_nonexcl_read_dct_req;
        CData/*0:0*/ __PVT__cmd_ph4_nonexcl_read_dct_req;
        CData/*0:0*/ __PVT__cmd_ph3_snprespfwded_dct_rsp;
        CData/*0:0*/ __PVT__cmd_ph3_snprespdatafwded_dct_rsp;
        CData/*0:0*/ __PVT__origreq_may_apply_dct_ph3;
        CData/*0:0*/ __PVT__opcode_any_snpfwded_response_dct_ph3;
        CData/*0:0*/ __PVT__invalid_requester_state_after_dct_ph3;
        CData/*2:0*/ __PVT__snoop_response_fwdstate_ph3;
        CData/*0:0*/ __PVT__cm_addr_match_pm_ph1;
        CData/*0:0*/ __PVT__cm_addr_match_pm_ph2;
        CData/*0:0*/ __PVT__cm_activated_pm;
        CData/*0:0*/ __PVT__noncm_addr_match_pm_ph1;
        CData/*0:0*/ __PVT__noncm_addr_match_pm_ph2;
        CData/*0:0*/ __PVT__noncm_activated_pm;
        CData/*0:0*/ __PVT__req_is_invalid_resperr_ph1;
        CData/*0:0*/ __PVT__req_is_invalid_resperr_ph2;
        CData/*0:0*/ __PVT__req_is_invalid_resperr_ph3;
        CData/*0:0*/ __PVT__req_is_invalid_resperr_ph4;
        CData/*1:0*/ __PVT__origreq_order_ph3;
        CData/*0:0*/ __PVT__origreq_cacheable_bit_ph3;
        CData/*0:0*/ __PVT__origreq_snpattr_ph3;
        CData/*0:0*/ __PVT__origreq_ordered_write_ph3;
        CData/*3:0*/ __PVT__stored_pcrdtype_from_mem_ph3;
        CData/*3:0*/ __PVT__share_vec_src_cluster_ph3;
        CData/*0:0*/ __PVT__any_timeout_flag_true;
        CData/*5:0*/ __PVT__winner_timeout_index_B0;
        CData/*5:0*/ __PVT__winner_timeout_index_B1;
        CData/*5:0*/ __PVT__winner_timeout_index_B2;
        CData/*5:0*/ __PVT__winner_timeout_index_B3;
        CData/*5:0*/ __PVT__winner_timeout_index;
        CData/*0:0*/ __PVT__service_timeout;
        CData/*6:0*/ __PVT__new_ownerp_id_ph4_rsp;
        CData/*2:0*/ __PVT__new_cache_st_ph4_rsp;
        CData/*6:0*/ __PVT__new_ownerp_id_ph4_req;
        CData/*2:0*/ __PVT__new_cache_st_ph4_req;
        CData/*0:0*/ __PVT__determine_ownerp_id_atreq;
        CData/*0:0*/ __PVT__determine_st_atreq;
        CData/*0:0*/ __PVT__itis_prelastresp_read_snp_ph3;
        CData/*0:0*/ __PVT__itis_lastresp_read_snp_ph3;
        CData/*0:0*/ __PVT__itis_lastresp_dataless_snpdataptl_ph3;
        CData/*4:0*/ __PVT__compbuff_num_1st_ph3;
        CData/*4:0*/ __PVT__compbuff_num_2nd_ph3;
        CData/*0:0*/ __PVT__vld_compbuff_num_2nd_ph3;
        CData/*0:0*/ __PVT__block_rsp_proc_dueto_dn_sm_req_ph3;
        CData/*0:0*/ __PVT__flit_dwt_en_ph3;
        CData/*0:0*/ __PVT__new_retry_pending_ph4_nxt;
        CData/*0:0*/ __PVT__retry_pending_ph3;
        CData/*3:0*/ __PVT__new_retry_pcrdtype_ph4_nxt;
        CData/*3:0*/ __PVT__retry_pcrdtype_ph3;
        CData/*1:0*/ __PVT__new_comp_resperr_ph4_nxt;
        CData/*1:0*/ __PVT__comp_resperr_ph3;
        CData/*0:0*/ __PVT__itis_atom_txn_data_ph3;
        CData/*0:0*/ __PVT__itis_atom_init_data_ph3;
        CData/*0:0*/ __PVT__itis_atom_comp_rsp_ph3;
        CData/*0:0*/ __PVT__itis_atom_res_data_ph3;
        CData/*0:0*/ __PVT__itis_atom_ini_data_ph3;
        CData/*0:0*/ __PVT__itis_atom_clr_buff_ph3;
        CData/*0:0*/ __PVT__itis_lastresp_atom_comp_ph3;
    };
    struct {
        CData/*0:0*/ __PVT__itis_lastresp_ph3_atom_clr_buffer;
        CData/*0:0*/ __PVT__itis_prelastresp_atom_wr_result_p1_ph3;
        CData/*0:0*/ __PVT__was_prelastresp_atom_wr_result_p1_ph4_nxt;
        CData/*0:0*/ __PVT__was_prelastresp_atom_wr_result_p1_ph3;
        CData/*0:0*/ __PVT__itis_lastresp_atom_wr_result_p2_ph3;
        CData/*0:0*/ __PVT__itis_prelastresp_atom_wr_result_p2_ph3_comp_is_last;
        CData/*0:0*/ __PVT__itis_lastresp_atom_wr_result_p2_ph3_comp_is_last;
        CData/*0:0*/ __PVT__itis_lastresp_atom_inidata_ph3;
        CData/*0:0*/ __PVT__block_b2b_resp;
        CData/*0:0*/ __PVT__reqfifo_bypass_en;
        CData/*0:0*/ __PVT__wren_reqcmdq_withbypass;
        CData/*0:0*/ __PVT__rden_reqcmdq;
        CData/*2:0*/ __PVT__serv_history_req;
        CData/*2:0*/ __PVT__serv_history_req_nxt;
        CData/*2:0*/ __PVT__gnt_requests_req;
        CData/*2:0*/ __PVT__req_all_req;
        CData/*2:0*/ __PVT__serv_history_rsp;
        CData/*2:0*/ __PVT__serv_history_rsp_nxt;
        CData/*2:0*/ __PVT__gnt_requests_rsp;
        CData/*2:0*/ __PVT__req_all_rsp;
        CData/*0:0*/ __PVT__block_b2b_resp_respcmdq;
        CData/*0:0*/ __PVT__block_b2b_resp_memrespcmdq;
        CData/*0:0*/ __PVT__block_b2b_resp_drespcmdq;
        CData/*0:0*/ __PVT__any_resp_selected;
        CData/*1:0*/ __PVT__resp_block_cnt_0;
        CData/*1:0*/ __PVT__resp_block_cnt_0_nxt;
        CData/*1:0*/ __PVT__resp_block_cnt_1;
        CData/*1:0*/ __PVT__resp_block_cnt_1_nxt;
        CData/*1:0*/ __PVT__resp_block_cnt_2;
        CData/*1:0*/ __PVT__resp_block_cnt_2_nxt;
        CData/*1:0*/ __PVT__resp_block_cnt_3;
        CData/*1:0*/ __PVT__resp_block_cnt_3_nxt;
        CData/*1:0*/ __PVT__resp_block_cnt_4;
        CData/*1:0*/ __PVT__resp_block_cnt_4_nxt;
        CData/*0:0*/ __PVT__sel_blkcnt_0;
        CData/*0:0*/ __PVT__sel_blkcnt_1;
        CData/*0:0*/ __PVT__sel_blkcnt_2;
        CData/*0:0*/ __PVT__sel_blkcnt_3;
        CData/*0:0*/ __PVT__sel_blkcnt_4;
        CData/*5:0*/ __PVT__last_resp_index_0;
        CData/*5:0*/ __PVT__last_resp_index_0_nxt;
        CData/*5:0*/ __PVT__last_resp_index_1;
        CData/*5:0*/ __PVT__last_resp_index_1_nxt;
        CData/*5:0*/ __PVT__last_resp_index_2;
        CData/*5:0*/ __PVT__last_resp_index_2_nxt;
        CData/*5:0*/ __PVT__last_resp_index_3;
        CData/*5:0*/ __PVT__last_resp_index_3_nxt;
        CData/*5:0*/ __PVT__last_resp_index_4;
        CData/*5:0*/ __PVT__last_resp_index_4_nxt;
        CData/*0:0*/ __PVT__occupied_last_resp_index_0;
        CData/*0:0*/ __PVT__occupied_last_resp_index_0_nxt;
        CData/*0:0*/ __PVT__occupied_last_resp_index_1;
        CData/*0:0*/ __PVT__occupied_last_resp_index_1_nxt;
        CData/*0:0*/ __PVT__occupied_last_resp_index_2;
        CData/*0:0*/ __PVT__occupied_last_resp_index_2_nxt;
        CData/*0:0*/ __PVT__occupied_last_resp_index_3;
        CData/*0:0*/ __PVT__occupied_last_resp_index_3_nxt;
        CData/*0:0*/ __PVT__occupied_last_resp_index_4;
        CData/*0:0*/ __PVT__occupied_last_resp_index_4_nxt;
        CData/*3:0*/ __PVT__cmd_ph3_dat_opcode;
        CData/*0:0*/ __PVT__read_req_requires_non_inv_snoop_ph3;
        CData/*0:0*/ __PVT__cmd_ph3_rsp_is_COPYBACKWRDATA;
        CData/*0:0*/ __PVT__cmd_ph3_rsp_is_NONCOPYBACKWRDATA;
        CData/*0:0*/ __PVT__cmd_ph3_rsp_is_NONCOPYBACKWRDATACOMP;
    };
    struct {
        CData/*0:0*/ __PVT__cmd_ph3_rsp_is_WRITEDATACANCEL;
        CData/*0:0*/ __PVT__live_RespErr_active;
        CData/*5:0*/ __PVT__index_pendingq_clr_outstand_cmd;
        CData/*1:0*/ __PVT__cc_inactive_st;
        CData/*1:0*/ __PVT__cc_inactive_st_nxt;
        CData/*0:0*/ __PVT__outstand_cmd_invalid_allones;
        CData/*0:0*/ __PVT__cc_is_inactive_nxt;
        CData/*0:0*/ __PVT__unused_signal;
        CData/*0:0*/ __PVT__cmdq_srcis_resp_ph3;
        CData/*0:0*/ __PVT__cmdq_srcis_mem_ph3;
        CData/*0:0*/ __PVT__cmdq_srcis_data_ph3;
        CData/*0:0*/ __PVT__cmdvalid_ph4_req_nxt;
        CData/*0:0*/ __PVT__wren_outcompfifo_excl_fail;
        CData/*0:0*/ __PVT__origreq_excl_ld_snp_ph3;
        CData/*0:0*/ __PVT__origreq_excl_ld_nonsnp_ph3;
        CData/*0:0*/ __PVT__req_is_wrbackfl_clean_i_ph4;
        CData/*0:0*/ __PVT__req_is_wrbackfl_clean_s_ph4;
        CData/*0:0*/ __PVT__req_is_wrcleanfl_clean_s_ph4;
        CData/*0:0*/ __PVT__new_comp_slc_cnt_req_ph3;
        CData/*5:0*/ __Vdly__respbuff_avail;
        CData/*1:0*/ __Vdly__resp_block_cnt_0;
        CData/*1:0*/ __Vdly__resp_block_cnt_1;
        CData/*1:0*/ __Vdly__resp_block_cnt_2;
        CData/*1:0*/ __Vdly__resp_block_cnt_3;
        CData/*1:0*/ __Vdly__resp_block_cnt_4;
        CData/*5:0*/ __Vdly__last_resp_index_0;
        CData/*5:0*/ __Vdly__last_resp_index_1;
        CData/*5:0*/ __Vdly__last_resp_index_2;
        CData/*5:0*/ __Vdly__last_resp_index_3;
        CData/*5:0*/ __Vdly__last_resp_index_4;
        CData/*0:0*/ __Vdly__occupied_last_resp_index_0;
        CData/*0:0*/ __Vdly__occupied_last_resp_index_1;
        CData/*0:0*/ __Vdly__occupied_last_resp_index_2;
        CData/*0:0*/ __Vdly__occupied_last_resp_index_3;
        CData/*0:0*/ __Vdly__occupied_last_resp_index_4;
        CData/*0:0*/ __Vdly__cmdvalid_ph2_req;
        CData/*1:0*/ __Vdly__cmdq_src_ph2_req;
        CData/*1:0*/ __Vdly__cmdq_src_ph3_req;
        CData/*0:0*/ __Vdly__cmdis_req_ph2;
        CData/*0:0*/ __Vdly__req_collnq;
        CData/*0:0*/ __Vdly__collnreq_st;
        CData/*0:0*/ __Vdly__cmdis_invalidate_ph2;
        CData/*0:0*/ __Vdly__cmdis_invalidate_ph3;
        CData/*0:0*/ __Vdly__cmdis_invalidate_ph4;
        CData/*2:0*/ __Vdly__serv_history_req;
        CData/*2:0*/ __Vdly__serv_history_rsp;
        CData/*0:0*/ __Vdly__cmdvalid_ph3_req;
        CData/*0:0*/ __Vdly__cmdvalid_ph3_rsp;
        CData/*1:0*/ __Vdly__cmdq_src_ph3_rsp;
        CData/*0:0*/ __Vdly__cmdis_req_ph3;
        CData/*0:0*/ __Vdly__cmdis_resp_ph3;
        CData/*0:0*/ __Vdly__reqid_matches_sharevec_ph4;
        CData/*5:0*/ __Vdly__index_statusreg_ph3;
        CData/*0:0*/ __Vdly__excl_pass_ph4;
        CData/*0:0*/ __Vdly__cmd_ph4_apply_dmt_req;
        CData/*0:0*/ __Vdly__cmd_ph4_nonexcl_read_dct_req;
        CData/*0:0*/ __Vdly__snpattr_req_ph3;
        CData/*0:0*/ __Vdly__cmdq_srcis_cachemiss_ph3;
        CData/*0:0*/ __Vdly__cmdq_srcis_colln_ph3;
        CData/*0:0*/ __Vdly__cmdq_srcis_newreq_ph3;
        CData/*0:0*/ __Vdly__cmdvalid_ph4_req;
        CData/*0:0*/ __Vdly__cmdvalid_ph4_rsp;
        CData/*0:0*/ __Vdly__cmdis_req_ph4;
        CData/*0:0*/ __Vdly__cmdis_resp_ph4;
    };
    struct {
        CData/*5:0*/ __Vdly__wrindex_req_ph4;
        CData/*0:0*/ __Vdly__wren_cmq_ph4;
        CData/*2:0*/ __Vdly__req_atmo_ph4;
        CData/*0:0*/ __Vdly__cmd_isatmo_wr_ph3;
        CData/*0:0*/ __Vdly__cmd_isatmo_rd_ph3;
        CData/*0:0*/ __Vdly__cmd_isatmo_ph3;
        CData/*0:0*/ __Vdly__reqid_matches_ownerpid_ph4;
        CData/*0:0*/ __Vdly__dataless_xfrdata_tomem_ph4;
        CData/*1:0*/ __Vdly__cmdq_src_ph4_rsp;
        CData/*0:0*/ __Vdly__dn_sm_req_ph4;
        CData/*5:0*/ __Vdly__cmd_ph4_23_18_rsp;
        CData/*5:0*/ __Vdly__cmd_ph5_23_18_rsp;
        CData/*5:0*/ __Vdly__cmd_ph4_23_18_req;
        CData/*5:0*/ __Vdly__cmd_ph5_23_18_req;
        CData/*5:0*/ __Vdly__cmd_ph6_23_18_req;
        CData/*6:0*/ __Vdly__ownerp_id_ph6_req;
        CData/*6:0*/ __Vdly__ownerp_id_ph6_rsp;
        CData/*5:0*/ __Vdly__index_statusreg_ph4;
        CData/*6:0*/ __Vdly__new_ownerp_id_ph4_rsp;
        CData/*2:0*/ __Vdly__new_cache_st_ph4_rsp;
        CData/*6:0*/ __Vdly__new_ownerp_id_ph4_req;
        CData/*2:0*/ __Vdly__new_cache_st_ph4_req;
        CData/*4:0*/ __Vdly__pshare_cnt_ph6_req;
        CData/*4:0*/ __Vdly__pshare_cnt_ph6_rsp;
        CData/*7:0*/ __Vdly__colln_detected_ph3;
        CData/*7:0*/ __Vdly__colln_atom_detected_ph3;
        VlWide<5>/*159:0*/ __Vdly__outstand_cmd_buffnum_1st;
        VlWide<5>/*159:0*/ __Vdly__outstand_cmd_buffnum_2nd;
        CData/*0:0*/ __Vdly__outstand_atmo_rd_alloc_then_wr_clr;
        CData/*4:0*/ __Vdly__outstand_no_atom_cntr;
        CData/*0:0*/ __Vdly__decrement_colln_atom_seq_num;
        CData/*7:0*/ __Vdly__colln_empty;
        CData/*7:0*/ __Vdly__colln_cmd_invalidate;
        CData/*7:0*/ __Vdly__colln_rdy_for_proc;
        CData/*7:0*/ __Vdly__colln_rdy_atom_block_rd;
        CData/*7:0*/ __Vdly__colln_rdy_for_proc_lock;
        CData/*7:0*/ __Vdly__colln_cmd_addr_invalid;
        CData/*7:0*/ __Vdly__colln_cmd_isatmo_rd;
        CData/*7:0*/ __Vdly__colln_cmd_isatmo_wr;
        CData/*0:0*/ __Vdly__en_clr_collnreg;
        CData/*0:0*/ __Vdly__en_clr_atom_rd_collnreg;
        CData/*7:0*/ __Vdly__num_emptyloc_collnq;
        CData/*0:0*/ __Vdly__req_is_invalid_resperr_ph2;
        CData/*0:0*/ __Vdly__req_is_invalid_resperr_ph3;
        CData/*0:0*/ __Vdly__req_is_invalid_resperr_ph4;
        CData/*0:0*/ __Vdly__cm_addr_match_pm_ph2;
        CData/*0:0*/ __Vdly__noncm_addr_match_pm_ph2;
        CData/*0:0*/ __Vdly__noncm_tgt_sn_supports_dmt_ph3;
        CData/*0:0*/ __Vdly__cm_tgt_sn_supports_dmt_ph3;
        CData/*1:0*/ __Vdly__cc_inactive_st;
        CData/*0:0*/ __Vdly__cc_is_inactive;
        VL_IN16(__PVT__index_cache_eviction,9,0);
        VL_OUT16(__PVT__cache_index_rd_ph2,9,0);
        VL_IN16(__PVT__cachehit_vector_ph3,15,0);
        VL_OUT16(__PVT__cache_index_rd_ph2_pre,9,0);
        VL_OUT16(__PVT__wren_cache_vector,15,0);
        VL_OUT16(__PVT__cache_index_wr,9,0);
        VL_IN16(__PVT__cache_index_wr_cohc_or_dirc,9,0);
        VL_OUT16(__PVT__excl_load_srcid,10,0);
        VL_OUT16(__PVT__excl_store_srcid,10,0);
        VL_IN16(__PVT__xy_coord_all_pm,10,0);
        VL_OUT16(__PVT__o_rcv_rsp_dat_srcid,10,0);
        VL_IN16(__PVT__i_rcv_rsp_dat_linear_srcid,10,0);
        SData/*10:0*/ __PVT__cmd_ph3_rsp_linear_srcid;
    };
    struct {
        SData/*11:0*/ __PVT__cmd_ph3_rsp_dbid;
        VlWide<16>/*511:0*/ __PVT__status_field_retry_ph3;
        VlWide<16>/*511:0*/ __PVT__status_field_retry_ph3_nxt;
        SData/*11:0*/ __PVT__outstand_atom_rd_txnid;
        SData/*10:0*/ __PVT__outstand_atom_rd_srcid;
        SData/*15:0*/ __PVT__cachehit_vector_ph4;
        SData/*11:0*/ __PVT__new_dbid_from_slavemem_ph4_nxt;
        SData/*11:0*/ __PVT__new_dbid_from_slc_ph4_nxt;
        SData/*10:0*/ __PVT__origreq_src_id_ph3;
        SData/*11:0*/ __PVT__origreq_txnid_ph3;
        SData/*15:0*/ __PVT__wren_cache_vector_ph4_rsp;
        SData/*15:0*/ __PVT__wren_cache_vector_ph4_rsp_nxt;
        SData/*15:0*/ __PVT__wren_cache_vector_ph5_rsp;
        SData/*15:0*/ __PVT__wren_cache_vector_ph6rsp_nxt;
        SData/*15:0*/ __PVT__wren_cache_vector_ph6rsp;
        SData/*15:0*/ __PVT__wren_cache_vector_ph4_req;
        SData/*15:0*/ __PVT__wren_cache_vector_ph4_req_nxt;
        SData/*15:0*/ __PVT__wren_cache_vector_ph5_req;
        SData/*15:0*/ __PVT__wren_cache_vector_ph6_req;
        SData/*15:0*/ __PVT__wren_cache_vector_ph7_req;
        SData/*9:0*/ __PVT__cache_index_wr_rsp_nxt;
        SData/*9:0*/ __PVT__cache_index_wr_rsp;
        SData/*9:0*/ __PVT__cache_index_wr_req_nxt;
        SData/*9:0*/ __PVT__cache_index_wr_req;
        SData/*10:0*/ __PVT__cm_tgtid_pm_ph2;
        SData/*10:0*/ __PVT__nodeid_pm_2d;
        SData/*10:0*/ __PVT__noncm_tgtid_pm_ph2;
        SData/*10:0*/ __PVT__tgt_id_ph2;
        SData/*10:0*/ __PVT__tgt_id_ph3;
        SData/*10:0*/ __PVT__tgt_id_ph4;
        SData/*10:0*/ __PVT__origreq_tgt_id_ph3;
        SData/*11:0*/ __PVT__stored_dbid_from_slavemem_ph3;
        SData/*11:0*/ __PVT__dbid_from_slavemem_ph3;
        SData/*11:0*/ __PVT__stored_dbid_from_slc_ph3;
        SData/*11:0*/ __PVT__dbid_from_slc_ph3;
        SData/*15:0*/ __PVT__ucie_sam_activated;
        SData/*15:0*/ __PVT__ucie_addr_match_vec_ph1;
        SData/*10:0*/ __PVT__ucie_tgtid;
        SData/*15:0*/ __PVT__inactive_ctr;
        SData/*15:0*/ __PVT__inactive_ctr_nxt;
        SData/*15:0*/ __Vdly__cachehit_vector_ph4;
        VlWide<16>/*511:0*/ __Vdly__status_field_retry_ph3;
        SData/*9:0*/ __Vdly__cache_index_wr_rsp;
        SData/*9:0*/ __Vdly__cache_index_wr_req;
        SData/*15:0*/ __Vdly__wren_cache_vector_ph4_rsp;
        SData/*15:0*/ __Vdly__wren_cache_vector_ph5_rsp;
        SData/*15:0*/ __Vdly__wren_cache_vector_ph6rsp;
        SData/*15:0*/ __Vdly__wren_cache_vector_ph4_req;
        SData/*15:0*/ __Vdly__wren_cache_vector_ph5_req;
        SData/*15:0*/ __Vdly__wren_cache_vector_ph6_req;
        SData/*15:0*/ __Vdly__wren_cache_vector_ph7_req;
        SData/*10:0*/ __Vdly__tgt_id_ph3;
        SData/*10:0*/ __Vdly__tgt_id_ph4;
        SData/*15:0*/ __Vdly__inactive_ctr;
        VL_INW(__PVT__wrdata_reqcmdq,155,0,5);
        VL_INW(__PVT__wrdata_respcmdq,73,0,3);
        VL_INW(__PVT__wrdata_drespcmdq,108,0,4);
        VL_INW(__PVT__wrdata_memrespcmdq,108,0,4);
        VL_OUTW(__PVT__cmd_ph4_req,154,0,5);
        VL_INW(__PVT__cm_cmd,154,0,5);
        VL_INW(__PVT__evict_details,83,0,3);
        VL_IN(__PVT__rddata_cache_ph3,31,0);
        VL_OUT(__PVT__wrdata_cache,31,0);
        VL_IN(__PVT__clr_outstand_cmd_compdata,31,0);
    };
    struct {
        VL_IN(__PVT__clr_outstand_cmd_snpreq,31,0);
        VL_IN(__PVT__cm_homeaddr_base_all_pm,27,0);
        VL_IN(__PVT__cm_homeaddr_limit_all_pm,28,0);
        VL_IN(__PVT__noncm_homeaddr_base_all_pm,27,0);
        VL_IN(__PVT__noncm_homeaddr_limit_all_pm,28,0);
        VL_IN(__PVT__clr_outstand_prep,31,0);
        VL_OUT(__PVT__outstand_prep_valid,31,0);
        VL_OUT(__PVT__dealloc_compfifo_vector,31,0);
        VlWide<5>/*155:0*/ __PVT__rddata_reqcmdq;
        VlWide<5>/*154:0*/ __PVT__rddata_reqcmdq_withbypass;
        VlWide<5>/*154:0*/ __PVT__cmd_ph3_req;
        VlWide<5>/*154:0*/ __PVT__cmd_ph2_req;
        VlWide<5>/*154:0*/ __PVT__cmd_ph2_req_nxt;
        VlWide<5>/*154:0*/ __PVT__cmd_ph3_rsp;
        VlWide<5>/*154:0*/ __PVT__cmd_ph3_rsp_nxt;
        IData/*30:0*/ __PVT__lower_index_valid;
        IData/*31:0*/ __PVT__wren_retry_ph3;
        IData/*31:0*/ __PVT__wren_retry_ph3_nxt;
        IData/*31:0*/ __PVT__wren_outstand_cmd;
        IData/*31:0*/ __PVT__outstand_cmd_invalid;
        IData/*31:0*/ __PVT__outstand_cmd_invalid_nxt;
        IData/*31:0*/ __PVT__outstand_cmd_atom;
        IData/*31:0*/ __PVT__outstand_cmd_atom_nxt;
        VlWide<24>/*767:0*/ __PVT__outstand_cmd;
        VlWide<24>/*767:0*/ __PVT__outstand_cmd_nxt;
        IData/*31:0*/ __PVT__outstand_req_atmo_wr_nxt;
        IData/*31:0*/ __PVT__outstand_req_atmo_wr;
        IData/*31:0*/ __PVT__outstand_req_atmo_rd_nxt;
        IData/*31:0*/ __PVT__outstand_req_atmo_rd;
        IData/*31:0*/ __PVT__cmd_isatmo_wr_atmo_rd_in_outstd_ph3;
        IData/*31:0*/ __PVT__vld_store_to_bn2;
        IData/*31:0*/ __PVT__vld_store_to_bn2_nxt;
        IData/*31:0*/ __PVT__vld_store_compbuf_2nd_for_snpdata;
        IData/*31:0*/ __PVT__vld_store_compbuf_2nd_for_snpdata_nxt;
        IData/*31:0*/ __PVT__outstand_prep_valid_nxt;
        VlWide<3>/*73:0*/ __PVT__rddata_respcmdq;
        VlWide<4>/*108:0*/ __PVT__rddata_drespcmdq;
        VlWide<4>/*108:0*/ __PVT__rddata_memrespcmdq;
        VlWide<4>/*108:0*/ __PVT__rddata_memrespcmdq_prepped;
        VlWide<5>/*154:0*/ __PVT__cmd_ph4_rsp;
        IData/*31:0*/ __PVT__rddata_cache_ph4;
        IData/*21:0*/ __PVT__req_share_vect_ph3;
        IData/*21:0*/ __PVT__req_share_vect_ph2;
        IData/*31:0*/ __PVT__itis_req_retry_2nd_pcrdgrant;
        IData/*31:0*/ __PVT__itis_req_retry_2nd_retryack;
        IData/*31:0*/ __PVT__clr_pcrdt_entry;
        IData/*31:0*/ __PVT__wren_retry_prio;
        IData/*31:0*/ __PVT__wrdata_cache_ph4_rsp;
        IData/*31:0*/ __PVT__wrdata_cache_ph5_rsp;
        IData/*31:0*/ __PVT__wrdata_cache_ph6_rsp;
        IData/*31:0*/ __PVT__wrdata_cache_ph6final_rsp;
        IData/*31:0*/ __PVT__wrdata_cache_ph4_req;
        IData/*31:0*/ __PVT__wrdata_cache_ph5_req;
        IData/*31:0*/ __PVT__wrdata_cache_ph6_req;
        IData/*31:0*/ __PVT__wrdata_cache_ph6final_req;
        IData/*31:0*/ __PVT__wrdata_cache_ph7final_req;
        VlWide<4>/*107:0*/ __PVT__wrdata_stat_req_ph4;
        VlWide<5>/*135:0*/ __PVT__wrdata_stat_common_ph3_req;
        VlWide<5>/*135:0*/ __PVT__wrdata_stat_common_ph3_rsp;
        VlWide<108>/*3455:0*/ __PVT__status_field_req;
        VlWide<108>/*3455:0*/ __PVT__status_field_req_nxt;
        VlWide<136>/*4351:0*/ __PVT__status_field_common;
        VlWide<136>/*4351:0*/ __PVT__status_field_common_nxt;
        IData/*21:0*/ __PVT__new_share_vect_ph3_req;
    };
    struct {
        IData/*21:0*/ __PVT__new_share_vect_ph3_rsp;
        VlWide<4>/*107:0*/ __PVT__rddata_statreg_req_ph3;
        VlWide<4>/*107:0*/ __PVT__rddata_statreg_req_ph4;
        VlWide<4>/*107:0*/ __PVT__rddata_statreg_req_rcvdatproc;
        VlWide<5>/*135:0*/ __PVT__rddata_statcommon_rsp_ph3;
        VlWide<5>/*135:0*/ __PVT__rddata_statcommon_rsp_ph4;
        IData/*21:0*/ __PVT__req_share_vect_ph4;
        IData/*21:0*/ __PVT__new_share_vect_req_m_ph3;
        IData/*21:0*/ __PVT__new_share_vect_rsp_m_ph3;
        IData/*21:0*/ __PVT__req_share_vect_m_ph3;
        IData/*21:0*/ __PVT__req_share_vect_m_qual_ph3;
        IData/*21:0*/ __PVT__moving_share_vect_m_ph3;
        IData/*21:0*/ __PVT__moving_share_vect_m_qual_ph3;
        VlWide<5>/*154:0*/ __PVT__cmd_req_ph2_pre;
        VlWide<5>/*154:0*/ __PVT__cm_cmdvalid_evict_pre;
        IData/*21:0*/ __PVT__moving_share_vect_ph4;
        IData/*21:0*/ __PVT__moving_share_vect_ph3;
        IData/*23:0*/ __PVT__seq_num_all;
        IData/*23:0*/ __PVT__seq_num_all_nxt;
        IData/*23:0*/ __PVT__seq_num_all_atom;
        IData/*23:0*/ __PVT__seq_num_all_atom_nxt;
        VlWide<39>/*1239:0*/ __PVT__colln_cmd_field;
        VlWide<39>/*1239:0*/ __PVT__colln_cmd_field_nxt;
        VlWide<7>/*223:0*/ __PVT__colln_cmd;
        VlWide<7>/*223:0*/ __PVT__colln_cmd_nxt;
        VlWide<5>/*154:0*/ __PVT__winner_colln_entry;
        VlWide<5>/*154:0*/ __PVT__sel_winner_entry;
        IData/*31:0*/ __PVT__colln_detected_outstq;
        IData/*31:0*/ __PVT__colln_atom_detected_outstq;
        IData/*31:0*/ __PVT__num_emptyloc_outstandq;
        IData/*31:0*/ __PVT__num_emptyloc_outstandq_nxt;
        IData/*27:0*/ __PVT__cm_flit_addr_sliced_pm_ph1;
        IData/*27:0*/ __PVT__cm_homeaddr_base_pm;
        IData/*28:0*/ __PVT__cm_homeaddr_limit_pm;
        IData/*27:0*/ __PVT__cm_homeaddr_base_sliced_pm;
        IData/*28:0*/ __PVT__cm_homeaddr_limit_sliced_pm;
        IData/*27:0*/ __PVT__noncm_flit_addr_sliced_pm_ph1;
        IData/*27:0*/ __PVT__noncm_homeaddr_base_pm;
        IData/*28:0*/ __PVT__noncm_homeaddr_limit_pm;
        IData/*27:0*/ __PVT__noncm_homeaddr_base_sliced_pm;
        IData/*28:0*/ __PVT__noncm_homeaddr_limit_sliced_pm;
        IData/*21:0*/ __PVT__share_vec_ph3;
        IData/*31:0*/ __PVT__cmd_timeout_flag;
        IData/*31:0*/ __PVT__cmd_timeout_flag_nxt;
        VlWide<18>/*575:0*/ __PVT__cmd_timeoutctr;
        VlWide<18>/*575:0*/ __PVT__cmd_timeoutctr_nxt;
        IData/*31:0*/ __PVT__service_timeout_flag;
        IData/*21:0*/ __PVT__sharevec_ph5_rsp;
        IData/*21:0*/ __PVT__sharevec_ph5_req;
        IData/*21:0*/ __PVT__new_share_vect_ph4_rsp;
        IData/*21:0*/ __PVT__new_share_vect_ph4_req;
        IData/*31:0*/ __PVT__clr_outstand_cmd;
        IData/*31:0*/ __PVT__clr_outstand_cmd_is_atom_rd;
        IData/*31:0*/ __PVT__rddata_cache_sel_ph3;
        IData/*31:0*/ __PVT__p;
        IData/*31:0*/ __PVT__q;
        IData/*23:0*/ __Vcellinp__sig_countones_0__share_vec;
        IData/*31:0*/ __PVT__select_req_datapath;
        IData/*31:0*/ __PVT__select_rsp_datapath;
        IData/*23:0*/ __Vcellinp__sig_countones_post_rsp__share_vec;
        IData/*23:0*/ __Vcellinp__sig_countones_post_req__share_vec;
        IData/*31:0*/ __PVT__unnamedblk1__DOT__i;
        IData/*31:0*/ __PVT__unnamedblk2__DOT__i;
        IData/*31:0*/ __PVT__unnamedblk3__DOT__i;
    };
    struct {
        IData/*31:0*/ __PVT__unnamedblk4__DOT__i;
        IData/*31:0*/ __PVT__unnamedblk5__DOT__i;
        IData/*31:0*/ __PVT__unnamedblk6__DOT__i;
        VlWide<5>/*154:0*/ __Vdly__cmd_ph2_req;
        VlWide<5>/*154:0*/ __Vdly__cmd_ph3_req;
        VlWide<5>/*154:0*/ __Vdly__cmd_ph3_rsp;
        IData/*31:0*/ __Vdly__rddata_cache_ph4;
        VlWide<5>/*154:0*/ __Vdly__cmd_ph4_req;
        VlWide<5>/*154:0*/ __Vdly__cmd_ph4_rsp;
        VlWide<136>/*4351:0*/ __Vdly__status_field_common;
        VlWide<108>/*3455:0*/ __Vdly__status_field_req;
        VlWide<4>/*107:0*/ __Vdly__rddata_statreg_req_ph4;
        VlWide<5>/*135:0*/ __Vdly__rddata_statcommon_rsp_ph4;
        IData/*31:0*/ __Vdly__wrdata_cache_ph5_rsp;
        IData/*31:0*/ __Vdly__wrdata_cache_ph6_rsp;
        IData/*31:0*/ __Vdly__wrdata_cache_ph5_req;
        IData/*31:0*/ __Vdly__wrdata_cache_ph6_req;
        IData/*31:0*/ __Vdly__wrdata_cache_ph7final_req;
        IData/*21:0*/ __Vdly__new_share_vect_ph4_rsp;
        IData/*21:0*/ __Vdly__new_share_vect_ph4_req;
        IData/*31:0*/ __Vdly__outstand_req_atmo_wr;
        IData/*31:0*/ __Vdly__outstand_req_atmo_rd;
        VlWide<24>/*767:0*/ __Vdly__outstand_cmd;
        IData/*31:0*/ __Vdly__vld_store_to_bn2;
        IData/*31:0*/ __Vdly__vld_store_compbuf_2nd_for_snpdata;
        IData/*31:0*/ __Vdly__outstand_cmd_invalid;
        IData/*31:0*/ __Vdly__num_emptyloc_outstandq;
        IData/*31:0*/ __Vdly__outstand_prep_valid;
        VlWide<18>/*575:0*/ __Vdly__cmd_timeoutctr;
        IData/*31:0*/ __Vdly__cmd_timeout_flag;
        VlWide<39>/*1239:0*/ __Vdly__colln_cmd_field;
        VlWide<7>/*223:0*/ __Vdly__colln_cmd;
        IData/*23:0*/ __Vdly__seq_num_all;
        IData/*23:0*/ __Vdly__seq_num_all_atom;
        VL_OUT64(__PVT__cmd_addr_ph3,51,0);
        VL_OUT64(__PVT__cache_tag_rd_ph2,35,0);
        VL_OUT64(__PVT__cache_tag_wr,35,0);
        VL_OUT64(__PVT__excl_load_addr,45,0);
        VL_OUT64(__PVT__excl_store_addr,45,0);
        VL_OUT64(__PVT__atom_addr,45,0);
        VL_OUTW(__PVT__wrdata_snpreqfifo,190,0,6);
        VL_OUTW(__PVT__wrdata_outcompfifo,180,0,6);
        VL_OUT64(__PVT__addr_outstandq_to_compdata,51,0);
        VlWide<5>/*150:0*/ __PVT__rddata_reqcmdq_withbypass_s;
        VlWide<5>/*150:0*/ __PVT__evict_req_s;
        VlWide<5>/*150:0*/ __PVT__sel_winner_entry_s;
        VlWide<5>/*150:0*/ __PVT__cm_cmd_s;
        VlWide<5>/*150:0*/ __PVT__cmd_ph1_req_s;
        VlWide<5>/*150:0*/ __PVT__cmd_ph2_req_s;
        VlWide<3>/*72:0*/ __PVT__cmd_ph3_rsp_s;
        VlWide<3>/*72:0*/ __PVT__cmd_ph3_rsp_nxt_s;
        VlWide<4>/*108:0*/ __PVT__cmd_ph3_datrsp_s;
        VlWide<5>/*150:0*/ __PVT__cmd_ph3_req_s;
        VlWide<52>/*1663:0*/ __PVT__outstand_cmd_addr;
        VlWide<52>/*1663:0*/ __PVT__outstand_cmd_addr_nxt;
        VlWide<4>/*108:0*/ __PVT__rddata_drespcmdq_s;
        VlWide<4>/*108:0*/ __PVT__rddata_memrespcmdq_s;
        VlWide<5>/*150:0*/ __PVT__cmd_ph4_req_s;
        VlWide<3>/*72:0*/ __PVT__cmd_ph4_rsp_s;
        QData/*35:0*/ __PVT__cache_tag_wr_rsp;
        QData/*35:0*/ __PVT__cache_tag_wr_rsp_nxt;
        QData/*35:0*/ __PVT__cache_tag_wr_req;
        QData/*35:0*/ __PVT__cache_tag_wr_req_nxt;
        VlWide<5>/*150:0*/ __PVT__cmd_req_ph2_pre_s;
    };
    struct {
        QData/*51:0*/ __PVT__cmd_addr_ph2_pre;
        QData/*51:0*/ __PVT__cmd_addr_ph2;
        QData/*51:0*/ __PVT__addr_clln_clearing;
        QData/*51:0*/ __PVT__addr_clln_clearing_nxt;
        VlWide<13>/*415:0*/ __PVT__colln_cmd_field_addr;
        QData/*51:0*/ __PVT__rddata_reqcmdq_addr;
        QData/*51:0*/ __PVT__rddata_cmq_addr;
        VlWide<3>/*72:0*/ __PVT__rddata_respcmdq_s;
        QData/*51:0*/ __PVT__cmd_ph5_req_addr_nxt;
        QData/*51:0*/ __PVT__cmd_ph5_req_addr;
        QData/*51:0*/ __PVT__cmd_ph6_req_addr;
        QData/*51:0*/ __Vdly__addr_clln_clearing;
        QData/*35:0*/ __Vdly__cache_tag_wr_rsp;
        QData/*35:0*/ __Vdly__cache_tag_wr_req;
        QData/*51:0*/ __Vdly__cmd_ph5_req_addr;
        QData/*51:0*/ __Vdly__cmd_ph6_req_addr;
        VlWide<52>/*1663:0*/ __Vdly__outstand_cmd_addr;
        VL_IN(__PVT__i_ucie_base_addresses[16],27,0);
        VL_IN(__PVT__i_ucie_limit_addresses[16],28,0);
        VlUnpacked<CData/*3:0*/, 16> __PVT__ucie_sliced_base_addresses;
        VlUnpacked<CData/*3:0*/, 16> __PVT__ucie_sliced_limit_addresses;
        VlUnpacked<CData/*3:0*/, 16> __PVT__ucie_flit_sliced_addr_ph1;
    };

    // INTERNAL VARIABLES
    Vsig_topology_top__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vsig_topology_top_sig_coherency_ctrlr__pi14(Vsig_topology_top__Syms* symsp, const char* v__name);
    ~Vsig_topology_top_sig_coherency_ctrlr__pi14();
    VL_UNCOPYABLE(Vsig_topology_top_sig_coherency_ctrlr__pi14);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
